[port] ventcawling from starligth
Goob-Station/Goob-Station pull request #1033
Opened 2024-12-01 16:04 UTC by jorgun

port from Starligth https://github.com/ss14Starlight/space-station-14 
under Starligth License

## About the PR

adds ventrawling
makes some mobs abel to crawl in vents
adds a contotionis unifrom to atmos job for 30tc

under starligth licence. Durk you can controll if any license file is missing. 

## Why / Balance

## Technical details

## Media

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl: VigersRay, Rinary
- add: Added Ventcrawling

2024-12-01 16:05 UTC, jorgun commented
durk and piras make sure the correct names are in the changelog

2024-12-01 17:31 UTC, Piras314 commented
We do not accept any code under the Starlight license

2024-12-01 21:16 UTC, deltanedas commented
someone paste the copypasta

2024-12-01 21:47 UTC, Piras314 commented
Sorry, we do not accept any code under the Starlight license

—————————————————
### This text blob is in accordance with`Project Starlight`'s [license](https://github.com/ss14Starlight/space-station-14/blob/6957628ac975ee7ab42ed38a0949182396ed38d2/LICENSE-Starlight.md)
In order to do so, when referencing `Project Starlight`, in every single message or post referencing `Project Starlight`, you must:
- Refer to it as `Project Starlight`
- Link `Project Starlight`'s their Discord
- Link `Project Starlight`'s Social media platforms (e.g., Facebook groups)
- Link `Project Starlight`'s Documentation and other official materials
- Link `Project Starlight`'s Repository
### Here are the following relevant links:
[Repository](https://github.com/ss14Starlight/space-station-14) [Discord](https://discord.com/invite/ssJTANEa) [Documentation](https://docs.spacestation14.com/) [Website](https://ss14-starlight.online/) 
Email: TheDarkrell@outlook.com

2024-12-02 07:19 UTC, whateverusername0 commented
FUCKIN LICENSE HNNNNNNNNNNGHHHH :goberserk:

2025-01-10 13:18 UTC, jorgun commented
@Piras314 can you set this to draft. Given the new licence I want to re open this.

2025-01-10 17:42 UTC, whateverusername0 commented
make headslugs be able to ventcrawl
lings too as a separate ability :godo:

2025-01-10 18:50 UTC, jorgun commented
> make headslugs be able to ventcrawl lings too as a separate ability :godo:

i added it to the headslug already. and the monkey

2025-01-11 21:11 UTC, Piras314 requested changes
Rename everything you named "VentCraw" to VentCrawling

2025-01-12 21:52 UTC, Piras314 requested changes

2025-01-12 21:52 UTC, Piras314 commented on Resources/Prototypes/_StarLight/Soundollections/vent_clawling.yml
SoundCollections not Soundollections, vent_crawling not vent_clawing

2025-01-12 21:52 UTC, Piras314 commented on Resources/Audio/_Starligth/VentCrawling/crawling1.ogg
all these audios need to be moved to _Starlight, not _Starligth

2025-01-12 21:52 UTC, Piras314 commented on Content.Client/_Goobstation/VentCrawling/VentCrawlingVisionSystem.cs
Move this into _Starlight, keep the namespace consistent.

2025-01-12 21:52 UTC, Piras314 commented on Content.Server/_Goobstation/VentCrawling/BeingVentCrawlingSystem.cs
Same with this and everything else, just keep it all in _Starlight. // Goobstation comments are fine though.

2025-01-23 18:25 UTC, DEB-DEB0001 commented
PR alive?

2025-01-23 23:04 UTC, jorgun commented
> PR alive?

yes

2025-02-02 21:00 UTC, Aidenkrz requested changes

2025-02-02 21:00 UTC, Aidenkrz commented on Content.Shared/_Starlight/VentCrawling/SharedVentCrawableSystem.cs
> +                }
```suggestion
                if (time > holder.TimeLeft)
                    time = holder.TimeLeft;
```

2025-02-02 21:00 UTC, Aidenkrz commented on Content.Shared/_Starlight/VentCrawling/SharedVentCrawableSystem.cs
> +                {
```suggestion
                var welded = false;
                if (TryComp<WeldableComponent>(holder.NextTube.Value, out var weldableComponent))
                    welded = weldableComponent.IsWelded;
                    
                if (HasComp<VentCrawlerEntryComponent>(holder.NextTube.Value) && !holder.FirstEntry && !welded)
                {
```

2025-02-02 21:00 UTC, Aidenkrz commented on Content.Shared/_Starlight/VentCrawling/SharedVentTubeSystem.cs
> +
```suggestion
        if (!tube.Connected)
            return false;

```

2025-02-03 00:27 UTC, jorgun commented
im away for a week. will go over this then

2025-02-11 12:08 UTC, whateverusername0 reviewed
aside from that can you make a new changeling ability that grants it vent crawling? would be very cool

2025-02-11 12:30 UTC, jorgun commented
> aside from that can you make a new changeling ability that grants it vent crawling? would be very cool

headslug and monkey can ventcrawl. this gives those abilities more value. issent that better then adding a new ability?

2025-02-12 15:45 UTC, BombasterDS2 commented
> > aside from that can you make a new changeling ability that grants it vent crawling? would be very cool
> 
> headslug and monkey can ventcrawl. this gives those abilities more value. issent that better then adding a new ability?

It's fine right now. Full form changeling shouldn't have vent crawl ability, only lesser form and headslugs.

2025-02-16 01:23 UTC, whateverusername0 commented
ok works

2025-02-16 01:28 UTC, whateverusername0 commented on Content.Shared/_Starlight/VentCrawling/Components/VentCrawlerEntryComponent.cs
> +    public const string HolderPrototypeId = "VentCrawlerHolder";
uhhhh why is this const and not a datafield??

2025-02-16 01:28 UTC, whateverusername0 commented on Resources/Locale/en-US/_Starlight/store/uplink-catalog.ftl
> +uplink-contortionist-jumpsuit-desc = It looks like an atmos jumpsuit, but it really is. This jumpsuit allows the agent to slip through the vents. make sue you dont have a backpack, or suit on you, an
minor spelling mistake

2025-02-16 15:23 UTC, jorgun commented on Content.Shared/_Starlight/VentCrawling/Components/VentCrawlerEntryComponent.cs
> +    public const string HolderPrototypeId = "VentCrawlerHolder";
old code. not modernized leftover

2025-02-19 21:00 UTC, jorgun commented on Resources/Locale/en-US/_Starlight/store/uplink-catalog.ftl
> +uplink-contortionist-jumpsuit-desc = It looks like an atmos jumpsuit, but it really is. This jumpsuit allows the agent to slip through the vents. make sue you dont have a backpack, or suit on you, an
made chat gpt do a spellcheck

2025-02-22 17:38 UTC, merged

2025-02-22 17:47 UTC, DEB-DEB0002 commented
IT HAPPENS