15 capacity burner
Goob-Station/Goob-Station pull request #1075
Opened 2024-12-05 06:59 UTC by a-person5660

## About the PR
burner rifle gets 5 extra bullets per mag

## Why / Balance
it was suggested on the discord, you kinda plow through bullets.
its also still like 2.5 TC per bullet :trollface: 

**Changelog**
:cl:
- tweak: The Burner assault rifle now has had its magazine capacity increased to 15 from 10.

2024-12-05 14:40 UTC, Piras314 commented
Just decrease the stupid mag cost

2024-12-06 12:45 UTC, JoeHammad1844 commented
what about 20 :troll:

2024-12-06 14:03 UTC, a-person5660 commented
actually, im gonna make it deal AP instead of 15 rounders :trollface:

2024-12-07 03:42 UTC, Piras314 reviewed
you increased the fire rate, made it AP, and decreased its cost? 😭

2024-12-07 17:01 UTC, a-person5660 commented
> you increased the fire rate, made it AP, and decreased its cost? 😭

Forgor to remove AP from the PR :trollface: 
Instead I'm leaving the price at 150 TC lol

2024-12-07 17:05 UTC, a-person5660 commented
![Uploading Screenshot_20241207_170445_Discord.jpg…]()

2024-12-07 19:57 UTC, TurboTrackerss14 commented on Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
>          Structural: 130 # if you were a wall would you like having a .50 cal anti materiel round go through you? (this breaks a normal wall in 3 shots, one mag goes through four normal walls, 10 roun
Comment should likely be updated due to the "one mag goes through x" calculation. 
Could just be removed tbh for "10 rounds to take down a reinf wall"

2024-12-09 14:28 UTC, Piras314 requested changes
Remove AP alltogether.

2024-12-11 22:55 UTC, merged