add some /tg/ gases
Goob-Station/Goob-Station pull request #1093
Opened 2024-12-06 09:08 UTC by marc-pelletier

## About the PR
Adds three new atmospheric gases, Healium, Nitrium, and their precursor BZ. (Primarily restored from whateverusername0's lost BZ pull request)

BZ is created by mixing plasma and nitrous oxide in an exothermic reaction. It's primary use is as a precursor in the generation of more complex gases, though for those seeking enlightenment, it is often used as a cheap substitute to frezon, albeit far more dangerous to consume.

Healium is created in an exothermic reaction by mixing BZ and frezon at below room temperatures. Healium is an expensive gas that has healing properties when inhaled, however, will also make you tired and slow.

Nitrium is created in an endothermic reaction by mixing nitrogen, tritium and bz in a chamber heated to 1500K. It is every bit as expensive as healium and works as a powerful stimulant when inhaled, enhancing the users speed and reflexes. Inhaling too much can cause lung failure. 

This code has been used on Funky Station without any noticeable hit to performance. 

## Why / Balance
Makes atmos gameplay more interesting and can increase cooperation between atmos and other roles on the station. 

## Technical details
I followed /tg/ formation and decomposition formulas as closely as I could. [Click here for an idea of what they are](https://i.redd.it/rl46009i1bb61.png)

## Media
[healium-production.webm](https://github.com/user-attachments/assets/55857c14-ea6f-41a7-9cfb-effd07ff9924)
[bz-effects.webm](https://github.com/user-attachments/assets/38184619-3cad-44fa-9cc5-27d41f407400)
[bz-slime-effects.webm](https://github.com/user-attachments/assets/95d65ed0-76ad-4f48-a07f-b21f502992ff)
[healium-effects.webm](https://github.com/user-attachments/assets/acfb940e-6d39-47e8-8470-918ee3c3afba)
(some older media - formation formulas have changed)

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
None

**Changelog**
:cl:
- add: Add BZ
- add: Add Healium
- add: Add Nitrium

2024-12-06 15:30 UTC, Aviu00 requested changes

2024-12-06 15:30 UTC, Aviu00 commented on Resources/Prototypes/Entities/Structures/Storage/Canisters/gas_canisters.yml
> +    - state: yellow
Unique sprites should be added for each canister.

2024-12-06 15:30 UTC, Aviu00 commented on Resources/Prototypes/Reagents/gases.yml
> +      - !type:NitriumMovespeedModifier
Why add another EntityEffect and not use existing MovespeedModifier?

2024-12-06 15:30 UTC, Aviu00 commented on Resources/Prototypes/Reagents/gases.yml
> +        key: Adrenaline
There should also be `component` data field.

2024-12-06 19:31 UTC, marc-pelletier commented on Resources/Prototypes/Reagents/gases.yml
> +      - !type:NitriumMovespeedModifier
So existing effects don't play too nicely with inhaled gases. Rather than applying lasting, consistent effects, your effect is only applied temporarily on each "breath". With Healium, this results in bursts of healing every second or so, which is fine for its purposes. With Nitrium, it was causing you to only have very short bursts of speed every second or so depending on the concentration of the gas. Increasing the effect time would somewhat help carry over to your next breath, but would compound to the point where you can run around for a full minute off of a few breaths of nitrium.

Ideally, I would get rid of NitriumMovespeedModifier and replace it with a modified version of AdjustReagent, which also doesn't work with gases. I'd put Nitrosyl Plasmide in the users blood and apply most of nitrium's effects to that chemical. Currently, the increase in movespeed works as intended while I work out a way of doing that.

2024-12-06 23:16 UTC, marc-pelletier commented on Resources/Prototypes/Entities/Structures/Storage/Canisters/gas_canisters.yml
> +    - state: yellow
I'd agree. New overlay sprites for the gases should also be done. I'm just very bad at spriting. 

At the moment, the only way to access the canisters is through the admin spawn menu.

2024-12-11 22:41 UTC, Aidenkrz commented
if this causes tps drops its getting reverted :trollface:

2024-12-11 22:41 UTC, merged