adds flaps wings emote to moths
Goob-Station/Goob-Station pull request #1117
Opened 2024-12-10 12:08 UTC by lanse12

## About the PR
added a "flaps wings" emote to moths and the sound for it

## Why / Balance
why not

## Media

https://github.com/user-attachments/assets/7e60110f-4b00-43d8-8739-d7ec9095339e

**Changelog**
:cl:
- add: Moths can now flap their wings.

2024-12-10 14:03 UTC, HenhenIII commented
Time to start using my dead character "Mista cloth" again

2024-12-11 01:58 UTC, JoeHammad1844 commented
sounds like he broke a bone.
also don't forget aflap

2024-12-11 22:59 UTC, Aidenkrz requested changes
all of this needs to have goob comments or be in goob namespace

2024-12-11 23:57 UTC, lanse12 commented
yea i think this is what you asked me to do

2024-12-12 06:15 UTC, Aidenkrz requested changes

2024-12-12 06:15 UTC, Aidenkrz commented on Resources/Audio/Voice/Moth/attributions.yml
> +- files: ["moth_flap.ogg"] #goob thingy
no reason to be here, should be in goob files, as well as with the actual audio file

2024-12-12 06:15 UTC, Aidenkrz commented on Resources/Locale/en-US/chat/emotes.ftl
> +chat-emote-name-flap = Flap
still needs to be in goob files

2024-12-12 06:15 UTC, Aidenkrz commented on Resources/Prototypes/Voice/speech_emotes.yml
> +- type: emote #goob thingy
should be in a goob file

2024-12-12 21:10 UTC, Aidenkrz requested changes

2024-12-12 21:10 UTC, Aidenkrz commented on Resources/Prototypes/Voice/speech_emote_sounds.yml
> -    Weh:
Why are you removing a ton of emotes here?

2024-12-12 21:10 UTC, Aidenkrz commented on Resources/Audio/Voice/Moth/attributions.yml
> -  source: "https://github.com/BeeStation/BeeStation-Hornet/blob/11ba3fa04105c93dd96a63ad4afaef4b20c02d0d/sound/emotes/"
dunno what you changed here but it needs to be how it originally was

2024-12-12 21:19 UTC, lanse12 commented on Resources/Prototypes/Voice/speech_emote_sounds.yml
> -    Weh:
oh that was the wrong file lmao

2024-12-12 21:25 UTC, lanse12 commented on Resources/Audio/Voice/Moth/attributions.yml
> -  source: "https://github.com/BeeStation/BeeStation-Hornet/blob/11ba3fa04105c93dd96a63ad4afaef4b20c02d0d/sound/emotes/"
it's the same as it originally was

2024-12-13 22:01 UTC, Piras314 approved these changes

2024-12-13 22:04 UTC, merged