Adds Roboticist Job
Goob-Station/Goob-Station pull request #1127
Opened 2024-12-11 02:00 UTC by JarlElbowses

## About the PR
This PR adds the roboticist job, complete with loadout changes and (hopefully) correct accesses. The job does not have any mapped spawns or doors configured to robotics access, but it should all be there to be mapped.

## Why / Balance
With shitmed being added, mechs, and IPCs, robotics is currently too busy of a job to fall under general science, and deserves its own dedicated job in sci. This will ensure that scientists focus on actual research while robotics can focus on...robotics!

## Technical details
This is probably really shitcode it's my first PR.

## Requirements
- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
-Adds Roboticist
-Adds Robotics loadouts
-Adds robotics access
-Removes robotics clothing from other sci jobs.

2024-12-11 02:05 UTC, starch70 commented
you should probably map this atleast to change all the roboticist doors and add spawns

dont forget to change the access reader on the robodrobe or whatever its called

also you need to add the access to HoP and the AllAccess group so cap and ERT roles can have it too

2024-12-11 02:07 UTC, JarlElbowses commented
> you should probably map this atleast to change all the roboticist doors and add spawns
> 
> dont forget to change the access reader on the robodrobe or whatever its called
> 
> also you need to add the access to HoP and the AllAccess group so cap and ERT roles can have it too
> 
> i'll actually PR that last one to ur repo rn buddy

Thankies for advice. I don't know how to map but I could try c:

2024-12-11 02:13 UTC, Aidenkrz requested changes

2024-12-11 02:13 UTC, Aidenkrz commented on Resources/Locale/en-US/_Goobstation/prototypes/access/accesses.ftl
> +id-card-access-level-robotics = Robotics
you put this ftl twice

2024-12-11 02:13 UTC, Aidenkrz commented on Resources/Locale/en-US/prototypes/access/accesses.ftl
> +id-card-access-level-robotics = Robotics
remove this one

2024-12-11 02:13 UTC, Aidenkrz commented on Content.Shared/Access/Components/IdCardConsoleComponent.cs
> +        "Robotics",
goob comment

2024-12-11 02:13 UTC, Aidenkrz commented on Resources/Prototypes/Access/misc.yml
> +  - Robotics
goob comment

2024-12-11 02:13 UTC, Aidenkrz commented on Resources/Prototypes/Entities/Objects/Tools/access_configurator.yml
> +      - Roboticist
goob comment

2024-12-11 02:13 UTC, Aidenkrz commented on Resources/Prototypes/Entities/Structures/Machines/vending_machines.yml
> +    access: [["Robotics"]]
goob comment

2024-12-11 02:13 UTC, Aidenkrz commented on Resources/Prototypes/Loadouts/Jobs/Science/scientist.yml
> -- type: loadout
comment this out and say why

2024-12-11 02:13 UTC, Aidenkrz commented on Resources/Prototypes/Loadouts/Jobs/Science/scientist.yml
> -- type: loadout
comment this out and say why

2024-12-11 02:13 UTC, Aidenkrz commented on Resources/Prototypes/Loadouts/Jobs/Science/scientist.yml
> -- type: loadout
comment this out and say why

2024-12-11 02:13 UTC, Aidenkrz commented on Resources/Prototypes/Loadouts/Jobs/Science/scientist.yml
> -- type: loadout
comment this out and say why

2024-12-11 02:13 UTC, Aidenkrz commented on Resources/Prototypes/Roles/Jobs/Science/research_director.yml
> +  - Robotics
goob comment

2024-12-11 02:13 UTC, Aidenkrz commented on Resources/Prototypes/Roles/Jobs/departments.yml
> +  - Roboticist
goob comment

2024-12-11 02:13 UTC, Aidenkrz commented on Resources/Prototypes/_Goobstation/Entities/Structures/Doors/Airlocks/access.yml
> +
??

2024-12-11 02:13 UTC, Aidenkrz commented on Resources/Prototypes/Access/research.yml
> +- type: accessLevel
you defined this twice

2024-12-11 02:13 UTC, Aidenkrz commented on Resources/Prototypes/_Goobstation/Access/research.yml
> +- type: accessLevel
you defined this twice, keep this one delete the other

2024-12-11 02:13 UTC, Aidenkrz commented on Resources/Prototypes/_Goobstation/Roles/Jobs/Science/roboticist.yml
> +    time: 14400 # 4 hours
6/6 is probably good here

2024-12-11 02:13 UTC, Aidenkrz commented on Resources/Prototypes/_Goobstation/Roles/Jobs/Science/roboticist.yml
> +    time: 14400 # 4 hours
6/8 is probably good here

2024-12-11 02:17 UTC, starch70 commented
> you should probably map this atleast to change all the roboticist doors and add spawns
> 
> dont forget to change the access reader on the robodrobe or whatever its called
> 
> also you need to add the access to HoP and the AllAccess group so cap and ERT roles can have it too
> 
> i'll actually PR that last one to ur repo rn buddy

nvm i cant figure out how to fork your repo but ADD IT TO THE ALL ACCESS GROUP AND HOP ACCESS!!

btw what durk means by the goobstation comment is adding the "# goobstation" stuff after all your changes (look at externals access for RD)

2024-12-11 12:24 UTC, JoeHammad1844 commented
> Thankies for advice. I don't know how to map but I could try c:

https://youtu.be/QR5vnmTwwxQ?si=NJiQ8zsYt3WqPKz8

2024-12-13 10:58 UTC, WhiteGorila commented
does this give robotocists binary headsets? or roboticist channel?

2024-12-13 12:52 UTC, JoeHammad1844 commented
> does this give robotocists binary headsets? or roboticist channel?

robotics headset should just be a reskinned science headset

2024-12-30 10:22 UTC, GitHubUser53123 commented
thats kinda roboticist

2025-01-05 01:37 UTC, Aidenkrz commented
1 month  no changes 👍

2025-01-05 01:37 UTC, closed without merging