Ported IPC wings from SimpleStation14
Goob-Station/Goob-Station pull request #1145
Opened 2024-12-13 14:36 UTC by ScyronX

## About the PR

Added wing marking for IPCs
## Why / Balance

**Changelog**

- add: Added IPC wings

2024-12-13 16:57 UTC, deltanedas commented
i wonder which character this is meant to be for

2024-12-13 17:05 UTC, HawkeyeBlade commented
> i wonder which character this is meant to be for

IPCs, no?

2024-12-13 22:02 UTC, Aidenkrz requested changes

2024-12-13 22:02 UTC, Aidenkrz commented on Resources/Locale/en-US/markings/wings.ftl
this needs to be in goob namespace..

2024-12-13 23:46 UTC, deltanedas commented
> > i wonder which character this is meant to be for
> 
> IPCs, no? Is the code saying otherwise? XD

V1 ultrakill

2024-12-14 05:49 UTC, ScyronX commented on Resources/Locale/en-US/markings/wings.ftl
Done

2024-12-14 18:44 UTC, merged