Tons of balance changes
Goob-Station/Goob-Station pull request #1157
Opened 2024-12-14 03:29 UTC by ARMOKS

## About the PR
- Adjusted most mech weapons' fire rates and energy consumption.
- Fixed mech battery drain from being EMP'd not being visible in the status menu
- Ling fleshmend and panacea now have unique chems (having three chems in fleshment caused one to be ignored) and are decently stronger
- Grabbing an infused blade now hardstuns you
- Goliaths stun for 3 seconds less
- Added evasion to part targeting
- Removed most bundles from uplink and replaced them with individual guns
- Fixed misinformation in stims description
- Tons of energy sword tweaks, they now easily delimb, and only reflect energy projectiles
- Desword does less damage but has better energy reflect than the normal esword, reduced price accordingly
- Fixed implant misinformation
- Tweaked a few shitty uplink prices
- Reduced Northstar stamina usage
-  Made toy esword use esword inhand sprite :godo:
- Changed how syndicate turret works, higher health and much higher firerate, but MUCH lower ammo count.
- Made edagger more quiet
- Evil fireaxe hits slower, costs more stamina, and deals more firestacks.
- Many ling and heretic abilities can now be done while cuffed.
- Ling armor slows you down less now
- Ling armblade does next to no base damage, but extremely high limb damage. Should make ling combat more exciting.
- Plasma rifle explodes less often at 3%
- Plasma Cutter does stam damage now
- Priest Ritual makes ichor

**Changelog**

:cl:
- add: Added evasion to part targeting
- add: New fleshmend and panacea chems for lings
- fix: fix implant misinformation
- fix: Fixed mech battery drain from being EMP'd not being visible in the status menu
- tweak: Adjusted most mech weapons' fire rates and energy consumption.
- tweak: Infused blades hardstun on grab
- tweak: Goliaths stun for 3 seconds less
- tweak: Removed most bundles from uplink and replaced them with individual guns
- tweak: Energy swords now easily delimb, and only reflect energy projectiles
- tweak: DEsword does less damage but has better energy reflect and is cheaper
- tweak: change a few minor uplink prices
- tweak: reduce northstar stam cost
- tweak: funny toy sword sprite
- tweak: edagger more quiet
- tweak: Fireaxe hits harder, slower, costs more stam, and does more firestacks.
- tweak: disposable turret fires faster, has less ammo, and more HP
- tweak: Many heretic and ling abilities can be done while cuffed
- tweak: less ling armor slowdown
- tweak: armblade does VERY little damage and is now a delimbing based weapon
- tweak: plasma rifle blows up less
- tweak: plasma cutter deals stam damage
- tweak: buff priest ritual

2024-12-14 03:40 UTC, a-person5660 commented
Could you make it so combat mechs can't move without a charged power cell :trollface:

2024-12-14 03:41 UTC, ARMOKS commented
> Could you make it so combat mechs can't move without a charged power cell :trollface:

It is done

2024-12-14 03:47 UTC, a-person5660 commented
One last thing, with the alchemy it's kinda impossible to do in a real round and impractical as its just omnizine but slightly better, I think adding other things you can make with it (that only require cooperation with one other department instead of most of them) and making the current product of it better would be cool.

2024-12-14 03:48 UTC, a-person5660 commented
Also yaml fail :trollface:

2024-12-14 03:52 UTC, ARMOKS commented
> One last thing, with the alchemy it's kinda impossible to do in a real round and impractical as its just omnizine but slightly better, I think adding other things you can make with it (that only require cooperation with one other department instead of most of them) and making the current product of it better would be cool.

yeah i added the base chems and whatnot first and am adding a couple dozen potions soon

2024-12-14 03:53 UTC, a-person5660 commented
Love to hear it, keep up the good work armok.

2024-12-14 04:33 UTC, Aviu00 requested changes

2024-12-14 04:33 UTC, Aviu00 commented on Content.Server/Mech/Systems/MechSystem.cs
> +        component.Energy = 0;
Don't set this to 0, reduce it by `EmpPulseEvent` `EnergyConsumption`.

2024-12-14 04:33 UTC, Aviu00 commented on Content.Server/_Goobstation/Heretic/EntitySystems/MansusGraspSystem.cs
> +            _stamina.TakeStaminaDamage(target, 110f);
No.

2024-12-14 04:33 UTC, Aviu00 commented on Content.Shared/Stunnable/StunOnContactComponent.cs
> +    public TimeSpan Duration = TimeSpan.FromSeconds(2);
Don't change the value in component. Edit yaml file.

2024-12-14 04:33 UTC, Aviu00 commented on Resources/Prototypes/Entities/Objects/Fun/toys.yml
> +      sprite: Objects/Weapons/Melee/e_sword.rsi
Make it so toy sword can be other colors, not just blue.

2024-12-14 04:33 UTC, Aviu00 commented on Resources/Prototypes/Entities/Objects/Weapons/Melee/e_sword.yml
> +    reflectProb: 0.5 #Goob rebalace
Check out #1137. I've made similar changes.

2024-12-14 04:33 UTC, Aviu00 commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/turrets.yml
> +      capacity: 25
What's the point of this? I don't really like these changes. Better make the turret to recharge ammo slowly.

2024-12-14 04:33 UTC, Aviu00 commented on Resources/Locale/en-US/_Goobstation/store/uplink-catalog.ftl
> +uplink-buldog-desc = Lean and mean: Contains the popular Bulldog Shotgun.
```suggestion
uplink-buldog-desc = Lean and mean: The popular Bulldog Shotgun.
```

2024-12-14 04:33 UTC, Aviu00 commented on Resources/Locale/en-US/_Goobstation/store/uplink-catalog.ftl
> +uplink-weapon-burner-desc = A bundle containing a Burner Heavy Rifle.
It's not a bundle is it?

2024-12-14 04:33 UTC, Aviu00 commented on Resources/Prototypes/_Goobstation/Heretic/Entities/Objects/Specific/heretic.yml
> +        - ReagentId: Ichor
Too op. Also, this should be a custom reagent that is poisonous to non-heretics.

2024-12-14 04:33 UTC, Aviu00 commented on Resources/Prototypes/_Goobstation/Changeling/Actions/changeling.yml
> +    chemicalCost: 30
No.

2024-12-14 04:33 UTC, Aviu00 commented on Resources/Prototypes/_Goobstation/Changeling/Entities/Objects/Weapons/Melee/changeling_armblade.yml
> +    clickPartDamageMultiplier: 10
How much damage does it deal to the body part? Multiplier of 10, sounds too strong.

2024-12-14 04:33 UTC, Aviu00 commented on Resources/Prototypes/_Goobstation/Heretic/Actions/Heretic/path_flesh.yml
> +    checkCanInteract: true
This shouldn't be usable while cuffed.

2024-12-14 04:39 UTC, BombasterDS2 commented
Stop returning BS crystals in protolathe. They're not supposed to be in protolathe because they are rare material that uses in very low amount of recipes. You also didn't fix anything about them - nor the price, nor effect.

2024-12-14 04:40 UTC, Aviu00 commented on Content.Server/_Goobstation/Heretic/EntitySystems/MansusGraspSystem.cs
> +            _stamina.TakeStaminaDamage(target, 110f);
Oh wait, I thought you made the mansus grasp hardstun.
Though it would be better if you remove `TakeStaminaDamage` and replace `TryKnockdown` with `TryParalyze`.

2024-12-14 05:15 UTC, gluesniffler commented on Content.Server/Mech/Systems/MechSystem.cs
> +        component.Energy = 0;
I was the one who gave him the code, upon closer inspection the issue was that the UI was just not being refreshed on EMP, the values were fine, so the `component.Energy` line can be removed.

2024-12-14 05:17 UTC, gluesniffler commented on Resources/Prototypes/_Goobstation/Heretic/Entities/Objects/Specific/heretic.yml
> +        - ReagentId: Ichor
I feel giving people a reason to hunt them for their items is more funny lol

2024-12-14 05:18 UTC, gluesniffler commented on Resources/Prototypes/_Goobstation/Changeling/Entities/Objects/Weapons/Melee/changeling_armblade.yml
> +    clickPartDamageMultiplier: 10
Severs in about... 3-5 hits? assuming you nail those hits in the first place that is. Heads have a 70% evade chance, normal limbs I think about 25-30% in this code?

2024-12-14 05:23 UTC, gluesniffler commented on Resources/Prototypes/_Goobstation/Changeling/Actions/changeling.yml
> +    chemicalCost: 30
If we go off values from /tg/, their changelings can have 75 chemicals max as per the DM code, and stasis costs 15 chemicals to use. So if anything this is still too expensive if we were to go off of their stuff.

2024-12-14 05:23 UTC, ARMOKS commented on Resources/Prototypes/Entities/Objects/Fun/toys.yml
> +      sprite: Objects/Weapons/Melee/e_sword.rsi
this was on purpose so its still somewhat identifiable as a toy

2024-12-14 05:24 UTC, gluesniffler commented on Resources/Prototypes/_Goobstation/Changeling/Actions/changeling.yml
> +    chemicalCost: 30
Also instead of just saying "No." give a reason, we're not fucking wizden.

2024-12-14 05:25 UTC, ARMOKS commented on Resources/Prototypes/Entities/Objects/Weapons/Melee/e_sword.yml
> +    reflectProb: 0.5 #Goob rebalace
will remove  the conflicting code, I would suggest giving esword 0% ballistic for counter purposes and also because how would it reflect a bullet anyway.

2024-12-14 05:27 UTC, ARMOKS commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/turrets.yml
> +      capacity: 25
Point of this is having the stopping power for a single target with the possibility of counter by sec, making it fire this fast lets you have a secure maints base while also being counterable by having either more than one person or wearing a bullet proof vest. Also it is reloadable with a long doafter

2024-12-14 05:28 UTC, Aviu00 commented on Resources/Prototypes/_Goobstation/Changeling/Actions/changeling.yml
> +    chemicalCost: 30
It's fine as it is currently. Also on tg it works differently I believe, you have to wait while in stasis, doesn't matter if you have chemicals or not.

2024-12-14 05:33 UTC, ARMOKS commented on Resources/Prototypes/_Goobstation/Heretic/Entities/Objects/Specific/heretic.yml
> +        - ReagentId: Ichor
Ichor is far weaker than its stats would suggest, especially with the 15 second delay from potion drinking to actual healing. Also,you can just take nightwatcher and Insta Heal to full health for the same knowledge cost.

2024-12-14 05:35 UTC, ARMOKS commented on Resources/Prototypes/_Goobstation/Heretic/Actions/Heretic/path_flesh.yml
> +    checkCanInteract: true
it is not

2024-12-14 05:36 UTC, ARMOKS commented on Resources/Prototypes/_Goobstation/Changeling/Entities/Objects/Weapons/Melee/changeling_armblade.yml
> +    clickPartDamageMultiplier: 10
it slices an unarmored bodypart off in 3-5 hits, did alot of testing with other players and we found this to be a sweetspot, also only works on sprite click. wideswing does less

2024-12-14 05:37 UTC, ARMOKS commented
> Stop returning BS crystals in protolathe. They're not supposed to be in protolathe because they are rare material that uses in very low amount of recipes. You also didn't fix anything about them - nor the price, nor effect.

price is 30 now and the effect is fine

2024-12-14 05:38 UTC, ARMOKS commented on Resources/Prototypes/Entities/Objects/Weapons/Melee/e_sword.yml
> +    reflectProb: 0.5 #Goob rebalace
If yours merges after should be fine, if before Ill change things around.

2024-12-14 05:39 UTC, ARMOKS commented on Resources/Prototypes/_Goobstation/Heretic/Entities/Objects/Specific/heretic.yml
> +        - ReagentId: Ichor
reduced to 30U, when I learn how to code more non YML stuff ill add the new chem

2024-12-14 05:41 UTC, ARMOKS commented on Resources/Prototypes/_Goobstation/Changeling/Actions/changeling.yml
> +    chemicalCost: 30
On 14 the meta is to downa  changeling and constantly stab them until burned, you need 60 seconds minimum to come back to life and quite a bit more if you are cuffed /  want a chance of escaping. Would like for this to be revisited and discussed in the future.

2024-12-14 06:05 UTC, ARMOKS commented
also I can join goob VC to discuss why I made some things the way they are

2024-12-14 06:13 UTC, Aviu00 commented on Resources/Prototypes/_Goobstation/Changeling/Entities/Objects/Weapons/Melee/changeling_armblade.yml
> +    clickPartDamageMultiplier: 10
Okay, will see how it plays out. Though armblade is the only option for ling, it dealing 5 damage may not be good. It would be nice if more melee options were added, like baystation ling has 3 different melee weapons. On goob it could be like: armblade - low damage overall but high damage to body parts, arm claw - normal damage, arm hammer - high damage, low attack speed, on hit it knocks down and knocks back the target but doesn't force to drop items.

2024-12-14 06:34 UTC, Aviu00 approved these changes

2024-12-14 06:34 UTC, Aviu00 commented on Resources/Locale/en-US/_Goobstation/store/uplink-catalog.ftl
> +uplink-buldog-desc = Contains the popular Bulldog Shotgun.
It doesn't contain it, it is a gun by itself.

2024-12-14 06:34 UTC, Aviu00 commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/turrets.yml
> +      capacity: 25
Okay, though it shouldn't probably have more fire rate than nukie turret, so make it 6. And it shouldn't really explode when out of ammo. It should break instead so you can repair it, you may tweak this if you can and want to.

2024-12-14 07:08 UTC, BombasterDS2 commented
> > Stop returning BS crystals in protolathe. They're not supposed to be in protolathe because they are rare material that uses in very low amount of recipes. You also didn't fix anything about them - nor the price, nor effect.
> 
> price is 30 now and the effect is fine

30 for one material. One BSCrystal contains 100 materials. 3000 for one crystal.

2024-12-14 07:10 UTC, BombasterDS2 commented
Still, i don't like idea that you can craft rare ore materials. There is a reason why you can't craft diamonds.

2024-12-14 07:18 UTC, ARMOKS commented
ill make them mining only when we have lavaland so salv actually does their job

2024-12-14 09:31 UTC, Ilya246 commented on Resources/Prototypes/_Goobstation/Changeling/Entities/Objects/Weapons/Melee/changeling_armblade.yml
> +    clickPartDamageMultiplier: 10
yeah i don't think this is good, armblade is the only good melee option lings have and i don't think delimbing is really all that useful, so i think this would just end up making it useless

2024-12-14 09:33 UTC, Ilya246 commented on Resources/Prototypes/_Goobstation/Changeling/Actions/changeling.yml
> +  description: Rise from the dead with full health. Costs 30 chemicals.
chemicalCost is 60 so why "Costs 30 chemicals"?

2024-12-14 09:36 UTC, Ilya246 commented
actually idea what if armblade had reflect

2024-12-14 12:01 UTC, a-person5660 commented
Make the plasma cutter do high limb damage :trollface:

2024-12-14 12:53 UTC, Aviu00 commented on Resources/Locale/en-US/_Goobstation/store/uplink-catalog.ftl
> +uplink-buldog-desc = A magazine fed semiauto shotgun.
Wrong, it's fullauto :godo:

2024-12-14 12:53 UTC, Aviu00 commented on Resources/Prototypes/Entities/Objects/Weapons/Melee/e_sword.yml
> +            Heat: 15    #Goob Station rebalance, was originally 12
Now that I think about it, 34 damage desword is fine if we suppose that #1137 gets merged, also any reflective weapons shouldn't have 0 spread, that would be too punishing for noobs who try to shoot it with a laser weapon.

2024-12-14 14:28 UTC, JoeHammad1844 commented
Explain how evasion works

2024-12-14 18:13 UTC, ARMOKS commented on Resources/Locale/en-US/_Goobstation/store/uplink-catalog.ftl
> +uplink-buldog-desc = A magazine fed semiauto shotgun.
armok vs uplink-buldog-desc part 3

2024-12-14 18:13 UTC, ARMOKS commented
> Make the plasma cutter do high limb damage :trollface:

based and doing this

2024-12-14 18:15 UTC, ARMOKS commented on Resources/Prototypes/Entities/Objects/Weapons/Melee/e_sword.yml
> +            Heat: 15    #Goob Station rebalance, was originally 12
I would argue that it is a _very_ important lesson for them to learn. :goberserk: surely they wont shoot it more than once or twice.

2024-12-14 18:16 UTC, ARMOKS commented
> Explain how evasion works

targeting a limb other than body has a chance for the other person to miss. head being highest at 70%

cutting off someones feet /  legs makes head easier to hit 

![image](https://github.com/user-attachments/assets/91d42907-7cbf-4d3d-974f-5bbbabbe4a9d)

2024-12-14 19:20 UTC, gluesniffler approved these changes
billions of flukies must deflect

2024-12-14 19:34 UTC, Ilya246 commented
actually what if lings had 2 melee weapons, one for delimbing and one current armblade

2024-12-14 19:50 UTC, Ilya246 commented
> > actually what if lings had 2 melee weapons, one for delimbing and one current armblade
> 
> I did bring up to armok in VC that you could potentially do sidegrades, or some form of progression where the armblade gets more damage based off of stages and depending on how many people you've absorbed, neat idea honestly.
> 
> Though theres not much reason to use the delimber one when you can just merk someone and absorb with less thought involved.

yeah i said that, delimber armblade is just useless, i don't think anyone will use it beyond being a meme ever

2024-12-14 19:56 UTC, ARMOKS commented
> > > actually what if lings had 2 melee weapons, one for delimbing and one current armblade
> > 
> > 
> > I did bring up to armok in VC that you could potentially do sidegrades, or some form of progression where the armblade gets more damage based off of stages and depending on how many people you've absorbed, neat idea honestly.
> > Though theres not much reason to use the delimber one when you can just merk someone and absorb with less thought involved.
> 
> yeah i said that, delimber armblade is just useless, i don't think anyone will use it beyond being a meme ever

it kills faster than the current one, it is FAR from useless

2024-12-14 19:59 UTC, Ilya246 commented
> it kills faster than the current one, it is FAR from useless

then i misunderstood how limb damage works, is that if you target the head or something?

2024-12-14 20:00 UTC, ARMOKS commented
> > it kills faster than the current one, it is FAR from useless
> 
> then i misunderstood how limb damage works, is that if you target the head or something?

join me in VC ill show you

2024-12-14 20:17 UTC, Aviu00 commented on Resources/Prototypes/Entities/Objects/Weapons/Melee/e_sword.yml
> +    reflectProb: 0.3 #Goob rebalace
```suggestion
    reflectProb: 0.25 #Goob rebalace
    otherTypeReflectProb: 0
```
I changed EnergyDaggerLoud proto but forgot about this one.

2024-12-14 20:37 UTC, Aviu00 approved these changes

2024-12-14 23:55 UTC, JoeHammad1844 commented
> > Explain how evasion works
> 
> 
> 
> targeting a limb other than body has a chance for the other person to miss. head being highest at 70%
> 
> 
> 
> cutting off someones feet /  legs makes head easier to hit 
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/91d42907-7cbf-4d3d-974f-5bbbabbe4a9d)
> 
> 

By the way you will crit anybody before shooting a limb enough times to disable it

2024-12-15 06:49 UTC, Ilya246 commented on Resources/Prototypes/_Goobstation/Changeling/Actions/changeling.yml
maybe also remove interaction checks from evo menu

2024-12-15 06:49 UTC, Ilya246 commented on Resources/Prototypes/Entities/Objects/Weapons/Melee/fireaxe.yml
> +    attackRate: 0.5  # goob edit
makes it significantly worse against structures, should probably increase structural to compensate

2024-12-15 06:49 UTC, Ilya246 commented on Resources/Prototypes/Catalog/uplink_catalog.yml
> +    Telecrystal: 30 # goob
i'd say go balling and also give them chameleon like thief gloves, if they become too op increase price to 40 later

2024-12-15 06:49 UTC, Ilya246 commented on Resources/Locale/en-US/store/uplink-catalog.ftl
> +uplink-scram-implanter-desc = An implant which teleports you within a large radius. Attempts to teleport you onto an unobstructed tile. May sometimes fail to do so. Life insurance not included.
could mention it's self-recharging

2024-12-15 06:49 UTC, Ilya246 commented on Resources/Prototypes/_Goobstation/Reagents/medicine.yml
> +            amount: -3.0
i think it should just purge bloodstream of everything like charcoal, though that'd also flush fleshmend if active
if this is done, add to its description "Purges you of all chemicals. This may interfere with other abilities, such as fleshmend or ephedrine overdose."
plus same suggeston as to fleshmend, set metabolism rate to like 2

2024-12-15 06:49 UTC, Ilya246 commented on Resources/Prototypes/_Goobstation/Reagents/medicine.yml
> +            type: Remove
maybe also remove muteness

2024-12-15 16:41 UTC, ARMOKS commented on Resources/Prototypes/_Goobstation/Changeling/Actions/changeling.yml
I tried but it’s actually impossible for both heretic and ling for some reason

2024-12-17 22:09 UTC, merged