melee aim assist
Goob-Station/Goob-Station pull request #1180
Opened 2024-12-15 10:30 UTC by Ilya246

## About the PR
adds aim assist to melee:
- if you hit something, remember it
- if something is remembered and you hit air within 1 tile of it, it will instead hit it

## Why / Balance
click combat is rather frustrating sometimes and relies on skill, this makes it be that way less

## Technical details
see diff it's small

## Media
https://github.com/user-attachments/assets/f8744c45-d7ff-433e-9a1d-bf9ccd1122a2

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- add: Melee click combat aim assist. If you hit something, subsequent clicks may now be some distance from it and still hit.

2024-12-15 10:34 UTC, WhiteGorila commented
Mald pr don't merge get robust

2024-12-15 10:36 UTC, HenhenIII commented
Get robust

2024-12-15 10:37 UTC, Ilya246 commented
mald responses, if you're robust you wouldn't be relying on others players being bad at clicking

2024-12-15 10:39 UTC, WhiteGorila commented
> mald responses, if you're robust you wouldn't be relying on others players being bad at clicking

>Other people are unrobust that makes you unrobust for beating them

Mald

2024-12-15 12:03 UTC, Aviu00 commented
Good but it only should work on mobs, not walls or anything. Also there should be a visual indicator (like a circle around cursor), you should be able to clear target via hotkey or when exiting combat mode or it should clear automatically after some time.

2024-12-15 12:18 UTC, AgentePanela commented
that soo cool

2024-12-15 12:24 UTC, Ilya246 commented
> Good but it only should work on mobs, not walls or anything. Also there should be a visual indicator (like a circle around cursor), you should be able to clear target via hotkey or when exiting combat mode or it should clear automatically after some time.

i think i could make it only work on non-static entities and clear the target when you exit combat mode

2024-12-15 15:06 UTC, Ilya246 commented
now ignores puddles and other unattackable objects for aim assist and will not aim assist for static objects like walls

2024-12-15 15:41 UTC, TurboTrackerss14 commented
While I will hold back my "mald comment" regarding monumental skill issues and considering "aim assist for click combat, to prevent mouse click skill gamerism" a stupid argument. 

This has a fairly big risk to cause bigger issues when stacked along with #1157 should it be merged. 
#1157 by itself covers combat changes and a more indepth design than "Just autoaim at them to buff LMB combat". 

While I agree that wideswing combat has became the defacto since upstream removed the 1.25 multiplier on LMB swings, moving all the way to making LMB a single click skill check is not it. 

#1157 actually gives intensives to use LMB swings by widening its usecase, instead of just making LMB swings easier. 

The SINGLE time I could see this being useful is also where it could be stupid to have;
>Tider is being chased by secoff
>Tider rushes into crowd to evade the stunbaton forcing the secoff to actually aim. 
compared to
>Tider is being chased by secoff
>Tider rushes into crowd and still gets autoaimed by a secoff gamer because its nearly impossible to miss now

Such interactions push sec to actually push others away and try to disperse the crowd to get their arrest. 
Any other time, just click the pixels gamer.

2024-12-15 15:42 UTC, 0tito commented
I agree with this pr as long as its toggleable and each hit has a 50% chance of insta gibbing you

2024-12-15 15:49 UTC, Ilya246 commented
> While I will hold back my "mald comment" regarding monumental skill issues and considering "aim assist for click combat, to prevent mouse click skill gamerism" a stupid argument.
> 
> This has a fairly big risk to cause bigger issues when stacked along with #1157 should it be merged. #1157 by itself covers combat changes and a more indepth design than "Just autoaim at them to buff LMB combat".
> 
> While I agree that wideswing combat has became the defacto since upstream removed the 1.25 multiplier on LMB swings, moving all the way to making LMB a single click skill check is not it.
> 
> #1157 actually gives intensives to use LMB swings by widening its usecase, instead of just making LMB swings easier.
> 
> The SINGLE time I could see this being useful is also where it could be stupid to have;
> 
> > Tider is being chased by secoff
> > Tider rushes into crowd to evade the stunbaton forcing the secoff to actually aim.
> > compared to
> > Tider is being chased by secoff
> > Tider rushes into crowd and still gets autoaimed by a secoff gamer because its nearly impossible to miss now
> 
> Such interactions push sec to actually push others away and try to disperse the crowd to get their arrest. Any other time, just click the pixels gamer.

so what's your argument, exactly? also reminder that on goob wideswings take stamina so they're back to kind of being a different mode of attacking rather than the aim assist they are on wiz, which means normal clicking should now need its own aim assist

2024-12-15 15:52 UTC, WhiteGorila commented
> > While I will hold back my "mald comment" regarding monumental skill issues and considering "aim assist for click combat, to prevent mouse click skill gamerism" a stupid argument.
> > This has a fairly big risk to cause bigger issues when stacked along with #1157 should it be merged. #1157 by itself covers combat changes and a more indepth design than "Just autoaim at them to buff LMB combat".
> > While I agree that wideswing combat has became the defacto since upstream removed the 1.25 multiplier on LMB swings, moving all the way to making LMB a single click skill check is not it.
> > #1157 actually gives intensives to use LMB swings by widening its usecase, instead of just making LMB swings easier.
> > The SINGLE time I could see this being useful is also where it could be stupid to have;
> > > Tider is being chased by secoff
> > > Tider rushes into crowd to evade the stunbaton forcing the secoff to actually aim.
> > > compared to
> > > Tider is being chased by secoff
> > > Tider rushes into crowd and still gets autoaimed by a secoff gamer because its nearly impossible to miss now
> > 
> > 
> > Such interactions push sec to actually push others away and try to disperse the crowd to get their arrest. Any other time, just click the pixels gamer.
> 
> so what's your argument, exactly? also reminder that on goob wideswings take stamina so they're back to kind of being a different mode of attacking rather than the aim assist they are on wiz, which means normal clicking should now need its own aim assist

This is fucking stupid, what you need isnt aim assist what you need is to get better at the fucking game. People don't need to be treated like children, click the sprite, It's not that hard.

2024-12-15 15:53 UTC, TurboTrackerss14 commented
>LMB Swings 
- Requires targetting
+ No Stamina cost
>RMB swings
+ Requires minimal to no targetting (depending on swing or stab) 
- Stamina cost dependant on weapon

"lets remove the negative from LMB swings" ???

2024-12-15 15:54 UTC, Ilya246 commented
> > LMB Swings
> 
>     * Requires targetting
> 
> 
>     * No Stamina cost
> 
> 
> > RMB swings
> 
>     * Requires minimal to no targetting (depending on swing or stab)
> 
> 
>     * Stamina cost dependant on weapon
> 
> 
> "lets remove the negative from LMB swings" ???

i'm saying targeting/skill-reliance shouldn't be a (balancing) factor and should just be minimised and not considered for tradeoffs

2024-12-15 15:57 UTC, 0tito commented
> i'm saying targeting/skill-reliance shouldn't be a (balancing) factor and should just be minimised and not considered for tradeoffs

I dont agree with this. Skill is and should be a balancing factor, yes its an rp game, but combat overall should be skill based to some extent, imagine if you add aimbot to guns like npcs have, how do you even fight that, obviusly this pr isnt that extreme, but i dont think its a good idea tho.

2024-12-15 15:58 UTC, Ilya246 commented
> I dont agree with this. Skill is and should be a balancing factor, yes its an rp game, but combat overall should be skill based to some extent, imagine if you add aimbot to guns like npcs have, how do you even fight that, obviusly this pr isnt that extreme, but i dont think its a good idea tho.

you fight that by working smarter, not harder, which is my point
you should use tactics and preparation to win and not better mouse skills

2024-12-15 16:04 UTC, 0tito commented
You work smarter AND harder
Yes, some situations should be able to be won by preparing in advance, but skill should to be a part of it.

In my opinion this game has a balance of 2 types of skill, knowledge and mechanical skills, and i think it should be kept that way.

 Theres alredy plenty of ways to prepare in advance for situations and win them without requiring mechanical skills,  and i dont think we should make the mechanical skill part of this game less important.

2024-12-15 16:10 UTC, WhiteGorila commented
> > Theres alredy plenty of ways to prepare in advance for situations and win them without requiring mechanical skills, and i dont think we should make the mechanical skill part of this game less important.
> 
> click combat is one of the most skill-demanding parts while also being one of the most frustrating and least interesting

Literally every single game you click a button to kill people, how is that hard to do? "Click combat isn't interesting" YEAH ITS MEANT TO BE BASIC YOU CLICK THE BUTTON AND IF YOU DONT SUCK THEY DIE

It's literally just a skill issue. Your trying to invalidate people who are actually decent at the game and have EARNED their level of skill because YOUR bad at it.

2024-12-15 16:12 UTC, Ilya246 commented
> It's literally just a skill issue. Your trying to invalidate people who are actually decent at the game and have EARNED their level of skill because YOUR bad at it.

> mald responses, if you're robust you wouldn't be relying on others players being bad at clicking

2024-12-15 16:16 UTC, Sarahon commented
Considering you have multiple options that doesn't always require melee(majority of the time, range is king) I don't really think this is necessary really. Especially with wide swing. Play to your strengths, I am not "robust" but I can utilise other mechanics in the game to get what I need.

2024-12-15 16:39 UTC, Ilya246 commented
> With my PR sprite clicking is rewarded with limb damage, this will make it absurdly strong, also it would be cool to keep skill based things skill based

so could change it in accordance with this if merged
as for whether this is a good change could commit democracy and see if the general server populace agrees because the people who go here and people who go on servers are 2 separate circles on a venn diagram

2024-12-15 16:45 UTC, ARMOKS commented
> > With my PR sprite clicking is rewarded with limb damage, this will make it absurdly strong, also it would be cool to keep skill based things skill based
> 
> so could change it in accordance with this if merged as for whether this is a good change could commit democracy and see if the general server populace agrees because the people who go here and people who go on servers are 2 separate circles on a venn diagram

The goobstation discord very much does not like this change from what I have seen

2024-12-15 16:49 UTC, Ilya246 commented
> > > With my PR sprite clicking is rewarded with limb damage, this will make it absurdly strong, also it would be cool to keep skill based things skill based
> > 
> > 
> > so could change it in accordance with this if merged as for whether this is a good change could commit democracy and see if the general server populace agrees because the people who go here and people who go on servers are 2 separate circles on a venn diagram
> 
> The goobstation discord very much does not like this change from what I have seen

none of them actually play on servers

2024-12-15 16:50 UTC, BasedUser commented
ilya is better than me at melee pvp

2024-12-15 17:16 UTC, Sarahon commented
> [Ilya246](/Ilya246)

Interesting accusation.

2024-12-15 17:37 UTC, Plyushsune commented
> > > While I will hold back my "mald comment" regarding monumental skill issues and considering "aim assist for click combat, to prevent mouse click skill gamerism" a stupid argument.
> > > This has a fairly big risk to cause bigger issues when stacked along with #1157 should it be merged. #1157 by itself covers combat changes and a more indepth design than "Just autoaim at them to buff LMB combat".
> > > While I agree that wideswing combat has became the defacto since upstream removed the 1.25 multiplier on LMB swings, moving all the way to making LMB a single click skill check is not it.
> > > #1157 actually gives intensives to use LMB swings by widening its usecase, instead of just making LMB swings easier.
> > > The SINGLE time I could see this being useful is also where it could be stupid to have;
> > > > Tider is being chased by secoff
> > > > Tider rushes into crowd to evade the stunbaton forcing the secoff to actually aim.
> > > > compared to
> > > > Tider is being chased by secoff
> > > > Tider rushes into crowd and still gets autoaimed by a secoff gamer because its nearly impossible to miss now
> > > 
> > > 
> > > Such interactions push sec to actually push others away and try to disperse the crowd to get their arrest. Any other time, just click the pixels gamer.
> > 
> > 
> > so what's your argument, exactly? also reminder that on goob wideswings take stamina so they're back to kind of being a different mode of attacking rather than the aim assist they are on wiz, which means normal clicking should now need its own aim assist
> 
> This is fucking stupid, what you need isnt aim assist what you need is to get better at the fucking game. People don't need to be treated like children, click the sprite, It's not that hard.

Why are you being a dick?

2024-12-15 17:41 UTC, WhiteGorila commented
> > > > While I will hold back my "mald comment" regarding monumental skill issues and considering "aim assist for click combat, to prevent mouse click skill gamerism" a stupid argument.
> > > > This has a fairly big risk to cause bigger issues when stacked along with #1157 should it be merged. #1157 by itself covers combat changes and a more indepth design than "Just autoaim at them to buff LMB combat".
> > > > While I agree that wideswing combat has became the defacto since upstream removed the 1.25 multiplier on LMB swings, moving all the way to making LMB a single click skill check is not it.
> > > > #1157 actually gives intensives to use LMB swings by widening its usecase, instead of just making LMB swings easier.
> > > > The SINGLE time I could see this being useful is also where it could be stupid to have;
> > > > > Tider is being chased by secoff
> > > > > Tider rushes into crowd to evade the stunbaton forcing the secoff to actually aim.
> > > > > compared to
> > > > > Tider is being chased by secoff
> > > > > Tider rushes into crowd and still gets autoaimed by a secoff gamer because its nearly impossible to miss now
> > > > 
> > > > 
> > > > Such interactions push sec to actually push others away and try to disperse the crowd to get their arrest. Any other time, just click the pixels gamer.
> > > 
> > > 
> > > so what's your argument, exactly? also reminder that on goob wideswings take stamina so they're back to kind of being a different mode of attacking rather than the aim assist they are on wiz, which means normal clicking should now need its own aim assist
> > 
> > 
> > This is fucking stupid, what you need isnt aim assist what you need is to get better at the fucking game. People don't need to be treated like children, click the sprite, It's not that hard.
> 
> Why are you being a dick?

What's your argument?
>Posts multiple arguments
So what's your argument?

Why am I being a dick? Why is this guy being an idiot? I'll praise you if you make a good pr and I'll call you a fucking dumbass if you make a bad one. Simple as.

2024-12-15 17:45 UTC, Plyushsune commented
> > > > > While I will hold back my "mald comment" regarding monumental skill issues and considering "aim assist for click combat, to prevent mouse click skill gamerism" a stupid argument.
> > > > > This has a fairly big risk to cause bigger issues when stacked along with #1157 should it be merged. #1157 by itself covers combat changes and a more indepth design than "Just autoaim at them to buff LMB combat".
> > > > > While I agree that wideswing combat has became the defacto since upstream removed the 1.25 multiplier on LMB swings, moving all the way to making LMB a single click skill check is not it.
> > > > > #1157 actually gives intensives to use LMB swings by widening its usecase, instead of just making LMB swings easier.
> > > > > The SINGLE time I could see this being useful is also where it could be stupid to have;
> > > > > > Tider is being chased by secoff
> > > > > > Tider rushes into crowd to evade the stunbaton forcing the secoff to actually aim.
> > > > > > compared to
> > > > > > Tider is being chased by secoff
> > > > > > Tider rushes into crowd and still gets autoaimed by a secoff gamer because its nearly impossible to miss now
> > > > > 
> > > > > 
> > > > > Such interactions push sec to actually push others away and try to disperse the crowd to get their arrest. Any other time, just click the pixels gamer.
> > > > 
> > > > 
> > > > so what's your argument, exactly? also reminder that on goob wideswings take stamina so they're back to kind of being a different mode of attacking rather than the aim assist they are on wiz, which means normal clicking should now need its own aim assist
> > > 
> > > 
> > > This is fucking stupid, what you need isnt aim assist what you need is to get better at the fucking game. People don't need to be treated like children, click the sprite, It's not that hard.
> > 
> > 
> > Why are you being a dick?
> 
> What's your argument?
> 
> > Posts multiple arguments
> > So what's your argument?
> 
> Why am I being a dick? Why is this guy being an idiot? I'll praise you if you make a good pr and I'll call you a fucking dumbass if you make a bad one. Simple as.

How is he an idiot? All he made was aim assist. (which btw is a core Qol setting found in nearly every game)
Your probably not gonna notice it.

2024-12-15 17:50 UTC, WhiteGorila commented
> > > > > > While I will hold back my "mald comment" regarding monumental skill issues and considering "aim assist for click combat, to prevent mouse click skill gamerism" a stupid argument.
> > > > > > This has a fairly big risk to cause bigger issues when stacked along with #1157 should it be merged. #1157 by itself covers combat changes and a more indepth design than "Just autoaim at them to buff LMB combat".
> > > > > > While I agree that wideswing combat has became the defacto since upstream removed the 1.25 multiplier on LMB swings, moving all the way to making LMB a single click skill check is not it.
> > > > > > #1157 actually gives intensives to use LMB swings by widening its usecase, instead of just making LMB swings easier.
> > > > > > The SINGLE time I could see this being useful is also where it could be stupid to have;
> > > > > > > Tider is being chased by secoff
> > > > > > > Tider rushes into crowd to evade the stunbaton forcing the secoff to actually aim.
> > > > > > > compared to
> > > > > > > Tider is being chased by secoff
> > > > > > > Tider rushes into crowd and still gets autoaimed by a secoff gamer because its nearly impossible to miss now
> > > > > > 
> > > > > > 
> > > > > > Such interactions push sec to actually push others away and try to disperse the crowd to get their arrest. Any other time, just click the pixels gamer.
> > > > > 
> > > > > 
> > > > > so what's your argument, exactly? also reminder that on goob wideswings take stamina so they're back to kind of being a different mode of attacking rather than the aim assist they are on wiz, which means normal clicking should now need its own aim assist
> > > > 
> > > > 
> > > > This is fucking stupid, what you need isnt aim assist what you need is to get better at the fucking game. People don't need to be treated like children, click the sprite, It's not that hard.
> > > 
> > > 
> > > Why are you being a dick?
> > 
> > 
> > What's your argument?
> > > Posts multiple arguments
> > > So what's your argument?
> > 
> > 
> > Why am I being a dick? Why is this guy being an idiot? I'll praise you if you make a good pr and I'll call you a fucking dumbass if you make a bad one. Simple as.
> 
> How is he an idiot? All he made was aim assist. (which btw is a core Qol setting found in nearly every game) Your probably not gonna notice it.

Aim assist is mostly in shooter games, specifically for console. You don't need aim assist, I can think of one game that uses aim assist as an integral function on PC and it's fucking doom where you literally can't move your camera up and down.

He's an idiot because of how he's acting, instead of acknowledgement he double downed and tried to get support on discord and when that didn't work he claimed that "they dont actually play on the servers" when faced with actual critique instead of backing their reasoning they just said "your actually the one Malding not me" which is the equivalent of "NUH UH"

Dosent matter if I notice it or not, I'm gonna robust noobs either way. Point is Integrity, you shouldn't have to turn on a literal fucking aimbot to be good at the game. Left click the sprite.

2024-12-15 18:16 UTC, Ilya246 commented
maybe cut down on the quote ladder
and no, unlike what you think i should've done, i'm not going to instantly close my PR just because a couple people said it's bad, considering said people didn't provide sufficient arguments for me to do so
and i will list all the potentially real arguments you've provided so far:
- makes mechanical skill less valuable (whether this is bad or good is a matter of opinion and i think it's good)
- may interfere with intent of armok's balance PR (just change the stats if this gets merged)

2024-12-15 18:19 UTC, WhiteGorila commented
> maybe cut down on the quote ladder and no, unlike what you think i should've done, i'm not going to instantly close my PR just because a couple people said it's bad, considering said people didn't provide sufficient arguments for me to do so and i will list all the potentially real arguments you've provided so far:
> 
> * makes mechanical skill less valuable (whether this is bad or good is a matter of opinion and i think it's good)
> * may interfere with intent of armok's balance PR (just change the stats if this gets merged)

Potentially real arguments you've shown so far:

Nothing

2-0

2024-12-15 18:24 UTC, Ilya246 commented
> Potentially real arguments you've shown so far:

yes, nothing except for:
- it makes the game less frustrating/annoying for many people
- allows wideswings to be made further different from click combat since with this, they're no longer supposed to serve the function of aim assist and are a full-fledged different attack mode

and things i consider good but which are likely a matter of opinion:
- less combat power discrepancy between gamerlords and not
- by extension, less learning time needed to be good at combat
- less luck-reliance in combat

2024-12-15 18:34 UTC, gluesniffler commented
wide swinging was a mistake, my desire to kill it grows with every passing day

2024-12-15 18:59 UTC, Sarahon commented
> * it makes the game less frustrating/annoying for many people
> * allows wideswings to be made further different from click combat since with this, they're no longer supposed to serve the function of aim assist and are a full-fledged different attack mode
> 
> and things i consider good but which are likely a matter of opinion:
> 
> * less combat power discrepancy between gamerlords and not
> * by extension, less learning time needed to be good at combat
> * less luck-reliance in combat

I dunno why the game shouldn't reward skill? The combat is already bare bones, you can at least be entertained by somebody with skill. 
Equally, this rewards even the "gamerlords" because they *can* and *will* utilise aim assist. The idea that this makes it "better for everyone" is kinda overly optimistic.

This will make it easier for antags to hit you, it will also make it easier for sec to hit you. For every gamerlord there's probably like 30 non-gamerlords. Skilled players can "dunk on the noobs", but they only got skilled via playing and getting better at the game. If this is an issue, then make time restrictions more realistic? 

I feel like it definitely could break immersion and cause a lot more frustration than even latency would, when you can clearly see a person missed you, but they got rewarded via aimbot. How would this not be considered frustrating? (it is when latency is involved.)

2024-12-15 19:06 UTC, Ilya246 commented
> I dunno why the game shouldn't reward skill?

it should, but it should ideally also not be frustrating; luck-based/skill-based things which the game (effectively) forces you to engage in tend to often be frustrating, and i'd say pixelhunt-based combat is such a thing

> Equally, this rewards even the "gamerlords" because they can and will utilise aim assist.

yes but you can only get ever so close to 100% hit rate, so not by much

> Skilled players can "dunk on the noobs", but they only got skilled via playing and getting better at the game. If this is an issue, then make time restrictions more realistic?

the issue isn't skill existing, see my first point in this comment

> I feel like it definitely could break immersion and cause a lot more frustration than even latency would, when you can clearly see a person missed you, but they got rewarded via aimbot. How would this not be considered frustrating? (it is when latency is involved.)

it's clientside which means it's exactly as if you just didn't miss the click, so no, this won't happen
immersion can be semi-solved by lowering the aimbot distance, i found 1.25 to be pretty good

2024-12-15 20:12 UTC, TurboTrackerss14 commented
Can you do a quick test for me that LastHit does or does not set on wideswing hit. 
because the way I am reading this right now screams that I can wideswing once, then "pixel hunt" them with this aim assist with zero stamina cost essentially replicating the wideswing 90 degree swing without the stamina cost.

2024-12-15 20:12 UTC, Nelliel-ss14 commented
This PR is so bad, I had to make an account to tell you, as a person IN the discord, and ACTIVELY plays on the server a few times a day, This PR is actually just mald for people refusing to learn how to combat and instead opting for an easy option. This isnt even remotely able to be compared as a QoL, since the only quality this improves is for lazy people refusing to learn how to get better from their mistakes in previous combat engagements.

2024-12-15 20:19 UTC, Ilya246 commented
> Can you do a quick test for me that LastHit does or does not set on wideswing hit.

it will not because wideswings are their own if-branch

> learn how to get better from their mistakes in previous combat engagements

simply just Get Good and improve your mouse movement through pure brainpower yes

2024-12-15 20:26 UTC, Nelliel-ss14 commented
> > Can you do a quick test for me that LastHit does or does not set on wideswing hit.
> 
> it will not because wideswings are their own if-branch
> 
> > learn how to get better from their mistakes in previous combat engagements
> 
> simply just Get Good and improve your mouse movement through pure brainpower yes

"Yes, I'm going to add auto aim so I do not have to get used to combat" The people good at combat are those that have over 1000 hours in game, its not pure brainpower, its muscle memory from being shit at combat and then learning from one's own mistake, its okay to suck at combat, just don't use it as an excuse to force a bad change onto other people, when clearly the majority says this is not good or ideal for the playerbase or the way the game plays

2024-12-15 20:39 UTC, Ilya246 commented
> The people good at combat are those that have over 1000 hours in game

should you need 1000 hours for this? ss14 isn't a cybersport

> just don't use it as an excuse to force a bad change onto other people, when clearly the majority says this is not good or ideal for the playerbase or the way the game plays

i don't think you're quite qualified to decide it's a "bad change", and the "majority" here is referring to about half of "github-using goob players", and not "goob players" which are groups with different compositions; therefore, the majority argument doesn't really work

to get a real public opinion on this PR that represents what the players actually want, you would have to make a poll among players in general

2024-12-15 21:33 UTC, ARMOKS commented
wait doesnt this also kinda ruin invisibility?

2024-12-15 22:07 UTC, Piras314 commented
Makes a lot of sense

2024-12-15 22:25 UTC, TurboTrackerss14 commented
> wait doesnt this also kinda ruin invisibility?

And, from what I am readying, it ignores identities because it just logs the uid.. 
Meaning I can slap the suspected ling once, then have a free ling check melee by keeping my combat enabled and "hitting nearby" people. 
if it auto aims, ling identity swap detected. 

Regardless of my personal convictions against adding aimassist to this game. 
This implementation is lacking when looked at deeper then "0.3ish tile range on hitbox"

2024-12-15 22:34 UTC, Piras314 requested changes
Forget the target if you move like 5 tiles away from them or something like that.

2024-12-15 23:02 UTC, ImWeax commented
> > I dont agree with this. Skill is and should be a balancing factor, yes its an rp game, but combat overall should be skill based to some extent, imagine if you add aimbot to guns like npcs have, how do you even fight that, obviusly this pr isnt that extreme, but i dont think its a good idea tho.
> 
> you fight that by working smarter, not harder, which is my point you should use tactics and preparation to win and not better mouse skills

Ah yes, my tactic: having a better weapon. Not being able to hit people more consistently because I have spent time practicing.

2024-12-15 23:09 UTC, ARMOKS commented
Just thought more and discussed this and it will fuck up combat with more than 1v1. Trying to stab the captain? Well you accidentally hit the clown once and now the captains just hovering around him and you can’t do anything.

2024-12-15 23:12 UTC, ImWeax commented
So, some thoughts:

This will make wideswing useless. Why would I wideswing when my left click is a guaranteed hit AND takes 0 stamina. RMB is balanced in that you might hit other stuff by accident, and in goob it also consumes stamina. The benefit of RMB is you have far more forgiving aim. 

This conflicts with other PRs which reward skilled use of LMB sprite clicking.

Having to aim is an intentional downside and balancing factor of LMB sprite clicking

This change will make the stun meta even more blatant. As previously mentioned, you can no longer go hide in a crowd of people to attempt to avoid being stun batoned. 

All melee 1 v 1 fights are determined by whoever either A) Hit first or B) has a higher DPS weapon. You're eliminating player skill expression from the equation.

2024-12-15 23:15 UTC, DiaAWAY commented
Won't this simply reduce all combat down to "whomever hits first"?

Also with it being a "sticky target" aim, it could have weird interactions in group combat - since it will effectivly prevent you from switching targets if they are close to each other?

If you wanted autoaim you would probably have to reduce it to automatically aiming at the nearest entity on your cursor when hitting, how would that interact with "unknown"\"invisibile" entities? 

If the combat is unsatisfying for people, I personally don't think that autoaim is the solution.

2024-12-15 23:35 UTC, Aviu00 requested changes
Make it so instead of hitting a person to target them, you have to alt-click them while in combat mode, and this really needs some sort of indicator like highlighting a person you are currently targeting in some color. This would make fighting in crowds much better. Also aim assist shouldn't work on invisible entities.

2024-12-16 00:17 UTC, Piras314 commented
Honestly this is a pretty bad solution, but not only that, I don't think this can really be done in a way that doesn't feel awful.

Even if I personally don't like how I have to zoom in 3x to be able to do melee combat because my monitor is small, I don't think this is worth it to "fix" that when it has a billion glaring issues and I can't think of a single way to do this that won't feel janky.

2024-12-16 00:17 UTC, closed without merging

2024-12-16 00:53 UTC, JoeHammad1844 commented
next PR: press R to reload guns :trollface:
skill shouldnt be a factor in reloading weapons, its QoL

2024-12-16 02:14 UTC, Ilya246 commented
> Honestly this is a pretty bad solution, but not only that, I don't think this can really be done in a way that doesn't feel awful.
> 
> Even if I personally don't like how I have to zoom in 3x to be able to do melee combat because my monitor is small, I don't think this is worth it to "fix" that when it has a billion glaring issues and I can't think of a single way to do this that won't feel janky.

another idea is a second wideswing that can only attack one target but doesn't take stamina

2024-12-16 13:14 UTC, Ilya246 commented
> > > Honestly this is a pretty bad solution, but not only that, I don't think this can really be done in a way that doesn't feel awful.
> > > Even if I personally don't like how I have to zoom in 3x to be able to do melee combat because my monitor is small, I don't think this is worth it to "fix" that when it has a billion glaring issues and I can't think of a single way to do this that won't feel janky.
> > 
> > 
> > another idea is a second wideswing that can only attack one target but doesn't take stamina
> 
> that would just make normal wideswinging useless.

it hits multiple targets at once

2024-12-16 22:04 UTC, ImWeax commented
> > > > Honestly this is a pretty bad solution, but not only that, I don't think this can really be done in a way that doesn't feel awful.
> > > > Even if I personally don't like how I have to zoom in 3x to be able to do melee combat because my monitor is small, I don't think this is worth it to "fix" that when it has a billion glaring issues and I can't think of a single way to do this that won't feel janky.
> > > 
> > > 
> > > another idea is a second wideswing that can only attack one target but doesn't take stamina
> > 
> > 
> > that would just make normal wideswinging useless.
> 
> it hits multiple targets at once

80% of combat in this game is a 1v1 or you want to focus a specific target in a group first. Wideswing is meant to have the disadvantage of hitting other people / things. You are trying to recreate wideswing without any disadvantages.