blob typo fixes
Goob-Station/Goob-Station pull request #1209
Opened 2024-12-18 14:08 UTC by lanse12

## About the PR
fixes typos related to blob shit

2024-12-19 02:14 UTC, JoeHammad1844 commented
the emergency shuttle shouldnt be called, anthougheversobeit

2024-12-19 16:54 UTC, Piras314 requested changes

2024-12-19 16:54 UTC, Piras314 commented on Resources/Locale/en-US/_Goobstation/blob/blob.ftl
> +blob-alert-detect = Confirmed outbreak of level 5 biohazard aboard the station. All personnel must contain the outbreak.
keep the old line here

2024-12-19 16:54 UTC, Piras314 commented on Resources/Locale/en-US/_Goobstation/blob/blob.ftl
> +        [one] There was one blob infection.
keep the old line here

2024-12-19 16:54 UTC, Piras314 commented on Resources/Locale/en-US/_Goobstation/blob/blob.ftl
> +ghost-role-information-blob-description = You are the Blob Infection. Consume the station.
the blob is fine, but the blob infection seems a bit silly to me

2024-12-20 22:35 UTC, lanse12 commented on Resources/Locale/en-US/_Goobstation/blob/blob.ftl
> +ghost-role-information-blob-description = You are the Blob Infection. Consume the station.
that's how it is on tg station bro

2024-12-20 22:36 UTC, lanse12 commented on Resources/Locale/en-US/_Goobstation/blob/blob.ftl
> +blob-alert-detect = Confirmed outbreak of level 5 biohazard aboard the station. All personnel must contain the outbreak.
that's how it is on tg station bro

2024-12-20 22:36 UTC, lanse12 commented on Resources/Locale/en-US/_Goobstation/blob/blob.ftl
> +        [one] There was one blob infection.
that's how it is on tg station bro

2024-12-21 02:15 UTC, Piras314 approved these changes
fair enough

2024-12-21 02:15 UTC, merged