Port Playing Cards
Goob-Station/Goob-Station pull request #1215
Opened 2024-12-18 21:17 UTC by RadsammyT

## About the PR
Ported playing cards to GoobStation from Frontier, from EstacaoPirata. Gamba is real now.

credits to Daniela for making the cards at EP. 
Leander-0 for porting to Frontier and whatson3 for making it good

You may obtain them during gameplay at a Games Vendor (3 in stock) or at lobby as a trinket in your loadout.

## Why / Balance
because i like gamba. and thought it would be amazing to see poker ops.

## Technical details

Due to the structure of Frontier's port of the playing cards, I found it real easy to literally just drag-n-drop any folders with `EstacaoPirata` in them (sans reverting some frontier changes to its prototypes) and put them in their respective folders with it just working.

so while it is a working port, its prolly gonna be a shit one for reasons unknown to me. that and I don't know if its required to put all of this in `_Goobstation` folders rather than what its in now, so ¯\\_(ツ)\_/¯

## Media

https://github.com/user-attachments/assets/feb09348-6301-4fa6-be8f-f81dad920c38

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Added Playing Cards. You may get them from the Games Vendor or as a trinket in your loadout.

2024-12-19 20:03 UTC, Day-OS commented
that might be the most awesome way of presenting this code I've seen yet! S2

I might add that the code has support for multilayered cards, so it is actually possible to port a complex card game like TGC into it, I'd love to see someone doing that haha!

2024-12-20 14:31 UTC, whateverusername0 commented
add mahjong next and i'm giving you all my goobcoins

2024-12-20 14:37 UTC, whateverusername0 requested changes
do whatever the bot said or tell the bot why he is wrong
also apply whatever changes i pointed to

2024-12-20 14:37 UTC, whateverusername0 commented on Content.Client/_EstacaoPirata/Cards/CardSpriteSystem.cs
> +        }
do what the ai said, the same thing caused void heretic to crash the server and i don't want that shit to repeat

2024-12-20 14:37 UTC, whateverusername0 commented on Content.Server/_EstacaoPirata/OpenTriggeredStorageFill/OpenTriggeredStorageFillSystem.cs
> +        Log.Debug("aaa");
this

2024-12-20 14:37 UTC, whateverusername0 commented on Content.Shared/_EstacaoPirata/Cards/Hand/CardHandSystem.cs
> +    public readonly EntProtoId CardHandBaseName = "CardHandBase";
add `[ValidatePrototypeId<EntityPrototype>]` attribute here just in case

2024-12-20 14:38 UTC, whateverusername0 commented
also playtest it thoroughly

2024-12-20 16:06 UTC, Aviu00 requested changes
Also flipped cards should probably be hidden if a person holds them in their hands to prevent other people from seeing them in strip menu.

2024-12-20 16:06 UTC, Aviu00 commented on Content.Client/_EstacaoPirata/Cards/CardSpriteSystem.cs
> +        foreach (var card in stack.Cards.TakeLast(cardCount))
Should do the same thing here as the rabbit said above in `TryAdjustLayerQuantity` method.

2024-12-20 21:11 UTC, RadsammyT commented on Content.Shared/_EstacaoPirata/Cards/Stack/CardStackSystem.cs
> +    public bool TryRemoveCard(EntityUid uid, EntityUid card, CardStackComponent? comp = null)
crash resolved. Shared CardStackSystem.OnActivate didn't actually set the handled argument when it was actually done

2024-12-20 21:12 UTC, RadsammyT commented on Content.Shared/_EstacaoPirata/Cards/Stack/CardStackSystem.cs
> +    public bool TryRemoveCard(EntityUid uid, EntityUid card, CardStackComponent? comp = null)
also I did somewhat implement the other thing you mentioned (auto 1-card convert) but for now it only happens when it its from an empty hand.
still need to figure out how to do the same thing on active items with `CardStackComponent`

2024-12-20 21:13 UTC, RadsammyT commented on Content.Shared/_EstacaoPirata/Cards/Hand/CardHandSystem.cs
> +    public readonly EntProtoId CardHandBaseName = "CardHandBase";
done

2024-12-20 21:14 UTC, RadsammyT commented on Content.Client/_EstacaoPirata/Cards/CardSpriteSystem.cs
> +        foreach (var card in stack.Cards.TakeLast(cardCount))
done

2024-12-20 21:17 UTC, RadsammyT commented on Content.Shared/_EstacaoPirata/Cards/Hand/CardHandSystem.cs
> +    public readonly EntProtoId CardHandBaseName = "CardHandBase";
all of these should be done
yell at me if it isnt

2024-12-20 21:30 UTC, RadsammyT commented on Content.Client/_EstacaoPirata/Cards/CardSpriteSystem.cs
> +        layerCount = int.Max(1, layerCount); // Frontier: you need one layer.
int.Max is an actual method within dotnet runtime
https://learn.microsoft.com/en-us/dotnet/api/system.int32.max?view=net-9.0

2024-12-21 00:03 UTC, RadsammyT commented on Content.Shared/_EstacaoPirata/Cards/Stack/CardStackSystem.cs
> +    public bool TryRemoveCard(EntityUid uid, EntityUid card, CardStackComponent? comp = null)
done

2024-12-21 01:00 UTC, RadsammyT commented on Content.Shared/_EstacaoPirata/Cards/Stack/CardStackSystem.cs
> +                _audio.PlayPredicted(firstComp.PlaceDownSound, Transform(first).Coordinates, user);
this is in `JoinStacks` where its literally just a wrapper to `TryJoinStacks` just so it can be used as a verb. and the try version also does the audio calls. If this was called via verb then the possibility exists that we'd dupe sounds.

should be changed so that it just calls `TryJoinStacks`

2024-12-21 01:01 UTC, RadsammyT commented on Content.Shared/_EstacaoPirata/Cards/Stack/CardStackSystem.cs
> +                _audio.PlayPredicted(firstComp.PlaceDownSound, Transform(firstStack).Coordinates, soundUser.Value);
should be changed so that its actually called on both.
and because of this `PlayPickupAnimation` has to be called on server otherwise shenanigans occur (if ran on both, animation dupes on client, etc.)

2024-12-21 05:21 UTC, RadsammyT commented
okay, it is currently just midnight and I am done addressing most of the reviews.
what remains is @Aviu00's review suggesting using `AppearanceSystem` rather than the original creator's method of constantly calling `UpdateSprite`.
which will be difficult for me because this is essentially the first time i've heard of it and will prolly see me refactoring the whole thing.
if anyone could help me with this, I will be very thankful and will give u all my goobcoin (~400)

2024-12-21 11:40 UTC, Aviu00 commented
> okay, it is currently just midnight and I am done addressing most of the reviews. what remains is @Aviu00's review suggesting using `AppearanceSystem` rather than the original creator's method of constantly calling `UpdateSprite`. which will be difficult for me because this is essentially the first time i've heard of it and will prolly see me refactoring the whole thing. if anyone could help me with this, I will be very thankful and will give u all my goobcoin (~400)

Actually, don't bother, it works currently for the most part. You'll only need to fix hand of cards always appearing as unflipped single card when client connects to the server. It works for deck of cards so just copy the logic from `CardDeckSystem` `Update` method to `CardHandSystem`, this might fix it.

2024-12-21 11:47 UTC, Aviu00 commented
And also, for example: when you take the second card from hand of cards with 2 cards in it, first card falls on the floor, they should both be in hands.

2024-12-21 14:16 UTC, RadsammyT commented on Content.Client/_EstacaoPirata/Cards/Hand/CardHandSystem.cs
> +        }
does this also apply to adding to the dictionary as well?

2024-12-21 15:16 UTC, RadsammyT commented
should be about everything done except for the hidden hands part. need to figure out how to get the hand's wielder uid (if any) and the clients own uid of the mob it controls.

or keep it as it is because its basically the only way you could "peek behind their shoulder" if you wanted to cheat or anything :godmode:

2024-12-21 16:01 UTC, Aviu00 commented
> should be about everything done except for the hidden hands part. need to figure out how to get the hand's wielder uid (if any) and the clients own uid of the mob it controls.

Edit `StrippableBoundUserInterface` and add extra check for cards in `AddInventoryButton` method.

2024-12-21 16:25 UTC, Aviu00 requested changes

2024-12-21 16:25 UTC, Aviu00 commented on Content.Client/_EstacaoPirata/Cards/Hand/CardHandSystem.cs
> +            if (!TryGetCardLayer(stack.Cards.Last(), out var _))
This needs to be slightly different from `CardDeckSystem`. This if statement can be removed I think.

2024-12-21 16:25 UTC, Aviu00 commented on Content.Client/_EstacaoPirata/Cards/Hand/CardHandSystem.cs
> +    private bool TryGetCardLayer(EntityUid card, out SpriteComponent.Layer? layer)
Can be removed.

2024-12-21 16:25 UTC, Aviu00 commented on Content.Client/_EstacaoPirata/Cards/Hand/CardHandSystem.cs
> +            sprite.LayerSetScale(0, new Vector2(1f, 1f));
```suggestion
        _cardSpriteSystem.TryAdjustLayerQuantity((uid, sprite, cardStack), comp.CardLimit);

        var cardCount = Math.Min(cardStack.Cards.Count, comp.CardLimit);

        // Frontier: zero/one card case
        if (cardCount <= 0)
        {
            _notInit[(uid, comp)] = 0;
            // Placeholder - we need to have a valid sprite.
            sprite.LayerSetVisible(0, true);
            sprite.LayerSetState(0, "singlecard_down_black");
            sprite.LayerSetOffset(0, new Vector2(0f, 0f));
            sprite.LayerSetScale(0, new Vector2(1f, 1f));
```

2024-12-21 17:51 UTC, RadsammyT commented on Content.Client/_EstacaoPirata/Cards/Hand/CardHandSystem.cs
> +            sprite.LayerSetScale(0, new Vector2(1f, 1f));
doing this reintroduces the card-desync-on-join bug I believe.

2024-12-21 17:53 UTC, RadsammyT commented on Content.Client/_EstacaoPirata/Cards/Hand/CardHandSystem.cs
> +            if (!TryGetCardLayer(stack.Cards.Last(), out var _))
if youre talking about the `TryGetCardLayer` if then alright. doesnt break anything from what I tested

2024-12-21 17:53 UTC, RadsammyT commented on Content.Client/_EstacaoPirata/Cards/Hand/CardHandSystem.cs
> +    private bool TryGetCardLayer(EntityUid card, out SpriteComponent.Layer? layer)
can't remove. made it as I was unable to call the one at `CardDeckSystem`.
the usage at `Update`, if removed, doesnt fuck things up but I cannot say the same for `UpdateSprite`. see below

2024-12-21 20:20 UTC, Aviu00 commented
If it doesn't work, then don't remove anything @RadsammyT

2024-12-21 20:22 UTC, Aviu00 requested changes

2024-12-21 20:22 UTC, Aviu00 commented on Content.Client/Inventory/StrippableBoundUserInterface.cs
> +                         EntMan.TryGetComponent<CardHandComponent>(hand.HeldEntity, out var _);
Use `HasComponent`.

2024-12-21 20:22 UTC, Aviu00 commented on Content.Client/Inventory/StrippableBoundUserInterface.cs
> +                         EntMan.TryGetComponent<CardHandComponent>(entity, out var _);
Same here.

2024-12-21 22:18 UTC, Aviu00 approved these changes

2024-12-29 18:40 UTC, merged