The Great gambling update.
Goob-Station/Goob-Station pull request #1221
Opened 2024-12-19 19:37 UTC by yglop

## About the PR
Adds lootbugs.

## Why / Balance
Goobers love gambling.

## Technical details
Shitcoded loot table.

## Media
Do you really need it?

## ToDo
- Sprites
- Spawn
- Cargo crates
- Replace moth stomach

**Changelog**
:cl:
- add: LootBugs.

2024-12-20 11:20 UTC, yglop commented
```
Error Message:
   System.Exception : Failed to delete map Packed
```

2024-12-20 14:36 UTC, Piras314 commented on Resources/Prototypes/_Goobstation/Entities/Mobs/NPCs/animals.yml
> +  description: It eats metal. Maybe it have eaten something valuable?
It eats metal, maybe it's eaten something of value?

2024-12-20 16:26 UTC, Aviu00 requested changes

2024-12-20 16:26 UTC, Aviu00 commented on Resources/Prototypes/_Goobstation/Entities/Markers/Spawners/random_loot.yml
> +- type: entity
Use `entityTable` instead of this.

2024-12-20 16:26 UTC, Aviu00 commented on Content.Server/_Goobstation/RandomChanceSpawner/RandomChanceSpawnerSystem.cs
> +    public override void Update(float frameTime)
Don't use `Update`. Make something like `SpawnLootOnDeathComponent` and spawn loot when loot bug dies. Or if you want it to spawn loot when it gets butchered, use `MapInit` event instead.

2024-12-20 16:26 UTC, Aviu00 commented on Content.Server/_Goobstation/RandomChanceSpawner/RandomChanceSpawnerSystem.cs
> +        if (!_timing.IsFirstTimePredicted)
This is unnecessary on server side.

2024-12-20 16:50 UTC, yglop commented on Resources/Prototypes/_Goobstation/Entities/Markers/Spawners/random_loot.yml
> +- type: entity
I shall rewrite the spell with your knowledge in mind, fella Wizard.

2024-12-23 08:11 UTC, whateverusername0 commented on Resources/Prototypes/_Goobstation/Entities/Markers/Spawners/random_loot.yml
> +      GoldRingGem: 0.001
where's my one in a million gibstick chance?

2024-12-24 11:36 UTC, yglop commented on Resources/Prototypes/_Goobstation/Entities/Markers/Spawners/random_loot.yml
> +      GoldRingGem: 0.001
done

2024-12-24 11:36 UTC, yglop commented on Content.Server/_Goobstation/RandomChanceSpawner/RandomChanceSpawnerSystem.cs
> +    public override void Update(float frameTime)
done

2024-12-24 11:36 UTC, yglop commented on Resources/Prototypes/_Goobstation/Entities/Markers/Spawners/random_loot.yml
> +- type: entity
did not find a way to use `entityTable` here

2024-12-24 12:22 UTC, whateverusername0 approved these changes
:godmode:

2024-12-24 12:55 UTC, Aviu00 approved these changes

2024-12-27 18:28 UTC, merged