25% Chance of ERT with Special Nuke Song when 50% or more of crew is dead during Nukeops
Goob-Station/Goob-Station pull request #1229
Opened 2024-12-20 21:41 UTC by Piras314

## About the PR

This PR introduces a 25% chance of an ERT (one commander, one engineer, one security, one medical, one janitor) spawning when 50% or more of the crew are dead during nukeops. They are all automatically raffled ghost roles, and the shuttle is preloaded.

If an ERT has been dispatched and the nuke is armed, it will play a custom nuke song just for this scenario, "Rescue Imminent" by mrjajkes.

[https://www.youtube.com/watch?v=DjV0OMskwiE](https://www.youtube.com/watch?v=DjV0OMskwiE)

## Why / Balance

## Technical details

## Media

I took a video of it working but honestly I'm too lazy to chop it up and blablabla. The shuttle loads with no lag, the ghost roles work, you can ftl to the station, the nuke song plays, etc. "Trust me bro".

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl: Piras314, mrjajkes
- add: Added a 25% chance for an ERT to spawn during nukeops if 50% or more of the crew is dead. If the nuke is armed when an ERT is spawned in, a *special* nuke song will play!

2024-12-20 21:43 UTC, jorgun commented
is this somthing we can add for when blob goes get to 50% aswell?

2024-12-20 21:46 UTC, Piras314 commented
> is this somthing we can add for when blob goes get to 50% /delta stage aswell?

Yeah just copy over the changes from NukeopsRuleSystem. A deathsquad might be more fitting for that though maybe? Not super familiar with blob.

2024-12-20 21:48 UTC, Piras314 commented on Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
> +        // Goobstation end
ok your first thing is bullshit your second one is ok

2024-12-20 21:57 UTC, Piras314 commented
I think I should reduce the percentage of crew that need to be dead to roll ERT to 35% or something lower like that.

2024-12-20 22:05 UTC, Piras314 commented
We can mess with the numbers and stuff later, this is just to start. The ERT is pretty weak anyway. Only 2 armed people and 1 medic plus like a janitor and an engi lol.

2024-12-20 22:21 UTC, starch70 approved these changes
Didnt read a single line

2024-12-20 22:30 UTC, Vlax2nd requested changes

2024-12-20 22:30 UTC, Vlax2nd commented on Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
>              return; // There are living operatives than can access the shuttle, or are still on the station's map.
minor spelling mistake, its over vro

2024-12-20 22:32 UTC, Piras314 commented on Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
>              return; // There are living operatives than can access the shuttle, or are still on the station's map.
out of scope :trollface:

2024-12-20 22:47 UTC, AgentePanela commented
The centcom dispatch a announcement when send ert?

2024-12-20 22:47 UTC, gluesniffler submitted a review, later dismissed

2024-12-20 22:48 UTC, gluesniffler commented
minor copypaste ops aside, my computer is imploding rn so i cant cherrypick this thing and run it, but whats the worst that could happen :clueless:

2024-12-20 22:55 UTC, Aviu00 requested changes

2024-12-20 22:55 UTC, Aviu00 commented on Content.Server/GameTicking/Rules/Components/NukeopsRuleComponent.cs
> +    public bool ERTCalled = false;
These shouldn't be DataFields. There should be a datafield `CallERT` and it should be set to false for lone ops (ert shouldn't be called during lone ops spawn).

2024-12-20 22:55 UTC, Aviu00 commented on Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
> +        // Goobstation start
1. Don't place this logic in `CheckRoundShouldEnd`. Instead, subscribe to `MobStateChangedEvent` and write this logic there. Because `CheckRoundShouldEnd` is checked when a nukie dies.
2. Make a separate system for this logic, this way it can be used for other gamemodes. Yes, there's a check for `NukeOperativeComponent` down below, you'll need to pass a `Func<EntityUid, bool>` to the method of a separate system to check for `NukeOperativeComponent`.
3. This needs a check if the round has ended or all nukies are dead or a nuke has exploded or ERTRolled = true.

2024-12-20 22:55 UTC, Aviu00 commented on Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
> +                    continue;
1. Don't count nukies towards `allPlayers`.
2. Use `MindSystem.IsDeadIc` instead of `IsAlive`. This way you can remove station grid check because it won't count people in ghost bar and also zombies or something like that.

2024-12-20 22:55 UTC, Aviu00 commented on Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
> +            if (aliveCrew.Count > 0 && allPlayers.Count > 0 && aliveCrew.Count / allPlayers.Count <= 0.5f)
0,5 should be a DataField.

2024-12-20 22:55 UTC, Aviu00 commented on Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
> +                if (!_random.Prob(0.25f))
0.25 should be a datafield, also remove '!'.

2024-12-20 22:55 UTC, Aviu00 commented on Content.Server/Nuke/NukeSystem.cs
> +                    _selectedNukeSong = _audio.GetSound(component.ERTArmMusic);
```suggestion
                    _selectedNukeSong = _audio.GetSound(component.ERTArmMusic);
                    break;
```

2024-12-20 22:55 UTC, Aviu00 commented on Content.Server/Nuke/NukeSystem.cs
> +            return;
Don't return, there's more logic down below.

2024-12-21 00:02 UTC, Piras314 commented on Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
> +        // Goobstation start
ERTRolled check already exists

2024-12-21 00:13 UTC, Piras314 commented on Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
> +                }
it exists, it's defined in YAML

2024-12-21 00:34 UTC, Piras314 commented on Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
> +    }
ERTDeadPercentage is a float, meaning it will always do float division.

2024-12-21 00:37 UTC, Aviu00 commented on Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
> +    }
Rabbit is right.

2024-12-21 01:03 UTC, Piras314 commented on Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
> +    }
sorry I misinterpreted an IDE thing

2024-12-21 01:03 UTC, Piras314 commented on Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
> +    }
this isn't even related to my code vro

2024-12-21 02:09 UTC, Piras314 commented
I'm honestly too lazy to refactor this right now and would rather do it in a later PR where we want to use the functionality for blob or whatever.

2024-12-21 11:25 UTC, Aviu00 requested changes

2024-12-21 11:25 UTC, Aviu00 commented on Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
> +        if (!_thisComp.ERTRolled)
Actuallly, `ERTRolled` and `ERTCalled` can be made `NukeopsRuleSystem` fields, because we probably want to share them between all NukeOpsRules and don't roll ERT for each of them. Just don't forget to set them to false on system shutdown and on round restart.

2024-12-21 11:25 UTC, Aviu00 commented on Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
> +        if (_thisComp == null || _gameTicker.RunLevel == GameRunLevel.PostRound || !_operativesAlive)
Remove `_thisComp` and `_operativesAlive`, replace it with `GetAliveOperatives` method call for each `NukeOpsRule` (check if nukies are alive for any nukeops rule where CallERT = true)

2024-12-21 14:57 UTC, Aviu00 commented
Also there should be an announcement if ERT is called and maybe gamma code as well.

2024-12-21 19:15 UTC, Piras314 commented on Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
> +        if (_operativesAlive)
`// This is code duplication but it's literally faster this way since all the vars for checking ops are needed outside of that function.`

2024-12-21 20:16 UTC, Aviu00 commented on Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
> +        if (_operativesAlive)
So true.

2025-01-05 01:38 UTC, Aidenkrz commented
i think this sucks, make a admin review before re-opening this

2025-01-06 02:02 UTC, Piras314 commented
why dont you make an admin review before closing it instead, like every other pr gets?

2025-01-06 15:40 UTC, Piras314 commented
![image](https://github.com/user-attachments/assets/6a0d7236-9daa-40db-b6a9-189c3ba2b5f6)
![image](https://github.com/user-attachments/assets/9c979c75-92c2-4198-8635-9d6037faa7e2)
![image](https://github.com/user-attachments/assets/48006f46-8882-4ff4-8431-21970320b45d)
![image](https://github.com/user-attachments/assets/9622f975-b885-4d19-98ae-e8afa4e299eb)
![image](https://github.com/user-attachments/assets/2b22aafc-2721-4df8-be09-d96a95a9c6d5)
![image](https://github.com/user-attachments/assets/1cf6b5f2-7f42-456a-b60e-03291300c07f)
![image](https://github.com/user-attachments/assets/093f656a-f0e5-412e-89f6-7a04d907f938)
![image](https://github.com/user-attachments/assets/adfff652-0e3d-4527-a193-7e0ff477a6d5)
![image](https://github.com/user-attachments/assets/c21f35ba-2648-4862-a2f3-37ceb4d78036)
![image](https://github.com/user-attachments/assets/9cdaebec-fa85-411a-9283-02d455197a8f)
![image](https://github.com/user-attachments/assets/1d50ebeb-2c11-419c-8ef6-bd0d400ae02a)
![image](https://github.com/user-attachments/assets/651a00a8-f60b-403d-a6dd-97b0d80b081e)
![image](https://github.com/user-attachments/assets/d9437994-54ce-40dc-b916-56e8c362d7f0)
![image](https://github.com/user-attachments/assets/a8e3be0c-a27e-4802-b268-1380d229a8fd)

2025-01-06 15:41 UTC, GitHubUser53123 commented
![speciest fuck](https://github.com/user-attachments/assets/b728eb26-228f-40a4-9460-8baeeeac9a4c)

2025-01-09 17:48 UTC, Piras314 commented
Can you believe it guys? Auto ERT, just a week away! I am so happy about this information. It got here so fast!

2025-01-15 16:51 UTC, Piras314 commented on Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
> +        if (!_thisComp.ERTRolled)
I'd say it's fine or better this way.

2025-01-15 17:54 UTC, Piras314 commented
in future I will check for how long the round has been going on as well before rolling for ert so it only even considers rolling if its been say, 50 minutes

2025-01-31 17:25 UTC, closed without merging