Load o' Fixes for IPCs and Mechs
Goob-Station/Goob-Station pull request #1235
Opened 2024-12-21 22:59 UTC by gluesniffler

I am now become maintainer, absent father to content I port.

## About the PR
Fixed a bunch of bugs with IPCs and Mechs, along with some buffs here and there.

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.
- [X] My soul has been left behind in the wagie cagie

**Changelog**
:cl: Mocho, Deltanedas
- add: Added a CVAR that lets server operators decide if players should be able to use mech guns without them being inside of a mech. Set to true by default.
- tweak: Reworked IPC fire mechanics to not round remove them from a tiny fire.
- tweak: IPCs cannot be picked as impersonation objectives for Changelings
- tweak: IPCs cannot be cloned now.
- tweak: Entity hands get blocked when they are inside of a mech now.
- tweak: Mech punches or mech drills cannot be wideswung. 
- tweak: The mech PKA now consumes basically no energy.
- fix: IPCs are finally not 3x more flammable than a plasmaman.
- fix: Fixed scram implants breaking your character if you use them inside of a mech.
- fix: Fixed EMPs completely bricking mech weapons.

2024-12-21 23:06 UTC, gluesniffler commented on Resources/Prototypes/_Goobstation/Entities/Objects/Specific/Mech/Weapons/Gun/industrial.yml
> +    fireCost: 0.1
SILENCE YE HEATHEN

2024-12-21 23:29 UTC, Aviu00 requested changes

2024-12-21 23:29 UTC, Aviu00 commented on Content.Server/Objectives/Systems/KillPersonConditionSystem.cs
> +        if (comp.NeedsOrganic && HasComp<SiliconComponent>(uid))
`uid` is objective entity, not a person.

2024-12-21 23:29 UTC, Aviu00 commented on Content.Server/_Goobstation/Temperature/KillOnOverheatSystem.cs
> +            _mob.ChangeMobState(uid, MobState.Dead, mob);
This can kill godmode entities.

2024-12-21 23:29 UTC, Aviu00 commented on Content.Shared/Mech/EntitySystems/SharedMechSystem.cs
> +            if (!_config.GetCVar(GoobCVars.MechGunOutsideMech))
Getting cvars from config each time shot is attempted is slow. Use `Subs.CVar`. Also `mech` component isn't used so you can replace `TryComp` with `HasComp`.

2024-12-21 23:29 UTC, Aviu00 commented on Content.Shared/_Goobstation/CCVars/CCVars.Goob.cs
> +        CVarDef.Create("mech.gun_outside_mech", true, CVar.REPLICATED);
```suggestion
        CVarDef.Create("mech.gun_outside_mech", true, Cvar.SERVER | CVar.REPLICATED);
```
Client can shouldn't be able to change this cvar.

2024-12-21 23:36 UTC, gluesniffler commented on Content.Server/_Goobstation/Temperature/KillOnOverheatSystem.cs
> +            _mob.ChangeMobState(uid, MobState.Dead, mob);
Even gods must fall :trollface:

2024-12-22 00:37 UTC, Aviu00 approved these changes

2024-12-23 14:19 UTC, Piras314 approved these changes

2024-12-23 14:19 UTC, merged