Evasion and wheelchair bound fix
Goob-Station/Goob-Station pull request #1239
Opened 2024-12-22 17:39 UTC by Aviu00

## About the PR

Fixed evasion mispredicts.
Fixed wheelchair bound people baing able to walk.
Now you can't stand up if any of your legs are broken, also legs and arms can't evade now. I want this for armblade and esword delimbing combat.

## Why / Balance

## Technical details

Random isn't predicted.

## Media

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl: Aviu
- fix: Wheelchair bound people can no longer stand up.
- tweak: Only head can evade now.
- tweak: People with at least 1 broken leg can't stand up.
- fix: Fix evasion popups appearing when they shouldn't.
- fix: Mobs always target torso now, so the person being hit by them can't evade.

2024-12-22 19:11 UTC, gluesniffler requested changes
Okay so the way you were handling evasion is a bit flawed, because even if we do prevent that stuff from happening, you still get mispredicts both visually and in the medhud, since DamageableSystem is predicted, and thus the client runs without an evasion happening.

I'll send you on discord my tweaked SharedBodySystem.Targeting so you can just paste it in this PR. Biggest change is just going to be to start using  `var rand = new System.Random((int) _timing.CurTick.Value);` like how ClumsySystem does it, which guarantees we'll get the same randomness on both client and server side.

2024-12-22 19:11 UTC, gluesniffler commented on Content.Shared/Mobs/Systems/MobStateSystem.Subscribers.cs
> +                    break;
Kill this, evasion is now predicted.

2024-12-22 19:11 UTC, gluesniffler commented on Content.Shared/Body/Systems/SharedBodySystem.Parts.cs
> +
```suggestion

2024-12-22 19:11 UTC, gluesniffler commented on Content.Shared/Mobs/Systems/MobStateSystem.Subscribers.cs
> +                    break;
```suggestion

2024-12-22 19:11 UTC, gluesniffler commented on Content.Shared/Mobs/Systems/MobStateSystem.Subscribers.cs
> +                    break;
```suggestion

2024-12-22 19:11 UTC, gluesniffler commented on Content.Shared/Mobs/Systems/MobStateSystem.cs
> +using Robust.Shared.Network;
```suggestion

2024-12-22 19:11 UTC, gluesniffler commented on Content.Shared/Mobs/Systems/MobStateSystem.cs
> +    [Dependency] private readonly INetManager _net = default!; // Shitmed
```suggestion

2024-12-22 19:54 UTC, gluesniffler commented on Content.Shared/_Shitmed/Body/Systems/SharedBodySystem.Targeting.cs
> +                    targetPart = args.CanEvade ? TargetBodyPart.Torso : GetRandomBodyPart(ent, targetEnt);
```suggestion
                    targetPart = GetRandomBodyPart(ent, targetEnt);

2024-12-22 19:54 UTC, gluesniffler commented on Content.Shared/_Shitmed/Body/Systems/SharedBodySystem.Targeting.cs
> +                    targetPart = args.CanEvade ? TargetBodyPart.Torso : GetRandomBodyPart(ent, targetEnt);
No reason not to include it now since the prediction issue was solved.

2024-12-22 20:08 UTC, Aviu00 commented on Content.Shared/_Shitmed/Body/Systems/SharedBodySystem.Targeting.cs
> +                    targetPart = args.CanEvade ? TargetBodyPart.Torso : GetRandomBodyPart(ent, targetEnt);
This would cause mobs to try to hit head and fail.

2024-12-22 21:27 UTC, gluesniffler commented on Content.Shared/_Shitmed/Body/Systems/SharedBodySystem.Targeting.cs
> +                    targetPart = args.CanEvade ? TargetBodyPart.Torso : GetRandomBodyPart(ent, targetEnt);
only 70% of the time, 1/6th of the time
![gambling-loop](https://github.com/user-attachments/assets/075c4128-1b4c-43e4-b598-cedca9d5c680)

2024-12-22 21:30 UTC, Aviu00 commented on Content.Shared/_Shitmed/Body/Systems/SharedBodySystem.Targeting.cs
> +                    targetPart = args.CanEvade ? TargetBodyPart.Torso : GetRandomBodyPart(ent, targetEnt);
Yes, still annoying when you play as non-humanoid creature.

2024-12-22 22:36 UTC, gluesniffler commented on Content.Shared/_Shitmed/Body/Systems/SharedBodySystem.Targeting.cs
> +                    targetPart = args.CanEvade ? TargetBodyPart.Torso : GetRandomBodyPart(ent, targetEnt);
weak. do as you please then

2024-12-23 03:45 UTC, JoeHammad1844 commented
hands and feet should be able to evade
wont change much but having just the head evade feels weird

2024-12-23 14:27 UTC, Piras314 approved these changes

2024-12-23 14:27 UTC, merged