Modsuits
Goob-Station/Goob-Station pull request #1242
Opened 2024-12-23 00:59 UTC by BombasterDS2

## About the PR
Adds craftable modsuit (just standard modsuits in this PR) that can be sealed, requires power and uses backpack slot.
Modules not implemented yet, but they'll be ready soon. Other types of modsuits will be added with modules.

I'll try to finish modules logic and add first modules in next two weeks (it'll be faster after i finish modules system)

Modsuit parts can be researched in experimental branch as T1 technology. Modsuit Cores can be found in cargo catalog. Modsuit control have flashlight and storage (it'll be replaced with modules) 

## Technical details
- Fully changes ToggleableClothingSystem to work with multiple toggleable clothings. 
- Changes some systems that should work with ComponentToggler.
- Slightly improves ConfirmableAction allowing it to use iconOn as confirm icon
- Improves ChargerSystem allowing it to raise relayed FindPowerCellEvent

## Media
Modsuit crafting:
https://github.com/user-attachments/assets/8ff03d3a-0fc1-4818-b710-bfc43f0e2a68

Modsuit sealing:
https://github.com/user-attachments/assets/6671459a-7767-499b-8678-062fc1db7134

:cl:
- add: Modsuits can be reseached as T1 experimental technology. Modules not implemented yet.

2024-12-23 01:54 UTC, BombasterDS2 commented on Content.Shared/Clothing/EntitySystems/ClothingSystem.cs
> +    }
I'm not sure if Hashset here can really be null

2024-12-23 01:55 UTC, BombasterDS2 commented on Content.Client/_Goobstation/Clothing/EntitySystems/PoweredSealableClothingSystem.cs
> +}
It's just needed for client to work. Shared logic work both on client and server.

2024-12-23 02:00 UTC, BombasterDS2 commented on Content.Shared/Clothing/Components/ToggleableClothingComponent.cs
> +    public Container? Container;
This component have Access(typeof(ToggleableClothingSystem)) that means it'll be accesed only by this system

2024-12-23 02:01 UTC, BombasterDS2 commented on Content.Shared/Clothing/Components/ToggleableClothingComponent.cs
> +}
Clothing can be attached or not attached. If it's partially attached, it'll unattach everything first.

2024-12-23 02:07 UTC, BombasterDS2 commented on Content.Server/Atmos/Components/BreathToolComponent.cs
I don't need DataField there and added it by mistake. Sorry about that.

2024-12-23 02:09 UTC, BombasterDS2 commented on Resources/Prototypes/_Goobstation/Recipes/Lathes/categories.yml
> +  name: lathe-category-modsuit
I added this localization. I guess you missed it.

2024-12-23 02:11 UTC, BombasterDS2 commented on Resources/Prototypes/_Goobstation/Recipes/Lathes/robotics.yml
> +
It's fine like this, don't worry about it.

2024-12-23 02:12 UTC, BombasterDS2 commented on Content.Client/_Goobstation/Clothing/Components/SealableClothingVisualsComponent.cs
> +}
Data field property VisualLayers in data definition SealableClothingVisualsComponent does not have a setter

2024-12-23 02:13 UTC, BombasterDS2 commented on Resources/Prototypes/_Goobstation/Entities/Clothing/Shoes/modsuit.yml
> +    sprintModifier: 0.9
0.9 is basic movement speed for space suits

2024-12-23 02:15 UTC, BombasterDS2 commented on Content.Shared/_Goobstation/Clothing/Components/SealableClothingRequiresPowerComponent.cs
> +    public float MovementSpeedPenalty = 0.3f;
Game don't have ValidateRange tag. Also i don't need "required" in dataField.

2024-12-23 02:15 UTC, BombasterDS2 commented on Content.Shared/_Goobstation/Clothing/Components/SealableClothingComponent.cs
> +    public TimeSpan SealingTime = TimeSpan.FromSeconds(1.75);
Game don't have ValidateRange tag.

2024-12-23 02:17 UTC, BombasterDS2 commented on Resources/Prototypes/_Goobstation/Entities/Clothing/Hands/modsuit.yml
> +    sealDownPopup: sealable-clothing-seal-down-gauntlets
PowerConsumer used for structures that connected to station cables. My item is battery-powered.

2024-12-23 02:19 UTC, BombasterDS2 commented on Resources/Prototypes/_Goobstation/Entities/Clothing/OuterClothing/modsuit.yml
> +      coefficient: 0.01
Item is battery-powered.

2024-12-23 02:37 UTC, BombasterDS2 commented on Content.Shared/Actions/ConfirmableActionComponent.cs
>      public LocId Popup = string.Empty;
I don't need it required

2024-12-23 02:40 UTC, BombasterDS2 commented on Resources/Prototypes/_Goobstation/Entities/Clothing/Shoes/modsuit.yml
> +        shader: unshaded
It used for SealableClothingControl

2024-12-23 02:41 UTC, BombasterDS2 commented on Content.Shared/_Goobstation/Clothing/Components/SealableClothingRequiresPowerComponent.cs
> +    public float MovementSpeedPenalty = 0.3f;
It needs to be that low

2024-12-23 03:44 UTC, JoeHammad1844 commented
pretty sure these are roundstart in ss13

2024-12-23 13:41 UTC, JustSome1Nearby commented
Can you put AI in this suit version?

2024-12-23 17:12 UTC, BombasterDS2 commented
> Can you put AI in this suit version?

Nope. It'll be implemented in future.

2024-12-23 21:19 UTC, GroggleG commented
Remember Goobers, this is an addition you cannot walk out of :feelsgood:

2024-12-24 17:51 UTC, BombasterDS2 commented
> Are security, medical, syndicate ect modsuits included? Or do they still use hardsuits

Just standard modsuit in this PR. Department/Syndicate modsuits will be added with modules.

2024-12-28 16:22 UTC, Piras314 requested changes
Nitpicks only in file review, the C# code itself all looks good to me, and testing it ingame went smoothly. I have no idea why that doafter code doesn't work either, but I'll request a review from Aviu and maybe they'll know.

For some reason this PR causes hardsuits without internal storage to have "storage" (it has the little storage icon on the side and you can right click open storage) that's completely empty and doesn't actually open any storage because, well, it doesn't have storage capacity. I've tested that this isn't the case on master.

2024-12-28 16:22 UTC, Piras314 commented on Resources/Locale/en-US/_Goobstation/clothing/sealable-clothing-component.ftl
> +sealable-clothing-seal-up-boots = The {$partName} boots seal around your feet.
The ${partName} seal around your feet. (the partname for modboots have boots at the end already so with the current one it would say "Boots boots seal around your feet" as can be seen in the video you attatched to the PR)

2024-12-28 16:22 UTC, Piras314 commented on Resources/Locale/en-US/_Goobstation/clothing/sealable-clothing-component.ftl
> +sealable-clothing-seal-down = The {$partName} unsealing
The {$partName} is unsealing

2024-12-28 16:22 UTC, Piras314 commented on Resources/Locale/en-US/_Goobstation/clothing/sealable-clothing-component.ftl
> +sealable-clothing-open-sealed-panel-fail = Wires panel tightly sealed!
The wires panel is too tightly sealed!

2024-12-28 16:23 UTC, Piras314 commented
(Also check YAML Linter fail)

2024-12-29 15:27 UTC, Aviu00 requested changes

2024-12-29 15:27 UTC, Aviu00 commented on Content.Shared/Clothing/Components/ToggleableClothingComponent.cs
> +    // Goobstation - Modsuits changes this system entirely
Maybe it is better to not modify this and make similar system for multiple toggleable clothing parts so this would become hell after upstream modifies this or adds new protos with `ToggleableClothingComponent`?

2024-12-29 15:27 UTC, Aviu00 commented on Content.Shared/Clothing/Components/ToggleableClothingComponent.cs
> +    public bool ReplaceCurrentClothing = false;
Make this `true` by default, nice QoL feature.

2024-12-29 15:37 UTC, BombasterDS2 commented on Content.Shared/Clothing/Components/ToggleableClothingComponent.cs
> +    // Goobstation - Modsuits changes this system entirely
I don't want to make new system that makes the same, but for multiple objects. I can make system compatible with old prototypes.

2024-12-29 15:40 UTC, BombasterDS2 commented on Content.Shared/Clothing/EntitySystems/ToggleableClothingSystem.cs
> +        return true;
I don't like this. It makes code less understandable.

2024-12-29 15:42 UTC, BombasterDS2 commented on Content.Shared/Clothing/Components/ToggleableClothingComponent.cs
> +    public bool ReplaceCurrentClothing = false;
This feature is modsuits only. I don't like idea that emergency EVA can replace your helmet and etc. (anyway, it can be changed in the feature)

2024-12-31 11:11 UTC, Aviu00 approved these changes

2025-01-03 15:54 UTC, Piras314 requested changes
2 tiny .ftl nitpicks, but the issue of faux storage on hardsuits without storage still remains:
![image](https://github.com/user-attachments/assets/cfc14834-88c1-449a-a58a-cac74b038479)

2025-01-03 15:54 UTC, Piras314 commented on Resources/Locale/en-US/_Goobstation/clothing/sealable-clothing-component.ftl
> +sealable-clothing-seal-up-helmet =  The {$partName} hisses as it closed
hisses as it close**s**

2025-01-03 15:54 UTC, Piras314 commented on Resources/Locale/en-US/_Goobstation/clothing/sealable-clothing-component.ftl
> +sealable-clothing-seal-down-gauntlets = The {$partName} become loose around your finger
finger**s**

2025-01-05 01:41 UTC, merged