Heretic blade path fixes
Goob-Station/Goob-Station pull request #1250
Opened 2024-12-23 20:16 UTC by yglop

## About the PR
Small fixes. Read cl.

## Requirements
[x] Tested.

**Changelog**
:cl:
- fix: Heretic who chose path of blade will not be able to shoot.
- fix: Heretic blade path Realignment spell will apply pacified effect on the user.

2024-12-24 08:16 UTC, JustSome1Nearby commented
Isnt "not being able to shoot " a feature? Cause you are a mele heretic? Why tf you need guns when blades goes slash slash

2024-12-24 09:44 UTC, a-person5660 commented
> Isnt "not being able to shoot " a feature? Cause you are a mele heretic? Why tf you need guns when blades goes slash slash

currently it doesnt enforce melee only

2024-12-24 09:50 UTC, Aviu00 commented
Why would blade heretics not be able to shoot? This path surely needs nerfs, but not this. Grasp effect should be nerfed, infusing blades should be nerfed, maybe something else as well idk. Ngl grasp stuns like for 1 or 1.5 seconds in ss13 when applied from behind or to prone targets. Infusing blades instead of x2 damage could give something like x3 left click attack part damage so it delimbs easier.

2024-12-24 09:52 UTC, whateverusername0 commented on Resources/Locale/en-US/_Goobstation/Heretic/abilities/heretic.ftl
> +heretic-cant-shoot = Gods wont let me fire { THE($entity) }!
waht about "I cannot use that" instead? sounds shitty imo

2024-12-24 09:52 UTC, whateverusername0 approved these changes

2024-12-24 09:54 UTC, whateverusername0 commented
> Why would blade heretics not be able to shoot?

path quirk

> Grasp effect should be nerfed
> when applied from behind or to prone targets

it already does that

> Infusing blades instead of x2 damage could give something like x3 left click attack part damage so it delimbs easier.

you like delimb combat don't you? you're a delimber 😺

2024-12-24 10:39 UTC, yglop commented on Resources/Locale/en-US/_Goobstation/Heretic/abilities/heretic.ftl
> +heretic-cant-shoot = Gods wont let me fire { THE($entity) }!
done

2024-12-24 11:42 UTC, Aviu00 commented
> it already does that

It stamcrits for whatever reason, but should stun for 1.5 seconds.

2024-12-24 12:20 UTC, whateverusername0 commented
> It stamcrits for whatever reason, but should stun for 1.5 seconds.

normal mansus grasp deals 80 stamina damage, blade grasp is an upgraded version that instead of giving a special effect just doubles the amount of stamina damage dealt when the conditions are met

2024-12-24 12:30 UTC, JustSome1Nearby commented
Should've just used Clown's cant-shoot component instead of making one more 🧐

2024-12-24 12:54 UTC, Aviu00 commented
> normal mansus grasp deals 80 stamina damage, blade grasp is an upgraded version that instead of giving a special effect just doubles the amount of stamina damage dealt when the conditions are met

It's op, should be like in ss13.

2024-12-26 12:42 UTC, TurboTrackerss14 commented
The double-negative of "CanNotShootGuns = false" hurts me so much.

2024-12-28 15:31 UTC, Piras314 requested changes
You should make it clear when selecting the blade path that it will make the player unable to use guns via the description of it.

See below for review of the actual code.

2024-12-28 15:31 UTC, Piras314 commented on Content.Shared/_Goobstation/Heretic/Components/HereticComponent.cs
> +    [ViewVariables(VVAccess.ReadWrite)] public bool CanNotShootGuns = false;
Change this to `CanShootGuns` and flip over the bools please.

2024-12-28 15:31 UTC, Piras314 commented on Resources/Locale/en-US/_Goobstation/Heretic/abilities/heretic.ftl
> +heretic-cant-shoot = I cannot use { THE($entity) }!
Why can't you use the entity? Explain to the player.

2024-12-28 15:31 UTC, Piras314 commented on Content.Server/_Goobstation/Heretic/Abilities/HereticAbilitySystem.Blade.cs
> +    }
put a newline between these two functions

2024-12-28 17:01 UTC, yglop commented on Resources/Locale/en-US/_Goobstation/Heretic/abilities/heretic.ftl
> +heretic-cant-shoot = I cannot use { THE($entity) }!
It was explained before John's suggestion.

2024-12-28 17:03 UTC, yglop commented on Content.Server/_Goobstation/Heretic/Abilities/HereticAbilitySystem.Blade.cs
> +    }
done

2024-12-28 17:03 UTC, yglop commented on Content.Shared/_Goobstation/Heretic/Components/HereticComponent.cs
> +    [ViewVariables(VVAccess.ReadWrite)] public bool CanNotShootGuns = false;
done

2024-12-28 17:07 UTC, yglop commented on Resources/Locale/en-US/_Goobstation/Heretic/abilities/heretic.ftl
> +heretic-cant-shoot = I cannot use { THE($entity) }!
In what better way i can explain to player that Gods don't like guns?

2024-12-29 18:42 UTC, Piras314 commented on Resources/Locale/en-US/_Goobstation/Heretic/abilities/heretic.ftl
> +heretic-cant-shoot = I cannot use { THE($entity) }!
You can't use { THE($entity) }! You can't use guns because of your sacred pledge to the path of the blade.

2024-12-30 02:16 UTC, whateverusername0 commented
i'm pretty sure ninja can't shoot so you can take his system (if you haven't done that already idk)

2024-12-30 18:51 UTC, yglop commented on Resources/Locale/en-US/_Goobstation/Heretic/abilities/heretic.ftl
> +heretic-cant-shoot = I cannot use { THE($entity) }!
done

2025-01-05 01:42 UTC, merged