Pirates (Space IRS)
Goob-Station/Goob-Station pull request #1254
Opened 2024-12-24 12:13 UTC by whateverusername0

## About the PR

gracing goobstation with more shitcode
very big draft, indicates that i'm slowly but surely working on it
will update the description as i figure stuff out

2024-12-24 12:28 UTC, JustSome1Nearby commented
Why did you name it Space IRS

2024-12-24 13:13 UTC, jorgun commented
> Why did you name it Space IRS

Ss13 pirates have different possible Crew option: skeleton Crew, gray tide, plain pirates , and irs

2024-12-24 16:49 UTC, whateverusername0 commented
> Why did you name it Space IRS

@JustSome1Nearby 
![image](https://github.com/user-attachments/assets/6523ce98-9983-4ea5-acc5-db54bce18cdb)

2024-12-24 18:03 UTC, JustSome1Nearby commented
Wait.. weak in space? 
Shouldnt this antag be the reason to actualy USE ship combat, ship guns? 
It isnt used ANYWHERE else (the only use of ship canons rn is to bomb the station itself... But Why?)

Imagine their ship BEING THE PLACE TO STORE THA BOOTY, being atacked by cargo shuttle with Friendship canons, 
a violent, EPIC spacecraft battle starts, people fly out of the ship due to busted walls, you constantly need repair the power and atmos, being CREATIVE about it, some pirates proceed to hop onto oponent's vessel and a bloody fight on the cutlasses initiates

2024-12-24 20:13 UTC, Aineias1 commented
@whateverusername0 https://github.com/Goob-Station/Goob-Station/issues/731

2024-12-24 20:14 UTC, Aineias1 commented
Yeah also if you need a shuttle, ping me in discord

2024-12-24 21:50 UTC, JoeHammad1844 commented
will these be a midround antag like ss13?

2024-12-26 06:49 UTC, whateverusername0 commented
> will these be a midround antag like ss13?

yes

2025-01-16 09:58 UTC, whateverusername0 commented on Content.Server/_Goobstation/_Pirates/Pirates/RansomSystem.cs
> +    }
they really won't

2025-01-16 09:58 UTC, whateverusername0 commented on Content.Server/_Goobstation/_Pirates/Pirates/Siphon/ResourceSiphonComponent.cs
> +    [ViewVariables(VVAccess.ReadWrite)] public float Credits = 0f;
it's not how it works

2025-01-16 09:59 UTC, whateverusername0 commented on Content.Server/_Goobstation/_Pirates/Pirates/Siphon/ResourceSiphonComponent.cs
> +    [DataField] public float DrainRate = 10f;
it already assigns names automatically

2025-01-16 09:59 UTC, whateverusername0 commented on Content.Server/_Goobstation/_Pirates/GameTicking/Rules/PendingPirateRuleSystem.cs
> +                price = _rand.Next((int) (bank.Balance * 0.75f), bank.Balance);
bank balance is never 0

2025-01-16 10:00 UTC, whateverusername0 commented on Content.Server/_Goobstation/_Pirates/GameTicking/Rules/ActivePirateRuleSystem.cs
> +            args.AddLine(Loc.GetString("nukeops-list-name-user", ("name", name), ("user", sessionData.UserName)));
?????????????????

2025-01-16 10:05 UTC, whateverusername0 commented
almost all checks passed first try? i must be getting good at this

2025-01-16 15:11 UTC, whateverusername0 commented on Content.Server/_Goobstation/_Pirates/Pirates/Siphon/ResourceSiphonSystem.cs
> +    }
logic runs on a single thread iirc

2025-01-17 06:25 UTC, JustSome1Nearby commented
Oh shit oh wait you are OPENING it
IS THE NEXT WEEK UPON US?!

2025-01-18 11:41 UTC, gluesniffler commented on Content.Server/Cargo/Systems/CargoSystem.Orders.cs
> +        public void DeductFunds(StationBankAccountComponent component, int amount)
Part of me feels making these functions public might not be a good idea, but since its running on the server idk.

2025-01-18 11:46 UTC, gluesniffler commented on Content.Server/_Goobstation/_Pirates/Pirates/Siphon/ResourceSiphonSystem.cs
> +        return true;
Havent tested it yet, but couldnt this code potentially lead to a case where the siphon is spawned with two sets of pirates on at the same time, and it activates on the one thats not yours?

2025-01-19 08:04 UTC, whateverusername0 commented on Content.Server/_Goobstation/_Pirates/Pirates/Siphon/ResourceSiphonSystem.cs
> +        return true;
it shouldn't really

2025-01-19 08:04 UTC, whateverusername0 commented on Content.Server/Cargo/Systems/CargoSystem.Orders.cs
> +        public void DeductFunds(StationBankAccountComponent component, int amount)
normalize publicizing server side code

2025-02-01 20:18 UTC, Aidenkrz commented on Content.Server/Research/Systems/ResearchSystem.Console.cs
> +        // goob edit end
bot is right here, you should add a popup

2025-02-11 12:07 UTC, whateverusername0 commented on Resources/Prototypes/Entities/Markers/Spawners/Conditional/pirates.yml
> +    name: ghost-role-information-pirate-irs-name # leaving it like that because i'm too lazy to redo it
🗣️

2025-02-11 12:50 UTC, gluesniffler commented on Content.Server/_Goobstation/_Pirates/Pirates/Siphon/ResourceSiphonSystem.cs
> +                siphon.ActivationPhase = 0; // reset
Why not use timespan here

2025-02-11 14:46 UTC, gluesniffler commented
Okay so feedback from my small test:

- We probably need a Pirate Captain role in the ship so they dont run around like headless chickens, and also because I want to see the Pirate Captain Hardsuit used :godo:
- Replace the `SuitStorageBasic` storages at the bottom of the ship with `SuitStorageEVAPirate`
- The siphon needs a maximum range. I can drive 2km away from the station and activate it as is, probably should force em to be within ATS distance of the station (I think thats about 200-400ish meters?)
- Pirates should be able to see the progress of their plundering, and get a clear cut indication of when they're done in case they want to fuck around or shitpost as salvage afterwards.

2025-02-20 15:16 UTC, gluesniffler commented
# YAML LINTER FAIL!!!!!!!!

2025-02-20 15:21 UTC, whateverusername0 commented
my sorry ass keeps forgetting there's no checks when it's drafted

2025-02-22 23:50 UTC, gluesniffler commented
Test fail is real.

2025-02-23 14:15 UTC, gluesniffler commented on Content.Server/_Goobstation/_Pirates/Pirates/Siphon/ResourceSiphonSystem.cs
> +            _chat.TrySendInGameICMessage(ent, loc, InGameICChatType.Speak, false);
Not working for some reason. I was spamming the siphon when trying to test distance from the station, and no messages would come out.

2025-02-23 14:16 UTC, gluesniffler commented on Content.Server/_Goobstation/_Pirates/Pirates/Siphon/ResourceSiphonSystem.cs
> +        _chat.TrySendInGameICMessage(ent, Loc.GetString("data-siphon-activated"), InGameICChatType.Speak, false);
Not working either.

2025-02-23 14:16 UTC, gluesniffler commented on Content.Server/_Goobstation/_Pirates/Pirates/Siphon/ResourceSiphonSystem.cs
> +        var anloc = Loc.GetString("data-siphon-activated-announcement", ("pos", $"X: {coords.X}; Y: {coords.Y}"));
Missing FTL string.

2025-02-23 14:18 UTC, gluesniffler commented on Resources/Maps/_Goobstation/Shuttles/pirates_irs.yml
You forgot to add a gyroscope on the ship too lol

2025-02-24 08:52 UTC, whateverusername0 commented on Content.Server/_Goobstation/_Pirates/Pirates/Siphon/ResourceSiphonSystem.cs
> +            _chat.TrySendInGameICMessage(ent, loc, InGameICChatType.Speak, false);
DAMN

2025-02-24 08:52 UTC, whateverusername0 commented on Content.Server/_Goobstation/_Pirates/Pirates/Siphon/ResourceSiphonSystem.cs
> +        var anloc = Loc.GetString("data-siphon-activated-announcement", ("pos", $"X: {coords.X}; Y: {coords.Y}"));
huh?

2025-02-24 08:52 UTC, whateverusername0 commented on Resources/Maps/_Goobstation/Shuttles/pirates_irs.yml
:goberserk:

2025-02-25 23:48 UTC, whateverusername0 commented
![image](https://github.com/user-attachments/assets/53828d2b-9344-433b-9a23-8841dfcfa61f)
map fail? couldn't be me

2025-02-26 03:25 UTC, Aidenkrz commented
this dude is actually a mapping noob, nobody tell him how to fix it

2025-02-26 03:36 UTC, whateverusername0 commented
the y🗣pper

2025-02-26 03:43 UTC, gluesniffler commented
> the y🗣pper

come on bro you got this

2025-02-26 09:46 UTC, whateverusername0 commented
![image](https://github.com/user-attachments/assets/fe9c441b-4f61-4bad-a6f6-aa378b7018f6)
pirates, when sir durk antagtoken merges it

2025-02-27 05:50 UTC, whateverusername0 commented
![image](https://github.com/user-attachments/assets/42e438c7-2ee5-43ee-bd94-9dc9160869af)
this person is clearly a mapping noob let's not tell anyone what the error is about

2025-02-27 07:47 UTC, gluesniffler commented
> ![image](https://private-user-images.githubusercontent.com/113782077/417449710-42e438c7-2ee5-43ee-bd94-9dc9160869af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDA2NDEyMDAsIm5iZiI6MTc0MDY0MDkwMCwicGF0aCI6Ii8xMTM3ODIwNzcvNDE3NDQ5NzEwLTQyZTQzOGM3LTJlZTUtNDNlZS1iZDk0LTlkYzkxNjA4NjlhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIyN1QwNzIxNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YjljZjBhODJhYTk3N2VlNDdjMDhmMDljYjM1ZWJkZTRhMTc1MWQwZTRmOTQ0ZmM1Y2MxOWExOTc3MWYxZWJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.uBOuEKZYJtvlPmk-Hn3t0TNJrBTxWUc1Kip3qa-7Ias) this person is clearly a mapping noob let's not tell anyone what the error is about

nah those test fails are lavaland related lmao

last few issues:

- pirate role doesnt open up again when they /ghost (see the recent abductor fix for it)
- gyroscope is turned off in the shuttle, most dumbasses dont even know you can toggle power on those
- you're creating an error by adding FactionPirate when you havent even defined it in YML, add it. (optionally also give it to the spirate mob which for whatever reason uses faction syndicate lmao) 
![image](https://github.com/user-attachments/assets/35559ce2-c210-4f79-89a5-ca4f0f358b8d)

for now ill approve it and leave someone else to merge once you get this done

2025-02-27 07:48 UTC, gluesniffler approved these changes

2025-03-01 01:30 UTC, whateverusername0 commented on Resources/Prototypes/_Goobstation/_Pirates/faction.yml
> +  - Wizard # goob edit - wizard
🥱

2025-03-06 03:16 UTC, gusxyz commented on Content.Server/Cargo/Systems/CargoSystem.Orders.cs
> +            var eqe = EntityQueryEnumerator<ResourceSiphonComponent>();
```suggestion
            var eqe = EntityQuery<ResourceSiphonComponent>();
```
If you dont need the entityUid just use EntityQuery()

2025-03-06 03:16 UTC, gusxyz commented on Content.Server/Cargo/Systems/CargoSystem.Orders.cs
> +            while (eqe.MoveNext(out var sip))
```suggestion
            foreach (var sip in eqe)
```
due to above suggested change

2025-03-06 03:16 UTC, gusxyz commented on Content.Server/Cargo/Systems/CargoSystem.Orders.cs
> +                if (sip.Active)
invert this

2025-03-06 03:16 UTC, gusxyz commented on Content.Server/Research/Systems/ResearchSystem.Console.cs
> +        while (eqe.MoveNext(out var siphon))
im not gonna copy paste the same suggestion from above guh

2025-03-06 03:16 UTC, gusxyz commented on Content.Server/_Goobstation/_Pirates/Pirates/Siphon/ResourceSiphonSystem.cs
> +        if (HasComp<CashComponent>(args.Used))
```sugestion
        if (HasComp<CashComponent>(args.Used))
          return;
```

2025-03-06 03:16 UTC, gusxyz commented on Content.Server/_Goobstation/_Pirates/Pirates/Siphon/ResourceSiphonSystem.cs
> +        {
```suggestion
```

2025-03-06 03:16 UTC, gusxyz commented on Content.Server/_Goobstation/_Pirates/Pirates/Siphon/ResourceSiphonSystem.cs
> +        }
```suggestion
```

2025-03-06 04:34 UTC, whateverusername0 commented on Content.Server/Cargo/Systems/CargoSystem.Orders.cs
> +            var eqe = EntityQueryEnumerator<ResourceSiphonComponent>();
i need

2025-03-06 04:35 UTC, whateverusername0 commented on Content.Server/Cargo/Systems/CargoSystem.Orders.cs
> +                if (sip.Active)
bro

2025-03-06 04:36 UTC, whateverusername0 commented on Content.Server/_Goobstation/_Pirates/Pirates/Siphon/ResourceSiphonSystem.cs
> +        if (HasComp<CashComponent>(args.Used))
bro

2025-03-06 04:37 UTC, whateverusername0 commented
how do i dismiss that shit on mobile

2025-03-06 12:01 UTC, SX-7 requested changes
Checkfail is related and real, save grid as map or edit its file (L24-35). 
Besides that all is good, and looks mergable.

2025-03-06 12:04 UTC, whateverusername0 commented
ight thanks

2025-03-06 12:09 UTC, Aviu00 requested changes

2025-03-06 12:09 UTC, Aviu00 commented on Content.Server/_Goobstation/_Pirates/Pirates/Siphon/ResourceSiphonSystem.cs
> +                objective.Plundered = siphon.Comp.Credits;
Pirates field in gamerule should store list of minds instead of entities. You are getting entity mind in UpdateObjective anyway.
Because if some pirate gets polymorphed or mindswapped or something - it would break.

2025-03-06 12:09 UTC, Aviu00 commented on Content.Server/_Goobstation/_Pirates/Pirates/Siphon/ResourceSiphonSystem.cs
> +        bank = ((EntityUid) stationent!, (StationBankAccountComponent) bankaccount!);
What with these casting and exclamation marks? Use .Value

2025-03-06 12:09 UTC, Aviu00 commented on Resources/Prototypes/_Goobstation/_Pirates/faction.yml
> +  - Wizard # goob edit - wizard
You forgot to make all these factions hostile to pirates. Pirates are hostile to them but they are not hostile to pirates.

2025-03-07 09:21 UTC, whateverusername0 commented on Content.Server/Cargo/Systems/CargoSystem.Orders.cs
> +            bal = forced ? Math.Max(0, bal) : bal;
huh?

2025-03-07 09:31 UTC, whateverusername0 commented on Content.Server/_Goobstation/_Pirates/GameTicking/Rules/ActivePirateRuleSystem.cs
> +        _role.MindAddRole(mindId, _MindRole.Id, mind, true);
that yamlshit man

2025-03-07 12:41 UTC, Aviu00 approved these changes

2025-03-07 13:44 UTC, merged