I think thats all
Goob-Station/Goob-Station pull request #1257
Opened 2024-12-24 17:23 UTC by Neptune-Zvezda

weh

## About the PR

Added 1 Winter coat, has cold resist unlike standard
## Why / Balance

single Coat
## Technical details

Add's New Rsi folder for item, adds prototype to Wintercoats Txt, Adds code to Winterdrobe
## Media

Later
## Requirements

- [x ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

I am Die
**Changelog**

- Add; N Parka to winter drobe, its just drip

2024-12-24 18:05 UTC, JustSome1Nearby commented
How dud you manage to not pass checks after adding a SINGLE COAT

2024-12-28 03:34 UTC, Piras314 requested changes

2024-12-28 03:34 UTC, Piras314 commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/winterdrobe.yml
> +    ClothingOuterNParka: 1
needs `# Goobstation` comment

2024-12-28 03:34 UTC, Piras314 commented on Resources/Prototypes/Entities/Clothing/OuterClothing/wintercoats.yml
> +- type: entity
Should be moved to `Resources/Prototypes/_Goobstation/Entities/Clothing/OuterClothing/wintercoats.yml`

2024-12-28 03:34 UTC, Piras314 commented on Resources/Textures/Clothing/OuterClothing/WinterCoats/CoatNparka.rsi/meta.json
Sprites should be moved to `Resources/Textures/_Goobstation/Clothing/OuterClothing/WinterCoats/CoatNparka.rsi/` and the sprite location in the prototype should be changed accordingly

2024-12-28 19:39 UTC, Piras314 requested changes

2024-12-28 19:39 UTC, Piras314 commented on Resources/Textures/_Goobstation/Clothing/OuterClothing/Wintercoats/CoatNparka.rsi/meta.json
You're tabbing/indenting with 2 spaces when there should be four. Please for the love of god install vscode so you can fix this easily if you make a PR again.

2024-12-28 19:40 UTC, Piras314 commented on Resources/Textures/_Goobstation/Clothing/OuterClothing/Wintercoats/CoatNparka.rsi/meta.json
BTW it's not working at all because of this, this actually does matter.

2025-01-05 01:45 UTC, Aidenkrz commented
closing because this still hasnt been fixed, also n parka is a dumb name make a better one lol

2025-01-05 01:45 UTC, closed without merging