Adds Dualetta new pistol
Goob-Station/Goob-Station pull request #1259
Opened 2024-12-25 13:14 UTC by ScyronX

## About the PR

Added dualetta a weapon that can only be fired when dual wielded with another dualetta
## Why / Balance

it has a high fire rate for a dual wield pistol but it costs a lot of TC and is hard to reload 

**Changelog**

🆑 
- add: Added dualetta, a weapon that can only be fired when dual wielded with another dualetta.
-

2024-12-25 13:58 UTC, TurboTrackerss14 commented
ClothingOuterVestWeb is 15TC. Which has this armor and insta valids you but is whatever. 
![image](https://github.com/user-attachments/assets/a3c38b43-7660-4f68-9ce4-bc1af33c9f24)

Detective armor is "free" here but gives similar armor values. so 15tc estimate ish.
![image](https://github.com/user-attachments/assets/29f57d02-ecd9-42d2-83f6-238aac05f55d)

MagazinePistolHighCapacity don't have a tc comparison so MagazinePistol will do ™️ costing 2tc each. 

Putting the cost of the actual pistols to 61TC. Thats 10 more than a fuckin c20. 

Dual wielding literally any other pistol will have the same effect other than magazine size, and if thats what you need.... the c20 is literally cheaper. 

What exactly is the usecase for these? or is this purely style points.

2024-12-25 14:04 UTC, ScyronX commented
> What exactly is the usecase for these? or is this purely style points.

other pistols dont have 8 fire rate

2024-12-25 14:09 UTC, TurboTrackerss14 commented
> > What exactly is the usecase for these? or is this purely style points.
> 
> other pistols dont have 8 fire rate

So why does a semi-auto pistol have a higher firerate than the cobra?? the full auto pistol?

2024-12-25 14:16 UTC, Aviu00 requested changes

2024-12-25 14:16 UTC, Aviu00 commented on Content.Shared/_Goobstation/Weapons/RequiresDualWield/RequiresDualWieldComponent.cs
> +[AutoGenerateComponentState]
Why use `AutoGenerateComponentState` and `AutoNerworkedField` when you never dirty this component?

2024-12-25 14:16 UTC, Aviu00 commented on Content.Shared/_Goobstation/Weapons/RequiresDualWield/RequiresDualWieldComponent.cs
> +    public TimeSpan LastPopup;
This shouldn't be `DataField`.

2024-12-25 14:16 UTC, Aviu00 commented on Content.Shared/_Goobstation/Weapons/RequiresDualWield/RequiresDualWieldSystem.cs
> +            PreventFiringWithoutDualWield(component,ref args);
```suggestion
            PreventFiringWithoutDualWield(component, ref args);
            break;
```

2024-12-25 14:16 UTC, Aviu00 commented on Content.Shared/_Goobstation/Weapons/RequiresDualWield/RequiresDualWieldSystem.cs
> +        foreach (var held in _handsSystem.EnumerateHeld(args.User, handsComp))
This `if` and `foreach` can be merged together so you don't enumerate twice.

2024-12-25 14:16 UTC, Aviu00 commented on Resources/Prototypes/_Goobstation/Catalog/Fills/Briefcases/briefcase.yml
> +      - id: ClothingHandsGlovesColorBlack
Add high capacity mag to uplink and replace black gloves with combat gloves so it's cooler.

2024-12-25 14:16 UTC, Aviu00 commented on Resources/Prototypes/_Goobstation/Catalog/uplink_catalog.yml
> +    Telecrystal: 80
Seems to be too much cost considering that you can buy 2 vipers for 28tc and have slightly less fire rate but slightly more accuracy.

2024-12-25 14:16 UTC, Aviu00 commented on Content.Shared/_Goobstation/Weapons/RequiresDualWield/RequiresDualWieldSystem.cs
> +            if (TryComp<RequiresDualWieldComponent>(held, out var DualWieldComponent))
Replace `TryComp` with `HasComp` and also maybe this should check for `MultishotComponent`? So it can be fired with viper for example.

2024-12-25 14:16 UTC, Aviu00 commented on Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/Pistols/pistol.yml
> +        startingItem: MagazinePistol
Maybe it should start with high capacity mag?

2024-12-25 14:16 UTC, Aviu00 commented on Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/Pistols/pistol.yml
> +    - SemiAuto
You won't be able to click 8 times per second unless you use autoclicker, so add `FullAuto` mode.

2024-12-25 14:24 UTC, ScyronX commented
> So why does a semi-auto pistol have a higher firerate than the cobra?? the full auto pistol?

because it can only be shot during dual wielding and its worth 80tc

2024-12-25 14:54 UTC, ScyronX commented on Resources/Prototypes/_Goobstation/Catalog/uplink_catalog.yml
> +    Telecrystal: 80
> Seems to be too much cost considering that you can buy 2 vipers for 28tc and have slightly less fire rate but slightly more accuracy.

Any price suggestions?

2024-12-25 15:00 UTC, Aviu00 commented on Resources/Prototypes/_Goobstation/Catalog/uplink_catalog.yml
> +    Telecrystal: 80
> Any price suggestions?

45-50tc would be fine.

2024-12-25 16:19 UTC, Aviu00 commented on Resources/Prototypes/_Goobstation/Catalog/uplink_catalog.yml
> +
Yeah, it should cost 3tc.

2024-12-25 17:26 UTC, TurboTrackerss14 commented
FTL strings need organising into their subgroups 
ammo in ammo etc etc.

2024-12-25 18:32 UTC, ScyronX commented
> FTL strings need organising into their subgroups ammo in ammo etc etc.
Do you mean like caliber? I just added caliber to the name in latest commit

2024-12-25 18:33 UTC, ScyronX commented on Resources/Prototypes/_Goobstation/Catalog/uplink_catalog.yml
> +
> Yeah, it should cost 3tc.

fixed

2024-12-25 18:46 UTC, Aviu00 requested changes

2024-12-25 18:46 UTC, Aviu00 commented on Resources/Locale/en-US/_Goobstation/store/uplink-catalog.ftl
> +uplink-highcap-pistol-mag-desc = High capacity pistol magazine holds 6 extra bullets for a total of 16 rounds.
It's actually 4 extra bullets, regular mags hold 12.

2024-12-25 18:46 UTC, Aviu00 commented on Resources/Locale/en-US/_Goobstation/store/uplink-catalog.ftl
> +uplink-dualetta-desc = Comes with 2 Dualetta pistols, 2 machine pistol magazines, black gloves, noir suit, detectives trenchcoat, and laceup shoes.
```suggestion
uplink-dualetta-desc = Comes with 2 Dualetta pistols, 2 machine pistol magazines, combat gloves, noir suit, detectives trenchcoat, and laceup shoes.
```

2024-12-25 19:28 UTC, ScyronX commented on Resources/Locale/en-US/_Goobstation/store/uplink-catalog.ftl
> +uplink-highcap-pistol-mag-desc = High capacity pistol magazine holds 6 extra bullets for a total of 16 rounds.
done

2024-12-25 19:31 UTC, TurboTrackerss14 commented
> > FTL strings need organising into their subgroups ammo in ammo etc etc.
> > Do you mean like caliber? I just added caliber to the name in latest commit

No I mean moving the ammo... to the ammo section of the file and not at the bottom.
and the gun/bundle in its section.

2024-12-25 19:32 UTC, Aviu00 approved these changes

2024-12-25 19:34 UTC, ScyronX commented
> No I mean moving the ammo... to the ammo section of the file and not at the bottom. and the gun/bundle in its section.

done

2024-12-25 23:11 UTC, Plyushsune commented
I would like it more if it was usable without the other pistol

2024-12-26 11:50 UTC, ScyronX commented on Resources/Locale/en-US/_Goobstation/store/uplink-catalog.ftl
> +uplink-dualetta-desc = Comes with 2 Dualetta pistols, 2 machine pistol magazines, combat gloves, noir suit, detectives trenchcoat, and laceup shoes.
Bot is suggesting misinformation

2024-12-28 16:26 UTC, Piras314 requested changes
Make it a MultiHandedItem instead of having RequiresDualWield, the latter is a very jank way of doing this in my opinion. Either that or make it so that they can be used individually but are extremely awful and together they are suddenly amazing.

2024-12-28 19:10 UTC, ScyronX commented
> Make it a MultiHandedItem instead of having RequiresDualWield, the latter is a very jank way of doing this in my opinion. Either that or make it so that they can be used individually but are extremely awful and together they are suddenly amazing.

Thats literally what I did you get total 16 fire rate when you use them together + the first option is a lot more jankier

2024-12-28 19:37 UTC, Piras314 requested changes

2024-12-28 19:37 UTC, Piras314 commented on Content.Shared/_Goobstation/Weapons/RequiresDualWield/RequiresDualWieldSystem.cs
> +
remove this newline

2024-12-28 19:37 UTC, Piras314 commented on Content.Shared/_Goobstation/Weapons/RequiresDualWield/RequiresDualWieldSystem.cs
> +
remove this newline

2024-12-28 19:37 UTC, Piras314 commented on Content.Shared/_Goobstation/Weapons/RequiresDualWield/RequiresDualWieldSystem.cs
> +        if(EnumeratedItems.ToList().Count <= 1)
put a space after if

2024-12-28 19:37 UTC, Piras314 commented on Content.Shared/_Goobstation/Weapons/RequiresDualWield/RequiresDualWieldSystem.cs
> +
remove this newline

2024-12-28 19:37 UTC, Piras314 commented on Content.Shared/_Goobstation/Weapons/RequiresDualWield/RequiresDualWieldSystem.cs
> +
remove this newline

2024-12-28 19:37 UTC, Piras314 commented on Content.Shared/_Goobstation/Weapons/RequiresDualWield/RequiresDualWieldSystem.cs
> +    }
add a new line after this line

2024-12-28 19:37 UTC, Piras314 commented on Content.Shared/_Goobstation/Weapons/RequiresDualWield/RequiresDualWieldSystem.cs
> +        var time = _timing.CurTime;
add a newline after this line

2024-12-28 19:37 UTC, Piras314 commented on Content.Shared/_Goobstation/Weapons/RequiresDualWield/RequiresDualWieldSystem.cs
> +
remove this newline

2024-12-28 19:37 UTC, Piras314 commented on Content.Shared/_Goobstation/Weapons/RequiresDualWield/RequiresDualWieldSystem.cs
> +
remove this newline

2024-12-28 19:37 UTC, Piras314 commented on Content.Shared/_Goobstation/Weapons/RequiresDualWield/RequiresDualWieldSystem.cs
> +
remove this newline

2024-12-28 19:37 UTC, Piras314 commented on Content.Shared/_Goobstation/Weapons/RequiresDualWield/RequiresDualWieldComponent.cs
> +
remove this newline

2024-12-28 19:37 UTC, Piras314 commented on Content.Shared/_Goobstation/Weapons/RequiresDualWield/RequiresDualWieldComponent.cs
> +
remove this newline

2024-12-28 20:13 UTC, Piras314 requested changes
See below for final formatting nitpick, you should make it so that you can dual wield the dualetta with another dualetta only (add whitelist to RequiresDualWieldComponent and use it in the yaml) and that you can buy just a pair of dualettas from the uplink for cheaper instead of only having the bundle.

2024-12-28 20:13 UTC, Piras314 commented on Content.Shared/_Goobstation/Weapons/RequiresDualWield/RequiresDualWieldSystem.cs
> +
remove this newline

2024-12-31 03:08 UTC, Piras314 approved these changes
LGTM

2024-12-31 03:08 UTC, merged