Buff humans
Goob-Station/Goob-Station pull request #1260
Opened 2024-12-25 15:08 UTC by Aviu00

## About the PR

Humans now receive 20% speed boost to their do-afters.

## Why / Balance

Humans should be superior. Right now they are outclassed by lizards with tail dragging or arachnids with extra pockets.

## Technical details

## Media

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl: Aviu
- add: Humans now interact 20% faster.

2024-12-25 15:13 UTC, Aineias1 commented
![Generic_assistant2.png](https://github.com/user-attachments/assets/5f2d241d-ca24-4ca4-b078-f95322194830)

Speciesm update?(Jk)

2024-12-25 16:17 UTC, deltanedas commented
we had that its called IPC NUMERO UNOOOOOO #1 #1 #1 :flag_br:

2024-12-25 16:21 UTC, whateverusername0 approved these changes

2024-12-25 19:41 UTC, lanse12 commented
wow you speciest fuck wtf is this pr

2024-12-25 19:45 UTC, jorgun commented
Can this somehow be tied to human hands. So we can remove and replace hands to gain the benefit.
(Robot devil idle hands gif)

2024-12-25 20:43 UTC, deltanedas commented
ipc with human hands + lizard tail + moth wings ultimate powergamer

2024-12-25 21:00 UTC, McBosserson commented
20% seems like a lot. And how about silicons? Slime people?(basically humans)

2024-12-25 22:50 UTC, Aviu00 commented
> Can this somehow be tied to human hands. So we can remove and replace hands to gain the benefit.

Done.

2024-12-26 06:43 UTC, whateverusername0 commented
> wow you speciest fuck wtf is this pr

uhmm backwards raceism isn't real 🤓

2024-12-26 06:44 UTC, whateverusername0 commented
> wow you speciest fuck wtf is this pr

🤓

2024-12-26 06:44 UTC, whateverusername0 commented
@Aviu00 i have the perfect solution for buffing humans

asimov lawset :godmode:

2024-12-26 06:48 UTC, JoeHammad1844 commented
> asimov lawset :godmode:

dehubbed

2024-12-26 06:56 UTC, whateverusername0 commented
> dehubbed

knowing them this pr is already a solid reason for that

2024-12-26 16:32 UTC, TurboTrackerss14 commented on Content.Shared/Silicons/StationAi/SharedStationAiSystem.cs
> +            MultiplyDelay = false, // Goobstaation
L + typo

2024-12-28 16:35 UTC, Piras314 requested changes
Let Dwarves still have human hands. I don't care about Felinids though keep them with slow hands.

2024-12-28 17:00 UTC, Aviu00 commented
> Let Dwarves still have human hands. I don't care about Felinids though keep them with slow hands.

Dwarves have a benefit of being smaller (harder to land a left click attack on them), so they are actually better than humans right now.

2024-12-29 02:19 UTC, G-370 commented
> Let Dwarves still have human hands. I don't care about Felinids though keep them with slow hands.

Aren't felinids literally half-cat, you know, the species known for being agile and fast?

2024-12-29 02:56 UTC, JoeHammad1844 commented
> Aren't felinids literally half-cat, you know, the species known for being agile and fast?

fuck 'em :trollface:
they dont need buffs

2024-12-29 03:07 UTC, McBosserson commented
Genetic damage resistance?

2024-12-29 07:00 UTC, CatMagic1 commented
I play human and I still think this is an ass change. It's just really unnecessary, all races have their own downsides anyway and there's no power imbalance between humans and other races. Other species aren't like "dominating" and people aren't not using humans because of how weak they are. And making humans better at something as common and universal as DOAFTERS is just going to discourage people from playing other species.

2024-12-29 08:28 UTC, TurboTrackerss14 commented
I think Nuclear Device defusal should 100% NOT be included in this. 
but I don't see it in the exclusions. double check?

2024-12-29 14:24 UTC, JoeHammad1844 commented
> just going to discourage people from playing other species.

implying that theres something wrong with that

2024-12-29 15:31 UTC, Aviu00 commented
> I think Nuclear Device defusal should 100% NOT be included in this. but I don't see it in the exclusions. double check?

Fixed.

2024-12-30 10:36 UTC, JoeHammad1844 commented
> Aren't felinids literally half-cat, you know, the species known for being agile and fast?
> 20% seems like a lot. And how about silicons? Slime people?(basically humans)

keep in mind that this is a human buff, not a humanoid buff, or we'd be buffing half the species

2024-12-31 04:07 UTC, CatMagic1 commented
> > just going to discourage people from playing other species.
> 
> implying that theres something wrong with that

I'm sorry, why do we want to discourage picking species other than human?

2024-12-31 07:05 UTC, JoeHammad1844 commented
> I'm sorry, why do we want to discourage picking species other than human?

because human doesn't have any advantages over other species
and i like humans (because im human :trollface:)

2025-01-01 17:41 UTC, CatMagic1 commented
> > I'm sorry, why do we want to discourage picking species other than human?
> 
> because human doesn't have any advantages over other species and i like humans (because im human :trollface:)

God I hate this game

2025-01-01 20:17 UTC, Piras314 approved these changes

2025-01-01 20:21 UTC, Piras314 requested changes
pls make dwarf like human i need my rock and stone... dwarves have the disadvantage of being short and stuff or something please i beg you my rock my stone, youll be blacklisted from the bar if you dont buff dwarves please


everything looks good to me other than that though

2025-01-01 20:30 UTC, Aviu00 commented
> dwarves have the disadvantage of being short and stuff

It's an advantage but ok.

2025-01-05 01:48 UTC, merged