Species and blob fixes
Goob-Station/Goob-Station pull request #1262
Opened 2024-12-25 18:44 UTC by Aviu00

## About the PR

Now ghost roles such as ninja, lone ops, ert and death squad can only be human.
Blob rolls before jobs.
No more multiple blobs per gamerule.
Blob doesn't die to flashbangs.
Yowie can't be nukie anymore (can't wear hardsuit).

## Why / Balance

It was kinda annoying to spawn as diona ninja for example (can't wear shoes) or similar stuff.

## Technical details

## Media

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl: Aviu
- add: Ghost roles such as ninja, lone operative, ert and deathsquad can only be human.
- add: Blob antag rolls before jobs now.
- fix: Blob doesn't die to flashes anymore.
- fix: Slime and gingerbread people now die to ling absorbing.

2024-12-25 18:50 UTC, Vlax2nd commented
> Now ghost roles such as ninja, lone ops, ert and death squad can only be human.
i swear there was a pr on upstream to do that, i dont see the point of it though

2024-12-26 06:48 UTC, whateverusername0 commented
> "Now ghost roles such as ninja, lone ops, ert and death squad can only be human." i swear there was a pr on upstream to do that, i dont see the point of it though

\>be vox deathsquad
\>oxygen tank enabled by default
\>:trollface:

2024-12-26 07:06 UTC, JustSome1Nearby commented
Spess Racism - The Update

2024-12-26 07:29 UTC, JoeHammad1844 commented
> Now ghost roles such as ninja, lone ops, ert and death squad can only be human.
> Yowies cant be nukies

speedmerge now 🙏

2024-12-28 17:56 UTC, Piras314 requested changes

2024-12-28 17:56 UTC, Piras314 commented on Content.Shared/Humanoid/Prototypes/RandomHumanoidSettingsPrototype.cs
> +    public string? SpecieWhitelist { get; private set; }
this should be SpeciesWhitelist not SpecieWhitelist

2024-12-28 18:34 UTC, Aviu00 commented on Content.Shared/Humanoid/Prototypes/RandomHumanoidSettingsPrototype.cs
> +    public string? SpecieWhitelist { get; private set; }
It's a single specie, not multiple.

2025-01-02 17:24 UTC, gluesniffler commented on Content.Shared/Humanoid/Prototypes/RandomHumanoidSettingsPrototype.cs
> +    public string? SpecieWhitelist { get; private set; }
Thats the singular form of the word though.

2025-01-02 21:47 UTC, Aviu00 commented on Content.Shared/Humanoid/Prototypes/RandomHumanoidSettingsPrototype.cs
> +    public string? SpecieWhitelist { get; private set; }
So true.

2025-01-04 12:14 UTC, Verbalase commented
![image](https://github.com/user-attachments/assets/f6714905-800a-4f44-b0b0-ce90192ea205)

2025-01-05 01:50 UTC, merged

2025-01-05 02:13 UTC, JoeHammad1844 commented
bless 🙏

2025-02-22 20:55 UTC, pheenty commented
feels kinda weird to took slime and gingerbread cellural immunity, can't we just make hollowing damage "armor-piercing", like how bible's damage still damages skeletons with airloss?