PDA Messaging
Goob-Station/Goob-Station pull request #1269
Opened 2024-12-26 13:15 UTC by angelofallars

## About the PR

**Port of Pull Request https://github.com/DeltaV-Station/Delta-v/pull/2362**

Original Message:

> adds pda messaging
> 
> each id card gets assigned a random 4 digit number using nameidentifier system (same system used for things like mobs), this number is used as your chat id rather than anything player facing like character names
> 
> the app ui has a left panel showing all your contacts with unread indicators, and a right panel showing the current chat conversation with bubble messages like a phone app, messages show in grey for others and green for your own messages
> 
> messages are stored directly on the id card component as two dictionaries - one for recipients (storing name/job/unread status) and one for the actual message history, both sender and receiver keep full copies of conversations
> 
> to prevent metagaming the system checks if both pdas have active telecomms connection and are on same station (unless using long range radio channel), failed messages show with a red error indicator
> 
> the detective's logprobe can scan an ID card and "connect" to it, allowing them to spy on people and view their recipients and messages in real time
> 
> interesting mechanics include:
> 
> - agent IDs can be used to impersonate others (they copy message conversation when you scan an ID, you can also change your number)
> - microwaving an id has 10% chance to wipe all messages, or randomly scramble message text and reassign conversations between contacts
> - message delivery requires working telecomms and respects radio blocking
> - notifications show truncated message previews up to 64 chars
> - contacts remember job titles from id cards (only if you message someone you dont know first)
> - messages store timestamps for rebuilding conversation order
> - supports up to 50 contacts per card
> - messages limited to 256 chars

## Why / Balance

Original Message:

> it's cool

## Technical details

## Media

Original Message:

<details><summary>Click me!</summary>

hiiiii

![image](https://github.com/user-attachments/assets/501a56ff-7549-4dc1-ba4f-28ea16122844)

![image](https://github.com/user-attachments/assets/fd082c83-52b9-499c-8740-51ac956e2b52)

![image](https://github.com/user-attachments/assets/63918dc6-3a16-40a5-aa60-03c320cdf34d)
![image](https://github.com/user-attachments/assets/4a9fa24f-f12f-46de-bbf7-2102d71b99db)
![image](https://github.com/user-attachments/assets/d079de71-b99d-4625-8bb8-e11b783b25b8)
![image](https://github.com/user-attachments/assets/46bc4f43-6a07-4eaa-916d-1606078c9255)

(microwaved)

![image](https://github.com/user-attachments/assets/ae7f6d4a-f4dd-43a5-a827-6b8ae46cd60d)

</details>

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl: MilonPL
- add: Added PDA messaging!

2024-12-26 18:53 UTC, whateverusername0 requested changes
we've been marking fork folders with an underscore for better navigation please do that here as well
![image](https://github.com/user-attachments/assets/58074e3f-e4ac-44b7-9fa3-5d2c0da46e33)

2024-12-27 03:11 UTC, deltanedas commented
thats how it is on deltav tbh i might change it to _ and break everything in the future

2024-12-27 18:18 UTC, angelofallars commented
> we've been marking fork folders with an underscore for better navigation please do that here as well ![image](https://private-user-images.githubusercontent.com/113782077/398787274-58074e3f-e4ac-44b7-9fa3-5d2c0da46e33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzMjE0ODAsIm5iZiI6MTczNTMyMTE4MCwicGF0aCI6Ii8xMTM3ODIwNzcvMzk4Nzg3Mjc0LTU4MDc0ZTNmLWU0YWMtNDRiNy05ZmEzLTVkMmMwZGE0NmUzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyN1QxNzM5NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDA5ZWQ4ZWJmMGFhMzUxMzhjYmNmMWQ0NDcyNWJiZTdjNzc5N2Q4NzMxY2U4MDU0NWZhOGU5MjU2YzQ0MWMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PpLmA9gFC2ViVQ2KMgd02WHkcUJOMTk0XWz1D1sKlbI)

I moved most of the files to the `_DeltaV` namespace, but some changes in `Resources/` were modifications to existing `DeltaV` files that other files unrelated to PDA messaging also rely on. Should I leave them as is or do you want me to also move them entirely to `_DeltaV`?

2024-12-27 18:26 UTC, Piras314 commented
We can fix the existing DeltaV folder (non _) stuff in a fix PR later.

2024-12-29 16:51 UTC, Aviu00 commented on Content.Client/_DeltaV/CartridgeLoader/Cartridges/NanoChatUiFragment.xaml.cs
> +            }
I don't like how it is checked clientside only. Message should be truncated to `MaxMessageLenght` on server side as well.

2024-12-30 18:56 UTC, AgentePanela commented on Content.Client/_DeltaV/CartridgeLoader/Cartridges/NanoChatUiFragment.xaml.cs
> +
```suggestion

MessageInput.OnTextEntered += _ => SendMessage(); // Send message when press enter
```

i add this to my downstream when a i port the messaging

2024-12-30 19:40 UTC, angelofallars commented on Content.Client/_DeltaV/CartridgeLoader/Cartridges/NanoChatUiFragment.xaml.cs
> +
Okay I'll add this too

2024-12-30 19:42 UTC, angelofallars commented
Server-side validation implemented with [c063001](https://github.com/Goob-Station/Goob-Station/pull/1269/commits/c063001ca97df3cd4ea69639b8f9c0cb9e51fc90). Message content when sending a message, and the recipient's name and job title when creating a new chat will now be trimmed of leading/trailing whitespaces and truncated when they go past their respective maximum length.

2024-12-30 19:55 UTC, angelofallars commented on Content.Client/_DeltaV/CartridgeLoader/Cartridges/NanoChatUiFragment.xaml.cs
> +
resolved with [0aec325](https://github.com/Goob-Station/Goob-Station/pull/1269/commits/0aec3258bb1dded4a680f82373932a6c4bc820d3)

2024-12-30 19:55 UTC, angelofallars commented on Content.Client/_DeltaV/CartridgeLoader/Cartridges/NanoChatUiFragment.xaml.cs
> +            }
resolved with [c063001](https://github.com/Goob-Station/Goob-Station/pull/1269/commits/c063001ca97df3cd4ea69639b8f9c0cb9e51fc90)

2024-12-31 00:31 UTC, Piras314 approved these changes
LGTM

2024-12-31 00:33 UTC, merged