Firefighting Nozzle, Atmos Backpack Water Tank and Atmos Resin
Goob-Station/Goob-Station pull request #1271
Opened 2024-12-26 18:32 UTC by marc-pelletier

## About the PR
Added Atmos Resin. A type of foam that cleans the air of toxins, and normalizes temperatures. 
Added a firefighter nozzle. This acts as a more powerful fire extinguisher, or if in hostile mode, acts similar to a projectile launcher. 
Added a new firefighter water tank backpack. It can hold 250 more units than the standard water tank backpack, and shoots Atmos Resin projectiles when used with a firefighter nozzle. 

## Why / Balance
Fires will be station ending a little bit less, and gives atmos more tools to fight fires and gas leaks than the typical engi, hopefully forcing them out of their caves once in a while. 

I deviated from the original ATMOS resin concept since I felt it would primarily be used for griefing at worst, or be a very overpowered tool for antags at best. Unlike 13, this ATMOS resin does not leave behind impassable walls that you need to break. It also does not perfectly return the air to a 22/78 101kpa mix like in 13. However, it can be fired much faster than in 13 and is directly tied to the water level of your storage tank, rather than needing to regenerate over time. 

## Technical details
This code touches both SmokeSystem and components, SmokeOnTriggerSystem and SpraySystem and components. SpraySystem has been extended to allow for external solution containers. SmokeSystem currently contains the logic for Atmos Resin. 

## Media

https://github.com/user-attachments/assets/11dcc888-c690-4ab2-b353-f6a330649731

https://github.com/user-attachments/assets/b48c6d4b-6cad-4c37-94fb-6defa19ad85a

https://github.com/user-attachments/assets/7e741c16-98cf-4b84-9792-7b892dfca4f9

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
All changes are marked and any code that has been changed is commented out so that it can be restored easily. 

**Changelog**
:cl:
- add: Added firefighting water tank backpacks to atmos

2024-12-27 07:25 UTC, BlueHNT commented
Needs to be able to use it on himself and extinguish players properly, the third demo showed how you were unable to do that.

2024-12-27 08:01 UTC, marc-pelletier commented
> Needs to be able to use it on himself and extinguish players properly, the third demo showed how you were unable to do that.
> 
> (unless it was a minor skill-issue)
> 
> Perfect fucking PR otherwise tho. Love it.

It's just a typical fire extinguisher. You can put others out, but not yourself. Last video was 90% skill issue.

2024-12-27 19:16 UTC, marc-pelletier commented
PR passed tests on forks so build failures seem to be unrelated.

2024-12-28 17:00 UTC, Piras314 commented
I've been hoping for something to make overheating something that can be fixed in anywhere near a reasonable time for a long time now! Gonna review and check this out now.

2025-01-03 16:09 UTC, Piras314 requested changes
1. You should be able to mix your own atmos resin via chemistry
2. The nozzle and tank should be added to the firefighting supplies crate
3. The resin should normalize temperature more

2025-01-03 18:20 UTC, BlueHNT commented
> 1. You should be able to mix your own atmos resin via chemistry

Last I've heard of atmos resin, it's just water with some internal tank chems... You don't mix anything.

> 3. The resin should normalize temperature more
It is intended for plasmafires... How much does it normalize temp rn even? Is it based on the amount of moles of gas present in the area?

2025-01-05 03:39 UTC, marc-pelletier commented
> It is intended for plasmafires... How much does it normalize temp rn even? Is it based on the amount of moles of gas present in the area?

The way it currently works is that every tile it spreads to is set back to 20C and everything that isn't oxygen, nitrogen or water vapor gets removed. It only happens on initial spread, which means the heat and gases from all the tiles around it flows back in. 

I'll see if I can do it as it dissipates as well. The only reason I didn't bother is because I though collapsing the temperature in a large portion of a hot room will increase space wind and thus lag, but I never even tested it and I think we have space wind off at the moment anyway.

2025-01-05 07:09 UTC, marc-pelletier commented
> 1. You should be able to mix your own atmos resin via chemistry

I'm probably not going to do this. The excessive amount of water it takes to fire them is meant to act as a balance to their use. That said, if it's a PR someone else wants to make, all the components and systems are done in a way very similar to metal foam. You just need to use the Resin smoke prototype and everything else will work fine. 

> 2. The nozzle and tank should be added to the firefighting supplies crate

I have a PR lined up that adds it to cargo's catalog. I have it sold separate from the firefighting crate for a few reasons. One, this comes prefilled so I wanted it to be comparable in price to a water tank. Another reason is that this is capable of being the best flamethrower in the game at the moment, and I felt like it should be in a crate that's locked to engineering. I'm not particularly worried about these issues though so if you still want it added to the firefighting crate I can do it quick. 

> 3. The resin should normalize temperature more

Done. It now removes toxins and normalizes temperatures in the entire covered area after the resin dissipates, rather than on initial tile spread, and I increased the duration so that each shot spreads to far more tiles. I also moved it out of SmokeSystem and into it's own atmospheric system and component. SmokeSystem, SmokeComponent, and SmokeOnTriggerComponent have been reverted back to their originals.

2025-01-06 20:04 UTC, Piras314 commented
> I'm probably not going to do this. The excessive amount of water it takes to fire them is meant to act as a balance to their use. That said, if it's a PR someone else wants to make, all the components and systems are done in a way very similar to metal foam. You just need to use the Resin smoke prototype and everything else will work fine.

I mean it's really weird in my opinion that all you need is water to use this, I think it should definitely be firing its own reagent (that should be very easy to make as chemist, maybe even make it with a chem that has an associated gas so atmos can make it themselves) and the backpack tank should have a chem whitelist for it so you can't use it as a flamethrower. Also you should remove the storage from the backpack tank cause it makes transferring chems into it not work (maybe drag works but at minimum it's annoying.)

> I have a PR lined up that adds it to cargo's catalog. I have it sold separate from the firefighting crate for a few reasons. One, this comes prefilled so I wanted it to be comparable in price to a water tank. Another reason is that this is capable of being the best flamethrower in the game at the moment, and I felt like it should be in a crate that's locked to engineering. I'm not particularly worried about these issues though so if you still want it added to the firefighting crate I can do it quick.

Add a chem whitelist to the water tank and make the firefighting kit engi or atmos locked.

2025-01-09 17:35 UTC, Piras314 commented
@marc-pelletier

2025-01-12 14:40 UTC, BlueHNT commented
Guess it's becoming unusable right off the bat...

2025-01-31 17:26 UTC, Piras314 commented
1 month

2025-01-31 17:26 UTC, closed without merging