New ling abilities
Goob-Station/Goob-Station pull request #1273
Opened 2024-12-27 00:25 UTC by Aviu00

## About the PR

Armblade now deals 25 slash, has 0.75 attack rate, breaks a leg in 2 hits and cuts off head in 3.
Added 2 new ling melee weapons.
- Arm hammer: 40 blunt damage, 0.5 attack speed. Able to knockdown victims and send them flying.
- Arm claw: 25 piercing damage, 1 attack speed. Can to aggro grab people instantly (ghetto grab intent) when pulling with it, can't attack while it's actively grabbing and breaking out of grab takes 5 seconds.

People without can't break out of grabs anymore.

Added sting dart gun for ling. Able to select between any of evolved reagent stings. Shoots a dart that injects half the reagents of the sting. Each shot costs 5 chemicals.
Stings are now cheaper  but inject less chemicals. Each reagent sting costs 25 chemicals and 3 evolution points, fake armblade sting costs 4 points.
Blind sting is now reagent based.
Cryo sting no longer injects chloral hydrate.
lethargic sting no longer injects mute toxin but it injects new reagents that slowly drains stamina.

Sprites were taken from bay12, so icons look out of place. It would be nice if someone resprited them. Also dart gun doesn't have inhand sprites.

This may or may not be unbalanced, will see.

## Why / Balance

Armblade is bad currently as it deals no direct damage and also ling needs new melee options.

## Technical details

Dart gun uses hardlight bow selectable ammo system and `ChangelingChemicalAmmoProviderComponent`. Reagent stings were refactored, now reagents are stored in sting configuration proto which is stored in reagent sting component on sting actions. Dartgun projectiles also use these sting configurations.

## Media

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl: Aviu
- add: Added 2 new ling melee weapons: arm hammer and arm claw.
- add: Added ling dart gun, able to sting at range.
- add: People without legs can't break out of grabs anymore.
- tweak: Armblade damage heavily increased, attack rate decreased. It delimbs roughly the same as before.
- tweak: Ling stings are now cheaper but inject less chemicals.
- tweak: Cryo sting doesn't inject chloral hydrate anymore.
- tweak: Lethargic sting doesn't inject mute toxin but slowly drains victim's stamina.

2024-12-27 01:21 UTC, JoeHammad1844 commented
You should still be able to break out of grabs if you don't have legs, but you shouldn't if you don't have arms

2024-12-27 01:42 UTC, BombasterDS2 commented
3 hits to cut off head is too op

2024-12-27 07:02 UTC, JustSome1Nearby commented
RN its IMPOSSIBLE to cut off head in combat. I was making like 10 and more hits in a row while my oponent laughed at the attempt and called me a lingnerd

Making it 3 hits, more than for other limbs, knowing people also can EVADE on one or more of the hits, makes it fairly balanced and rewarding i think

Like dude, the cryo sting is basicly infinite Noct. Hypopen and its allready, not funny to use it so much... 
And everyone uses it as default cause armblade stinks...
Other stings are HILARIOUSLY USELESS compared to cryo and are designed for atacking after the sting, wich is not possible without a gun or something...

2024-12-27 07:17 UTC, JustSome1Nearby commented
> 3 hits to cut off head is too op

Like infinite Noct Hypopen OP? And its the LEADING CAUSE of 90 % ling absorbs.
Sting-cuff-absorb
And there is like nothing to do about it if you are caught by ling like that
And the body is unrevivable!

When chopping off the head, you AT LEAST 
- make half of Med's job extracting the head for transplant 
- become VALID after a LOUD atack, forcing you to ACTUALY USE CHAGELING'S MAIN ABILITY and take another form for disguise 
- Force you to change clothes since person who you killed will know your outfit

2024-12-27 07:30 UTC, BombasterDS2 commented
> > 3 hits to cut off head is too op
> 
> Like infinite Noct Hypopen OP? And its the LEADING CAUSE of 90 % ling absorbs. Sting-cuff-absorb And there is like nothing to do about it if you are caught by ling like that And the body is unrevivable!
> 
> When chopping off the head, you AT LEAST
> 
> * make half of Med's job extracting the head for transplant
> * become VALID after a LOUD atack, forcing you to ACTUALY USE CHAGELING'S MAIN ABILITY and take another form for disguise
> * Force you to change clothes since person who you killed will know your outfit

If you cut off someone head you will absorb him anyway that will make body unrevivable aswell. Also, with surgery you can easily transplant brain from one body to another.

3 hits (4 seconds with 0.75 attack rate) to behead someone sounds overpowered and this don't fix ling main problem - useless stasis and lack of defense. Ling shouldn't be glass cannon antag, we have ninja for this.

2024-12-27 07:31 UTC, BombasterDS2 commented
Not against other changes, but armblade severing is overpowered in my opinion.

2024-12-27 08:38 UTC, whateverusername0 commented
@Aviu00 can you make regular armblade the same as it was before armok made it delimbing?
It was a slightly better combat knife but might as well add some delimbing capacity to it.

2024-12-27 08:43 UTC, whateverusername0 requested changes
bla bla bla make textures have the same style also read what i said earlier

2024-12-27 09:23 UTC, JustSome1Nearby commented
Also can you make Ling Hammer have a 1% chance of making Bwoink sound 🤡

2024-12-27 09:40 UTC, Aviu00 commented
> bla bla bla make textures have the same style also read what i said earlier

I can't sprite, sadly. I added borders to action icons, it's the best I can do. Maybe someone else will make sprites after the merge.

2024-12-27 10:30 UTC, JustSome1Nearby commented
> I can't sprite, sadly. I added borders to action icons, it's the best I can do. Maybe someone else will make sprites after the merge.

I might try, i love spriting ... But my time managment is non existent

2024-12-27 10:48 UTC, Aviu00 commented
> @Aviu00 can you make regular armblade the same as it was before armok mauled it? It was a slightly better combat knife but might as well add some delimbing capacity to it.

Done.

2024-12-27 10:49 UTC, Aviu00 commented
> I might try, i love spriting

This would be awesome.

2024-12-27 19:50 UTC, whateverusername0 commented on Resources/Prototypes/_Goobstation/Changeling/Entities/Objects/Weapons/Melee/changeling_armblade.yml
> +    heavyPartDamageMultiplier: 1.5
god bless the old armblade

2024-12-29 11:53 UTC, Aviu00 commented
Made it so blind sting no longer damages eyes as it could blind a person if stung like 3 times.

2025-01-03 12:59 UTC, BlueHNT commented
Did some private testing and I got some notes...

### The good:
- The tirizine in the lethargy is much better than shit ton of imped with mute toxin, great job there.
- Armblade feels about right. The damage feels about right and 4 hits on average to delimb unarmored person.
- The stings aren't a death sentence anymore, but I still feel like they should get some kind of cooldown on their uses (collective)

### The bad:
- Hammer and Claw are **wayyyyyy** too strong, the kill times, stuns and just about everything is busted about them.

<details>
<summary>[The nerd yapping and comparsion]</summary>

#### Sooooo...

The comparison of damage between the 3 is
- Blade **15 slash - Claw 25 slash - Hammer 40 blunt**

It's insane, the cooldown between hit doesn't warrant enough in actual combat, the hammer is just plain insane. Rather than going with high damage differences, you can attach unique abilities to them.

For example **The Claw** going down a bit to like 20 at same attackRate, but having the ability to pry open doors, even while powered.

As for **The Hammer**, you can give it high structural damage. Break walls 'n' shit with it. CRACK BONES. (future shitmed)

**The Blade** on the other hand is already more or less decided to be a 15 slash menace which you swing around wildly at fast speeds and delimb everyone.

_You could also look at PROTOTYPE games for some ideas in that._
</details>

### The others?
- I still can't see the blind and freezing sting being useful sadly, unless you're abusing freezing chems or just wanna slow someone.
- The hammer knocks you over when you get hit, but you need to press the button to stand up... Is that intended?

2025-01-03 13:03 UTC, BlueHNT commented on Resources/Prototypes/_Goobstation/Changeling/Entities/Objects/Weapons/Melee/changeling_armblade.yml
> -    wideAnimationRotation: 90
Why did you remove the WideSwing?

2025-01-03 13:04 UTC, BlueHNT commented on Resources/Prototypes/_Goobstation/Changeling/Entities/Objects/Weapons/Melee/changeling_armblade.yml
> -    wideAnimationRotation: 90
oh nvm I'm stupid, that's the Fake ArmBlade. LOL

2025-01-03 13:06 UTC, BlueHNT commented on Resources/Prototypes/_Goobstation/Changeling/Entities/Objects/Weapons/Melee/changeling_hammer.yml
> +        Structural: 90
40 is still wayy too much... 30 would work?
```suggestion
        Blunt: 30
```

2025-01-03 13:17 UTC, Aviu00 commented on Resources/Prototypes/_Goobstation/Changeling/Entities/Objects/Weapons/Melee/changeling_hammer.yml
> +        Structural: 90
Its attack rate is 0.5 so DPS is actually lowest amongst the 3 ling weapons.

2025-01-03 13:32 UTC, BlueHNT commented on Resources/Prototypes/_Goobstation/Changeling/Entities/Objects/Weapons/Melee/changeling_hammer.yml
> +        Structural: 90
Let's gather 3 people and put em to practical test. I believe claw or hammer will win easily due to the claw DPS and Hammer utility (the knock back is insane)

2025-01-03 13:32 UTC, Aviu00 commented
> I still can't see the blind and freezing sting being useful sadly, unless you're abusing freezing chems or just wanna slow someone.

Freezing sting slows down better and for longer time than lethargic. But yeah, lethargic is probably still better cause it drains stamina as well. Blind sting is good when you are fighting people with guns. Sting chemical cost can be tweaked I guess.

> The hammer knocks you over when you get hit, but you need to press the button to stand up... Is that intended?

Yes.

2025-01-03 13:41 UTC, BlueHNT commented
> > I still can't see the blind and freezing sting being useful sadly, unless you're abusing freezing chems or just wanna slow someone.
> 
> Freezing sting slows down better and for longer time than lethargic. But yeah, lethargic is probably still better cause it drains stamina as well. Blind sting is good when you are fighting people with guns. Sting chemical cost can be tweaked I guess.

Minor idea, you could work the freezing sting into a healing sting by adding some cryo meds into it. You can heal yourself, with it you could heal others if you truly wanted to... 
Though I can't see the situation in which you would want to do that.
There isn't cryo-poison after all.

2025-01-06 11:07 UTC, Aviu00 commented
Made reagent stings cost 2 evo points and 20 chemicals except for lethargic sting which cost 3 points and 30 chems.
Dart gun now shoots once per second, but it's fire cost increased to 1/3rd of selected sting chem cost.
Hammer attack rate increased to 0.75, damage lowered to 30 and it now knocks down on light attack only.
Toggling off ling equipment doesn't cost any chemicals anymore.
Dart gun now shows selected sting indicator near the cursor, also applies to hardlight bow, multiphase and energy shotgun.

2025-01-11 17:14 UTC, merged

2025-02-07 12:26 UTC, JustSome1Nearby commented
![ArmHammer](https://github.com/user-attachments/assets/14d3b599-a108-4215-9074-d3c2ef7e9161)

How would this look as an armhammer? I just did this sprite in colors of an Armblade, while keeping the bone-hammer aesthetic