Adds Banana people (Only Adminspawn)
Goob-Station/Goob-Station pull request #1274
Opened 2024-12-27 01:08 UTC by BeeRobynn

## About the PR
Add's Bananapeople as a spawnable race. Currently only via the admin menu because I'm still trying to decide where the best place to put them is (no they shouldn't be roundstart they are literally potassium generators and will be used for raiding, don't make a bounty pr for it)

Future pr's that me or someone who wants it enough will do:

- [ ] Displacement maps to make clothing look a bit better
- [ ] A way for them to be obtainable ingame
- [ ] A smite that makes you into one
- [ ] Guidebook documentation if you ignore me and make it roundstart

## Why / Balance
Fucking......bananas, man, idk

## Technical details
Adds slipperyonlayingdown as a component so you can turn anyone into a bananapeople when they drop to the floor

## Media
![image](https://github.com/user-attachments/assets/bfcee8c8-6137-4db6-b7b5-5c4f382b978c)

## Requirements

- [x] I have read and am IGNORING the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**
:cl:
- add: Added Banana People as a (currently admin-only spawn) species!

2024-12-27 01:22 UTC, BeeRobynn commented on Resources/Prototypes/_Goobstation/Species/bananamen.yml
> +    state: r_foot
This issue does not exists, as the path Resources/Textures is already implied and works fine without it. Also, in the future, please only make code reviews and interactions with me on my PR's as a disinterested goth person

2024-12-27 06:10 UTC, JustSome1Nearby commented
Add them to Plant anom OR botanical Banana Mutation

2024-12-27 08:26 UTC, AstroDogeDX commented
I for one welcome our new banana overlords.

2024-12-27 09:20 UTC, JustSome1Nearby commented
Idea
Add a funny Ling gamemode where all lings are literally Minions trying to eat the banana people

2024-12-27 16:51 UTC, AgentePanela commented
Bananas in pyjamas
![image](https://github.com/user-attachments/assets/cd3758de-6317-4a71-bb14-15cc36fcec1d)

2024-12-27 19:45 UTC, whateverusername0 commented
beerobyn is evolving
a NON ROUNDSTART race with a DIFFICULT UNLOCKING method? unbelievable.

2025-01-02 03:04 UTC, Piras314 requested changes
fix your indentation and style and randomly 2 new lines at the bottom or else

2025-01-03 04:18 UTC, deltanedas commented
> Bananas in pyjamas ![image](https://private-user-images.githubusercontent.com/107573283/398977500-cd3758de-6317-4a71-bb14-15cc36fcec1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4NzgyMTQsIm5iZiI6MTczNTg3NzkxNCwicGF0aCI6Ii8xMDc1NzMyODMvMzk4OTc3NTAwLWNkMzc1OGRlLTYzMTctNGE3MS1iYjE0LTE1Y2MzNmZjZWMxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwM1QwNDE4MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNjBlYjQ1ZDM1NzljNzI1YzU5OGFhMGY2YjU3ZTIzYzQ5M2FjNzk1ZTE5ZTRlYzM2NzAzMTQ0NTlmOGJiZjI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Hsh-nVLyT-7kO7-WN4Mn9FB7VAc7wvpDRUYGWuOtJiI)

holy based

2025-01-05 01:58 UTC, merged