1 less ling spawn
Goob-Station/Goob-Station pull request #1281
Opened 2024-12-27 16:37 UTC by Sarahon

## About the PR
I just slightly rebalanced ling spawns

## Why / Balance
I think 7 lings right now, is just too much for the station. I've seen constant complaining and experienced the headache they can be. 

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl: Tweak: Slight ling spawn rebalance

2024-12-27 21:34 UTC, JustSome1Nearby commented
Yeah 2 last rounds that i played as one, lings basicaly teamed up and took over the station...CAUSE WHY NOT
Its EASY to kill IPCs once you figure out EMP shriek and the leg delimbing with cryo sting takes care of humans

2024-12-28 17:51 UTC, Piras314 requested changes
Decrease the ling spawn even more in my opinion. Lings are incredibly powerful, I'd say 3-5 lings at 85 pop is enough.

2024-12-28 20:16 UTC, McBosserson commented
I missed the occasional shear choas of the 35 ling rounds, before the antag patch.

2024-12-28 20:46 UTC, deltanedas commented
theres already incentive to eat other lings its just ape together strong is much more powerful for taking over the station and killing everyone

2024-12-29 01:46 UTC, Sarahon commented
> Decrease the ling spawn even more in my opinion. Lings are incredibly powerful, I'd say 3-5 lings at 85 pop is enough.

Sure, I was gonna do it in increments just to see how it goes but if you think that's fair then I personally agree.

2024-12-29 01:48 UTC, Sarahon commented
> theres already incentive to eat other lings its just ape together strong is much more powerful for taking over the station and killing everyone

It's become the meta to just gang so I've seen them take over the station in consecutive rounds all this week.

2024-12-30 01:01 UTC, Piras314 approved these changes

2024-12-30 01:02 UTC, merged

2024-12-30 02:20 UTC, whateverusername0 commented
bro just killed the main ling gamemode

2024-12-30 08:29 UTC, Sarahon commented
> bro just killed the main ling gamemode

I've seen 3 lings take over a station on full pop. They'll be fine.