Frezon canister sprite
Goob-Station/Goob-Station pull request #1293
Opened 2024-12-28 22:41 UTC by marc-pelletier

## About the PR
Adds the old freon can sprite to frezon to replace the duplicated oxygen can sprite. Unfortunately, breaking the can still leaves behind a broken oxygen can for the time being. 

## Why / Balance
Looks better. Particularly in the guidebook. 

## Technical details
None

## Media
![frezon](https://github.com/user-attachments/assets/837a6c47-965e-413e-8454-c3bce245e8dc)

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
None

**Changelog**
:cl:
- add: Added frezon canister sprite

2024-12-29 14:31 UTC, whateverusername0 approved these changes

2025-01-01 13:56 UTC, BlueHNT commented
I think I'll make one.

2025-01-05 02:01 UTC, Aidenkrz requested changes
add the sprite blue made

2025-01-05 02:01 UTC, Aidenkrz commented
oh they PRd it seperately

2025-01-05 02:01 UTC, merged