added smuggler satchel
Goob-Station/Goob-Station pull request #246
Opened 2024-06-02 09:07 UTC by jorgun

## About the PR

## Why / Balance

## Technical details

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

2024-06-02 13:55 UTC, CatMagic1 commented
Honestly, the spice removals are unneeded. It's all random and finding a secret little floorboard bag then the bag having absolutely nothing interesting would be extremely disappointing.

2024-06-02 13:57 UTC, CatMagic1 commented
Also in uplink_catalogue.ftl you said "underneet"

2024-06-02 14:01 UTC, CatMagic1 commented
also up the gatfruit (and maybe even carp) chance because it's not all that crazy of contraband
i see gatfruit like all the time

2024-06-02 14:07 UTC, jorgun commented
> said

fixed

2024-06-02 14:12 UTC, jorgun commented
> Honestly, the spice removals are unneeded. It's all random and finding a secret little floorboard bag then the bag having absolutely nothing interesting would be extremely disappointing.

that is a risk of randomness

>Also in uplink_catalogue.ftl you said "underneet" ye spotted haddent pushed it yet

>also up the gatfruit (and maybe even carp) chance because it's not all that crazy of contraband
i see gatfruit like all the time

2024-06-02 14:34 UTC, CatMagic1 commented
It should be "hidden underneath floorboards". Bruh.

2024-06-02 15:23 UTC, jorgun commented
updated example pictures

2024-06-02 21:25 UTC, CatMagic1 commented
no in uplink_catalogue.ftl it should say ""hidden underneath floorboards""

2024-06-02 23:03 UTC, jorgun commented
just "hidden underneath floorboards" ?

2024-06-03 20:33 UTC, CatMagic1 commented
> just "hidden underneath floorboards" ?

nevermind you already changed it

2024-06-04 19:49 UTC, misandrie requested changes
Probabilities are out of whack

2024-06-04 19:49 UTC, misandrie commented on Resources/Prototypes/Catalog/Fills/Backpacks/smugglersatchel.yml
> +        prob: 0.1
This is an entry tool through any door that is not bolted, potentially given out for free.

2024-06-04 19:49 UTC, misandrie commented on Resources/Prototypes/GameRules/events.yml
> +      path: /Audio/Announcements/attention.ogg
Average round goes for ~70 minutes. Having two separate events spawning free loot, with one immediately prompting a server-wide hunt for gamer loot is a bad idea. In a 70-minute timeframe you can have at most 9 different satches around station.

2024-06-04 20:09 UTC, a-person5660 commented on Resources/Prototypes/Catalog/Fills/Backpacks/smugglersatchel.yml
> +        prob: 0.1
science can mass produce these with a T2 industrial tech, they arent rare. i think its ok to be there.

2024-06-04 20:17 UTC, jorgun commented on Resources/Prototypes/GameRules/events.yml
> +      path: /Audio/Announcements/attention.ogg
it is a bit overtuned. but its not announced so there as there is no announcment. i assume less will be lookingfor the satchels. Doing there own thing, then when the anouncment goes off. there will be a rush hunting for the satchels then having 3 or 4 to find.

2024-06-04 21:18 UTC, misandrie commented on Resources/Prototypes/Catalog/Fills/Backpacks/smugglersatchel.yml
> +        prob: 0.1
T2 industrial implies science is doing work, which is
A) An anomaly
B) Not free

Being able to print jaws of life does not invalidate giving them to anyone for free with no pre-reqs or work required being a bad idea.

2024-06-04 21:19 UTC, misandrie commented on Resources/Prototypes/GameRules/events.yml
> +      path: /Audio/Announcements/attention.ogg
Yeah, they'll be finding satchels left right and center when a very late stash gets announced to the entire server. Two max on station per round?

2024-06-05 13:56 UTC, jorgun commented on Resources/Prototypes/GameRules/events.yml
> +      path: /Audio/Announcements/attention.ogg
increased time and set a cap on the  numbers spawned..
i whud want to actualy test it and see how it will affect the game before lowering it further.

2024-06-11 15:05 UTC, Piras314 requested changes
You need to move these changes to Resources/Goobstation and Resources/Locale/en-US/Goobstation. I also suggested a small change in the description, and there are a lot of typos so I didn't correct them all, mostly in your comments.

2024-06-11 15:05 UTC, Piras314 commented on Resources/Prototypes/Catalog/uplink_catalog.yml
Again, move this to Resources/Prototypes/Goobstation/Catalog/uplink_catalog.yml

2024-06-11 15:05 UTC, Piras314 commented on Resources/Prototypes/Entities/Clothing/Back/satchel.yml
Resources/Prototypes/Goobstation/Entities/Clothing/Back/satchel.yml please

2024-06-11 15:05 UTC, Piras314 commented on Resources/Prototypes/Entities/Clothing/Back/satchel.yml
> +  description: A trendy looking satchel.
suspicious is a more fitting description than trendy

2024-06-11 15:05 UTC, Piras314 commented on Resources/Prototypes/Entities/Clothing/Back/satchel.yml
> +  description: A trendy looking satchel.
same thing on line 204

2024-06-11 15:05 UTC, Piras314 commented on Resources/Prototypes/GameRules/events.yml
Resources/Prototypes/Goobstation/GameRules/events.yml please

2024-06-11 15:47 UTC, misandrie commented on Resources/Prototypes/Catalog/Fills/Backpacks/smugglersatchel.yml
> +        prob: 0.1
Those are weights, in this case it is 10% because its 1.0 total.

2024-06-11 16:08 UTC, Piras314 commented on Resources/Prototypes/Catalog/Fills/Backpacks/smugglersatchel.yml
> +        prob: 0.1
alright yeah so I was right, well it looks like this chance is applied to each item, meaning these chances need to be significantly lowered because at the moment it's practically guaranteed you'll get multiple of these items. Maybe 0.05 or 0.025 is better for the 0.1 items. Gas mask being 0.4 is fine though for example.

2024-06-13 15:01 UTC, jorgun commented on Resources/Locale/en-US/station-events/events/smuggler-satchel.ftl
fixed

2024-06-13 15:02 UTC, jorgun commented on Resources/Prototypes/Catalog/Fills/Backpacks/smugglersatchel.yml
fixed

2024-06-13 15:03 UTC, jorgun commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/clothesmate.yml
this part cant be moved

2024-06-13 15:03 UTC, jorgun commented on Resources/Prototypes/GameRules/events.yml
fixed

2024-06-13 15:03 UTC, jorgun commented on Resources/Prototypes/Entities/Clothing/Back/satchel.yml
> +  description: A trendy looking satchel.
fixed, exelent sugestion

2024-06-13 15:04 UTC, jorgun commented on Resources/Prototypes/Entities/Clothing/Back/satchel.yml
fixed

2024-06-13 15:05 UTC, jorgun commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/clothesmate.yml
Fixed

2024-06-13 15:21 UTC, jorgun commented on Resources/Prototypes/Catalog/Fills/Backpacks/smugglersatchel.yml
> +        prob: 0.1
its not "free" 
 ther is just a chance of it spawning and you need to searth to find the bag.
 the bag shud contain loot that is worth looking for.
 i added a tool group so that only one tool can spawn reducing the randomness a bit

2024-06-13 15:22 UTC, jorgun commented on Resources/Prototypes/Catalog/Fills/Backpacks/smugglersatchel.yml
> +        prob: 0.1
not sure what you mean by multiple, but i reduced the combatgloevs to 1%

2024-06-13 17:58 UTC, Piras314 requested changes
a lot of things you said are fixed aren't fixed, perhaps you forgot to push your changes?

2024-06-13 17:58 UTC, Piras314 commented on Resources/Locale/en-US/station-events/events/smuggler-satchel.ftl
@jorgun still seems to be there...

2024-06-13 17:58 UTC, Piras314 commented on Resources/Prototypes/Catalog/Fills/Backpacks/smugglersatchel.yml
> +        prob: 0.1
the problem is 0.1 is 10% not 1% @jorgun

2024-06-13 17:58 UTC, Piras314 commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/clothesmate.yml
true, my bad

2024-06-13 17:58 UTC, Piras314 commented on Resources/Prototypes/Entities/Clothing/Back/satchel.yml
doesn't seem fixed to me, did you not merge your changes or something @jorgun ?

2024-06-13 17:58 UTC, Piras314 commented on Resources/Prototypes/Catalog/uplink_catalog.yml
this is not fixed

2024-06-13 17:58 UTC, Piras314 commented on Resources/Prototypes/Catalog/Fills/Backpacks/smugglersatchel.yml
this is not fixed

2024-06-13 17:58 UTC, Piras314 commented on Resources/Locale/en-US/store/uplink-catalog.ftl
this is not resolved, move the file don't just add a comment

2024-06-13 17:58 UTC, Piras314 commented on Resources/Locale/en-US/store/uplink-catalog.ftl
move the code to a different file, I mean

2024-06-13 17:58 UTC, Piras314 commented on Resources/Prototypes/GameRules/events.yml
not fixed

2024-06-13 18:59 UTC, jorgun commented
now everything shud be in place

2024-06-18 02:57 UTC, Aidenkrz commented
Closing this as it appears that this is being added to upstream, https://github.com/space-wizards/space-station-14/pull/19460.

2024-06-18 02:57 UTC, closed without merging