Cryo/Bluespace syringe buff
Goob-Station/Goob-Station pull request #257
Opened 2024-06-09 08:34 UTC by a-person5660

## About the PR
minor buff to cryo and bluespace syringes.

## Why / Balance
have you ever seen a cryo syringe used ever? they are literally pointless right now, this buff makes it so they are slightly better than regular syringes for capacity and gives them a faster injection speed. they are now a complete upgrade to normal syringes, considering they are behind a T2 civ tech i think this is acceptable.
improved syringes will help a lot when med is overwhelmed and it still requires science to do their job, research civ and make the syringes for med.
i may have overdone the injection speed, if you feel i have then let me know and i will change it.

## Media
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl: 
- buffed cryo syringe to 20u capacity
- buffed cryo syringe to inject about three times as fast
- buffed bluespace syringe to inject around three times as fast (might revert)

2024-06-09 08:36 UTC, a-person5660 commented on Resources/Prototypes/Entities/Objects/Specific/chemistry.yml
> +    delay: 0.5
in retrospect this might be too much but bluespace syringes are already rare af anyway.

2024-06-09 08:46 UTC, a-person5660 commented on Resources/Prototypes/Entities/Objects/Specific/chemistry.yml
> +    delay: 0.5
tested it and it was in fact too much, also changed the cryo syringe to be a bit slower too.

2024-06-09 19:48 UTC, jorgun commented
and all changes inside of pre existing scripts/yaml should include a comment, in this format # GoobStation - *reason for this code addition/change*

else it looks good

2024-06-10 16:26 UTC, a-person5660 commented
does everyone agree with the specific stat change? im not sure about upping the volume so much, maybe 20u.

2024-06-10 19:36 UTC, Piras314 approved these changes
looks good 👍

2024-06-10 19:37 UTC, Piras314 requested changes
You need to mark these as goobstation changes following the guidelines: all changes inside of pre existing scripts/yaml should include a comment, in this format # GoobStation - *reason for this code addition/change*

2024-06-10 19:43 UTC, a-person5660 reviewed
# GoobStation - reason for this code addition/change
to give cryo syringes a use.

2024-06-10 19:46 UTC, a-person5660 commented on Resources/Prototypes/Entities/Objects/Specific/chemistry.yml
> +    delay: 2
# GoobStation - reason for this code addition/change
buffing bluespace syringe becuase they are underused and rarely found, it should be a more interesting and useful item that provides a good advantage to the medical team when aquired.

2024-06-10 19:46 UTC, a-person5660 commented on Resources/Prototypes/Entities/Objects/Specific/chemistry.yml
> +  description: An improved syringe used to contain chemicals or solutions without reactions.
# GoobStation - reason for this code addition/change
updating the description to specify that this syringe is an upgrade to normal syringes

2024-06-10 19:47 UTC, Piras314 commented
no I mean literally change the code please

2024-06-10 19:48 UTC, a-person5660 commented
remember, i am literally stupid and have no idea what im doing.

2024-06-10 19:49 UTC, a-person5660 commented
nvm, i figured it out.

2024-06-10 19:55 UTC, Piras314 requested changes
Please add the goobstation comment to line 409, 438 and 445

2024-06-10 19:57 UTC, a-person5660 commented
fifth times the charm!

2024-06-10 19:57 UTC, Piras314 approved these changes
looks good to me

2024-06-11 20:02 UTC, merged