Immovable Rod QOL update
Goob-Station/Goob-Station pull request #258
Opened 2024-06-10 14:30 UTC by jorgun

## About the PR

adds new sprite to immovable rod
tewak immovable rod sprite probabilitys

## Why / Balance

lack of flying toilets in space

## Technical details

added fyuing toiltet to space,  probability 90% on imovable rod event
changeed base rod from 95% probability to 5%

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

- tweak:  immovable rod QOL

2024-06-11 15:08 UTC, Piras314 requested changes
Need to move some changes, look at my full review for more info

2024-06-11 15:08 UTC, Piras314 commented on Resources/Prototypes/Entities/Objects/Fun/immovable_rod.yml
This needs to be in Resources/Prototypes/Goobstation/Entities/Objects/Fun/immovable_rod.yml please! Looks hilarious though.

2024-06-11 15:08 UTC, Piras314 commented on Resources/Prototypes/Entities/Objects/Fun/immovable_rod.yml
> +  description: skibidi dub dub yes yes
skibidi DOB DOB yes yes, not DUB DUB yes yes

2024-06-11 15:08 UTC, Piras314 commented on Resources/Prototypes/GameRules/events.yml
These changes are fine here, looks good

2024-06-13 19:22 UTC, jorgun commented on Resources/Prototypes/Entities/Objects/Fun/immovable_rod.yml
moved

2024-06-13 21:38 UTC, Piras314 approved these changes

2024-06-13 21:38 UTC, Piras314 commented on Resources/Prototypes/Goobstation/Entities/objects/Fun/immovable_rod.yml
no need for #goobstation comment if it's in a Gooobstation folder, but it's not a problem at all

2024-06-17 18:00 UTC, Piras314 approved these changes

2024-06-19 14:08 UTC, merged