Clothing Reintergration Patch / Addions
Goob-Station/Goob-Station pull request #267
Opened 2024-06-12 01:36 UTC by Neptune-Zvezda

Oh God oh fuck this is so many files
Uh, assuming i didnt fuck it up all Socks have been readded all previously made ones. updated their spawn locations for each requisite job locker, vendrobe and dresser. I have also set the socks to have winter protection like the winter boots have.

 i have added a Personal Winter Coat with the standard winter coat stats.

Besides some yaml limiter errors from the kira outfit everything should just work off the bat

## About the PR
Preadded Texture files and YML files for previously integrated sock clothing, as well as Adding them to most expected spawns.
addionally added Kira's Danny phantom admin only outfit which is purely for use with admin ghost and his personal events
Lastly, added a custom winter coat for myself to the winterdrobe

## Why / Balance
The biggest balance change I can see with this is from the thermal insulation the socks now provide which can possibly reduce the effect a gas fire has on the station population in its lifespan

## Technical details

No adjustments to code functions have been added or changed
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

Non Pizza with left beef
**Changelog**

Readied Socks!

- Add: Kira is stalking you while you erp
- Add: Erp Socks!
- Fix: Socks actually spawn in places now

2024-06-12 14:47 UTC, Piras314 requested changes
Missing files + Goobstation folder structure see review below 👇

2024-06-12 14:47 UTC, Piras314 commented on Resources/Prototypes/Catalog/Cargo/cargo_fun.yml
Move this to Resources/Prototypes/Goobstation/Catalog/Cargo/cargo_fun.yml

If you are making new prototypes, you put them in a Goobstation folder
If you're editing existing prototypes, you put them in the existing file with a comment saying it's from goobstation and why it exists / the pr it's from e.g. # Goobstation - Clothing reintegration

2024-06-12 14:47 UTC, Piras314 commented on Resources/Prototypes/Catalog/Jukebox/Standard.yml
These audio files don't seem to exist, and should be put in Resources/Audio/Goobstation/Jukebox/ if you choose to add them. If you add the audio files to fix this instead of removing this, please remove the "hmeister" from the names as well.

2024-06-12 14:49 UTC, Piras314 commented on Resources/Prototypes/Catalog/Cargo/cargo_fun.yml
Btw, you need to put that comment above all the changes you made outside of Goobstation folders. (Obviously not on every single line, but on the first line of the changes, and if there are multiple changes separated by a bunch of lines, put it at the top of each contiguous block of code changes)

2024-06-12 16:49 UTC, Piras314 requested changes
needs goobstation comments, folder changes for audio and removal of hmeister from song names. you're already aware of the problems with the socks so I didn't comment on them here, check out my comments below 👇

2024-06-12 16:49 UTC, Piras314 commented on Resources/Audio/Jukebox/StraussII-Blue_Danube_Waltz.ogg
convert this to ogg.

2024-06-12 16:49 UTC, Piras314 commented on Resources/Audio/Jukebox/attributions.yml
> +  copyright: "Only God and the internet knows, and im keeping it that way."
you told me this was temporary as a joke GUH

2024-06-12 16:49 UTC, Piras314 commented on Resources/Audio/Jukebox/A_Good_Man_Is_Hard_to_Find.ogg
Move this to Resources/Audio/Goobstation/Jukebox

2024-06-12 16:49 UTC, Piras314 commented on Resources/Audio/Jukebox/A_Good_Man_Is_Hard_to_Find.ogg
move all of the jukebox audios there

2024-06-12 16:49 UTC, Piras314 commented on Resources/Prototypes/Catalog/Fills/Lockers/dressers.yml
add # Goobstation - Clothing reintegration comments pls

2024-06-12 16:49 UTC, Piras314 commented on Resources/Prototypes/Catalog/Fills/Lockers/medical.yml
more goobstation comments needed here

2024-06-12 16:49 UTC, Piras314 commented on Resources/Prototypes/Catalog/Fills/Lockers/misc.yml
ok yeah theres a lot of goobstation comments needed, ill not mark every single file that needs it since thatll just take a long time

2024-06-12 16:49 UTC, Piras314 commented on Resources/Prototypes/Catalog/Jukebox/Standard.yml
remove hmeister and set them to /Audio/Jukebox/Goobstation/

2024-06-17 16:04 UTC, Piras314 approved these changes
Assuming this is all working and tested in-game, seems good to me.

2024-06-17 16:06 UTC, Piras314 commented
One thing though, your changelog is in the wrong format and not great, please replace it with this:

```
:cl:
- add: More thigh-high socks and other Goobstation clothing have been added!
- add: A few more Jukebox songs have been added.

2024-06-18 11:30 UTC, Piras314 commented
RAAAAH MERGE CONFLICTS @Neptune-Zvezda

2024-06-18 11:31 UTC, Piras314 commented
Merge conflicts @Neptune-Zvezda

2024-07-13 19:00 UTC, Aidenkrz requested changes
Main issue with this is the sock prototypes/RSIs.

2024-07-17 15:20 UTC, Neptune-Zvezda commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/secdrobe.yml
> +    ClothingHeadHatCowboyBlack: 1
to reply to this, since its more complicated
during some previous version it claimed that these were in the secdrobe and causing a confliction
I made this change using github directly as i didnt understand why it was giving the comfliction
Removing now as it clearly wont happen now

2024-07-17 15:21 UTC, Neptune-Zvezda commented on Resources/Audio/Jukebox/attributions.yml
> +  source: "https://soundcloud.com/pigeonbeans/sunset"
Song Removed from Pr  whined at piras to make their own damn pr

2024-07-17 15:33 UTC, Neptune-Zvezda commented on Resources/Prototypes/Goobstation/Entities/Clothing/OuterClothing/Nparka.yml
> +  id: NParka
Renamed to Parka_Nep

2024-07-17 15:34 UTC, Neptune-Zvezda commented on Resources/Prototypes/Goobstation/Entities/Clothing/Under/under.yml
> +- type: entity
When you train me

2024-07-17 16:30 UTC, Piras314 commented
Read checks

2024-07-19 01:02 UTC, Piras314 commented
check the checks @Neptune-Zvezda

2024-07-19 16:09 UTC, Piras314 approved these changes

2024-07-19 16:09 UTC, Piras314 commented
perhaps it's finally time to put this saga to an end

2024-07-20 12:52 UTC, Aidenkrz commented
> I've stated my issue with this many times before but it was not seen I guess.
> The sock sprites are insanely redundant and add too much bloat to the files. At bare minimum you should've made it all in one RSI, but you need to change it so it has two sprites for the base layers of the socks that can be recolored in the prototypes and extra layers over the top of that for sec boots, bunny slippers, etc.
> > When you train me

You marked this conversation resolved when you didn't actually resolve any of the issues with it. This is my main issue with the PR and it won't be merged until this is changed.

2024-08-05 23:13 UTC, jorgun commented
for the socks make a pure white png of the socks for base and a pure white of just the stripes.

  components:
  - type: Sprite
    sprite: Goobstation/Objects/socks.rsi
    layers:
      - state: SocksBase
      - color: pink
      - state: SocksStripe
        color: teal

2024-08-10 21:38 UTC, Aidenkrz commented
Can be reopened when this is being worked on again.

2024-08-10 21:38 UTC, closed without merging