Moderate Rev Changes + Weight Change
Goob-Station/Goob-Station pull request #276
Opened 2024-06-15 16:08 UTC by TooSillyFennec

## About the PR
Changes revs to make them funner and more balanced. 6 Changes are included: New Kit (Recharge Flash (3 Charges 180 recharge), Synd shades and synd enc key), Sci Flash nerf (2 > 1 Charge), 4 Headrevs, Midround revs (Max 3, 30 Players per headrev 1.5 weight), 2018 TG Rev icons and revs/survival chances are swapped (10% Revs, 5% Surv)

Also my 1st PR so... yeah.

## Why / Balance
New Kit - Recharge Flash nerfs blitz and buffs stealth, makes the start slower, paces revs better and makes converting decently often more important. shades grant sechud and chameleon over the old ones, preventing 2 pretty bad scenarios (Not gonna flash someone shielded, and prevents "OMG Sunglasses!!!") and the enc key lets headrevs coordinate. Plan a strategy TOGETHER! For once. 

Robo Flash Nerf - Pretty blatant. Nerfs the cancer strategy of the ol' mech fab pretty heavily. Also helps lower converts in a bag at one time along with the above.

4 Headrevs - To balance the other nerfs and make headrevs better at higher pops, adding a 4th Headrev may help. They probably convert the same amount of revs as an old 3 headrev team considering the starting converts at 4 new headrevs are 12 compared to old 3 headrevs at 15. Still stronger than the old 3 headrevs, but revs lose pretty often. More headrevs more chance for competence! Also, 9 command staff compared to 7 on a den server already made command stronger than normal.

Midround Revs - They are much weaker than a normal revolt with normally half the revs for the player count. Zombs have also been lowered to 1.5. They can start spawning 10m earlier than zombs to offset the much higher time to get ready than zombs. All in all, less likely to turbofuck the round compared to zombs and adds some more flavor to rounds, especially survival. (Also helps prevent "We already have synds!!!" when headrevs are called!)

2018 TG icons - Why did the Rev PR use the old ones? These have been in 13 for 6 years, holy fuck! they look cooler at least. Made larger at 10x10 to make them more visible, and cooler. And all antag icons probably should be larger than they are to be honest.

Weight Changes - People want more revs, survival's totally ass and needs to be rarer to be funner to be honest. Pretty easy change, and it's somewhat of a compromise between the old weights on both goob and den and the current. 

## Technical details
No C#

## Media

Besides the ss13 icons that you can go and see, everything changes gameplay by balance. Midround headrevs work the exact same as sleepers and outbreak and probably don't need to be shown off. No extra features for that compared to sleepers either.

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl:
- add: Midround revs can spawn rarely, at 1 Headrev per 30 players and a max of 3. Don't piss the workers off next time!
- tweak: Headrevs now start with a 3-Charge, Recharging flash, Chameleon sec glasses, and an encryption key to talk with your fellow leaders. Coordinate, Comrades!
- tweak: 4 Headrevs can now spawn for more freedom fighting fun!
- tweak: Revs now roll at a 10% chance, and Survival at 5%!
- tweak: Science Flashes have been nerfed to 1 Charge. Maybe kill security or command for the real deal?

2024-06-15 16:10 UTC, TooSillyFennec commented
Also i moderately goofed while making the texture changes so... yeah, 10+ commits from my goof.

2024-06-15 17:55 UTC, Piras314 approved these changes
Looks good. I assume the rechargeDuration of 180 is in seconds.

2024-06-15 18:30 UTC, Aidenkrz commented
Looks good other than you should attempt to comment all lines you change with # Goobstation, and the new gamerule should be in a new yml inside of /Prototypes/Goobstation/GameRules

2024-06-16 01:11 UTC, Piras314 requested changes
goobstation file structure and commit standards must be followed, look at durk's comment

2024-06-16 02:07 UTC, TooSillyFennec commented
Added comments and moved the rev yml to goobstation.

Do i need to change anything else?

2024-06-16 04:57 UTC, TooSillyFennec commented
Also moved the gamerule, sorry forgot about that.

2024-06-16 12:03 UTC, TooSillyFennec commented
Realised i made oopsies, they have been unfucked and everything's now # Goobstation commented or under Prototypes/Goobstation.

2024-06-16 13:47 UTC, Piras314 requested changes
balance changes needed

2024-06-16 13:47 UTC, Piras314 commented on Resources/Prototypes/Entities/Objects/Weapons/security.yml
I don't think making sciflashes 1 charge is a good move considering they need them for shadow anomalies.

2024-06-16 13:47 UTC, Piras314 commented on Resources/Prototypes/GameRules/roundstart.yml
I recommend you take this down to 3 again and make sciflashes 2 charges to balance it out.

2024-06-16 14:43 UTC, TooSillyFennec commented on Resources/Prototypes/Entities/Objects/Weapons/security.yml
Okay then, gonna make them cost more to make however (and probably less in the vendor also)

2024-06-16 14:43 UTC, TooSillyFennec commented on Resources/Prototypes/GameRules/roundstart.yml
Okay, gonna lower to 3 max.

2024-06-16 14:57 UTC, TooSillyFennec commented on Resources/Prototypes/Entities/Objects/Weapons/security.yml
yeah, forgot about those.

2024-06-16 15:11 UTC, TooSillyFennec commented on Resources/Prototypes/Entities/Objects/Weapons/security.yml
is that okay at 300/500/300 and borg exo's cheaper by 300 to balance borg prices okay?

Could also do the opposite and go 50/100/50 and keep 1 charge sciflashes, matters on your opinion really.

2024-06-16 15:36 UTC, TooSillyFennec commented on Resources/Prototypes/Entities/Objects/Weapons/security.yml
Actually, probably gonna lower that to 200/400/200

2024-06-16 16:35 UTC, misandrie requested changes
This addition will only make sec gameplay even worse. Security on goobstation on average is understaffed and/or underskilled - throwing more shit at them while already a typical round ends up in a security Bloons TD gameplay with hos holding down security with a laser rifle even without revolutionaries is a significantly unfun idea.

This doesn't pass for admeme gamerule either as we have revolutionaires already as that.

2024-06-16 16:35 UTC, misandrie commented on Resources/Prototypes/Roles/Antags/revolutionary.yml
> +    - EncryptionKeySyndie # Goobstation
This will rat out nuclear operatives or other syndicates, either directly by headrevs trying to cause a distraction or, more likely, just gifting the encryption key to security for almost free.

2024-06-16 16:35 UTC, misandrie commented on Resources/Prototypes/Goobstation/GameRules/ProvokedRevolt.yml
> +        prototype: HeadRev
This creates 3 headrevs when server is at 90 players, this **doesn't reduce** the amount of headrevs or make them weaker if the server is not lowpop. Max amount of headrevs is equivalent to the roundstart rule.

2024-06-16 17:17 UTC, TooSillyFennec commented on Resources/Prototypes/Goobstation/GameRules/ProvokedRevolt.yml
> +        prototype: HeadRev
Headrevs was increased to 4 at one point, can lower to 2 max here.

2024-06-16 17:26 UTC, TooSillyFennec commented on Resources/Prototypes/Roles/Antags/revolutionary.yml
> +    - EncryptionKeySyndie # Goobstation
Pretty low amount of natural scenarios where there are both ops and revs/agents and revs/all three right now, and freelance is used for admemes. Adding a new frequency definitely would be needed for a dynamic implementation, but there are few changes are needed there anyways for almost every antag so probably not the PR to add that.

Also, pretty easy fix for caught by sec: "COMMS COMPROMiSED!!!" - didn't use the key? Probably never even opened the bag in the first place besides for the flash and would already be an absolute trash headrev that ruins the game even before now. The pros for revs to me seems to outweigh the one con they have. And having the chance to strategise probably makes them funner too.

Only my opinion though, stuff can change.

2024-06-16 21:54 UTC, misandrie commented
Additionally make sure this doesnt fire during revs

2024-06-17 02:41 UTC, TooSillyFennec commented
> Additionally make sure this doesnt fire during proper revs

Don't know how to do that exactly, any tips to make that well, work? Pretty sure no other event does the same so I'm not exactly sure how. (Only reason outbreak never happens on zombs is those rounds being too short for example- very very rarely happens on ops too, but only seen that happen twice when they had a higher weight on lowpop stealth op rounds back like a year ago on den) But, if that doesn't exist yet at all, i can just set the weight lower/start later or both. Don't know how I'd code for a check for that- but don't mind any help for that.

(Definitely gonna add a Max Occurrences of 1 to prevent survival from barfing out a 4 headrev or even 6 headrev game after long enough however)

2024-06-17 02:59 UTC, TooSillyFennec commented on Resources/Prototypes/Roles/Antags/revolutionary.yml
> +    - EncryptionKeySyndie # Goobstation
Can actually remove the Synd key from provocateurs to prevent some of the more likely natural scenarios,

2024-06-17 11:37 UTC, misandrie approved these changes

2024-06-17 11:41 UTC, misandrie commented on Resources/Prototypes/Roles/Antags/revolutionary.yml
> +  id: ProvacateurGear
```suggestion
  id: ProvocateurGear
```

2024-06-17 13:21 UTC, TooSillyFennec commented on Resources/Prototypes/Roles/Antags/revolutionary.yml
> +  id: ProvacateurGear
typo moment

2024-06-17 15:39 UTC, Piras314 requested changes
A few more changes requested.

2024-06-17 15:39 UTC, Piras314 commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/robotics.yml
> +    SciFlash: 2
Add # Goobstation - Rev changes to the end of this line.

2024-06-17 15:39 UTC, Piras314 commented on Resources/Prototypes/Recipes/Lathes/robotics.yml
Add ```# Goobstation - Rev changes``` to the line before ```Glass: 200``

2024-06-17 15:39 UTC, Piras314 commented on Resources/Prototypes/Roles/Antags/revolutionary.yml
Please just put ```# Goobstation - Rev changes``` above line 21 and above line 25, no need to put them on every line (which wasn't even fully done).

Roundstart headrevs having syndicate comms and provocateurs not having them seems good to me though.

2024-06-17 15:39 UTC, Piras314 commented on Resources/Textures/Interface/Misc/job_icons.rsi/HeadRevolutionary.png
Move this to Resources/Textures/Goobstation/Interface/Misc/job_icons.rsi/HeadRevolutionary.png please.

2024-06-17 15:39 UTC, Piras314 commented on Resources/Textures/Interface/Misc/job_icons.rsi/Revolutionary.png
Move this to Resources/Textures/Goobstation/Interface/Misc/job_icons.rsi/Revolutionary.png please.

2024-06-17 16:59 UTC, TooSillyFennec commented
can do all of that.

2024-06-17 18:39 UTC, Aidenkrz commented
Actually, revert your commits that changed the file location of the rev icon texture. Any texture changes of preexisting prototypes should stay in their original folder.

2024-06-18 06:14 UTC, TooSillyFennec commented
New rev icons are too large to work, gonna revert to the old ones.

Also apparently synd shades are totally broken, totally odd they worked a month ago or so. Gonna make them normal sec glasses.

2024-06-18 06:56 UTC, TooSillyFennec commented
PR's TOTALLY fucked- No matter what, the rev component doesn't work at all.

Fuck.

Gonna close and make a new PR that only adds the synd key and secret weights, something went REALLY wrong with the PR somehow. Tested by the way, any flash doesn't work.

2024-06-18 06:56 UTC, closed without merging