Ntr rloadout
Goob-Station/Goob-Station pull request #323
Opened 2024-06-18 09:06 UTC by Teapug

i swear if github deletes this im going to jump out a window

2024-06-18 10:17 UTC, Teapug commented
alsol added a jumpskirt for NTR

2024-06-18 10:27 UTC, Aidenkrz approved these changes
This all looks good, now you just have to do the same for blueshield :trollface:

2024-06-18 11:23 UTC, Piras314 requested changes
ID naming format changes required to fit PascalCase. @Teapug

2024-06-18 11:23 UTC, Piras314 commented on Resources/Prototypes/Goobstation/Entities/Clothing/Uniforms/jumpskirts.yml
> +  id: Centcom_agentSkirt
You make this mistake in a lot of places, but this needs to be CentcomAgentSkirt, not Centcom_agentSkirt. Look through the rest of your code and make it all PascalCase.

2024-06-18 11:23 UTC, Piras314 commented on Resources/Prototypes/Goobstation/Loadouts/Jobs/Command/nanotrasen_representative.yml
Same thing all through this.

2024-06-18 11:23 UTC, Piras314 commented on Resources/Prototypes/Goobstation/Loadouts/loadout_groups.yml
Here too

2024-06-18 11:23 UTC, Piras314 commented on Resources/Prototypes/Goobstation/Loadouts/role_loadouts.yml
And here

2024-06-18 11:23 UTC, Piras314 commented on Resources/Textures/Goobstation/Clothing/Uniforms/Jumpskirt/centcom_agent.rsi/equipped-INNERCLOTHING.png
sprite naming format is good

2024-06-18 11:42 UTC, Teapug commented
> ID naming format changes required to fit PascalCase. @Teapug

Made requested changes

2024-06-18 11:44 UTC, Piras314 approved these changes
If you send a screenshot of this working in-game it's good to merge

2024-06-18 11:48 UTC, Teapug commented
> If you send a screenshot of this working in-game it's good to merge

Small problem, i dont have enough ram to host a server... Could someone else test it?

2024-06-19 06:43 UTC, Aidenkrz commented
All is good here now, in the future we also need to move the startinggear out of the pockets and into the backpack, but this is fine for now.

2024-06-19 06:44 UTC, merged