adding duathread armour
Goob-Station/Goob-Station pull request #333
Opened 2024-06-19 07:31 UTC by a-person5660

## About the PR
added durathread armour

## Why / Balance
contributes towards the completion of  #304

## Media
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
🆑 
- add: durathread armour

2024-06-19 10:42 UTC, a-person5660 commented
this should be working, it is building on my end. im not sure whats causing it.

2024-06-19 13:07 UTC, a-person5660 commented
it should be good to merge now

2024-06-19 13:13 UTC, Aidenkrz requested changes
Move the latherecipes into goobstation, then this should be good 👍

2024-06-19 13:13 UTC, Aidenkrz commented on Resources/Prototypes/Recipes/Lathes/clothing.yml
> +- type: latheRecipe # Goobstation - adding durathread armoured clothing
this should be in its own file in /goobstation/

2024-06-20 00:48 UTC, a-person5660 commented
now it should be good to merge

2024-06-20 03:35 UTC, merged