Better Supermatter (real)
Goob-Station/Goob-Station pull request #344
Opened 2024-06-21 11:46 UTC by whateverusername0

## About the PR

Massively refactored SupermatterSystem because in my opinion it looked knda stinky. Made it look more readable and eye appealing :3
- Supermatter now shoots lightning bolts depending on the amount of power it currently has.
- Is able to delaminate into a tesla.
- Starts dormant round-start. To activate it, you need to throw anything at it, or, basically, make it collide with something.
- Makes global announcements whether it's delamming or not, changes station code to whatever if delaminating, which is ofc reversible if there are crazy engineers who will prevent, or at least contain the delam.
- And it now shows integrity when examined within an appropriate range.

Added new objective - cut off a sliver from the supermatter crystal. Basically you have to use a knife or whatever's sharp on the SM crystal, (which will activate it, if it was dormant), stand still for 30 seconds, and run away with a highly radioactive piece of the supermatter. This will greatly damage the SM and alert the crew with a massive fucking announcement stating that "SOMEONE HAS TAMPERED WITH SM ENGINEERS GET HIS ASS!!"

Added some placeholders for cascade resonance delamination type if nobilium ever gets added or smh else comes up on my mind.

## Why / Balance

because i fucking love supermatter and because i can

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## TODO
- [ ] Playtest and bug fix.

**Changelog**

:cl:
- add: Supermatter now shoots out lightning bolts.
- add: You will now have to activate the SM by making it collide with anything.
- add: Supermatter Tesla Delamination.

2024-06-21 15:13 UTC, misandrie requested changes
Offer these changes to the [upstream where the code is ported from](https://github.com/Simple-Station/Einstein-Engines/pull/341) for better scrutiny

Not really going into the unneccesary variable name changes (they were explicit for a reason).

2024-06-21 15:13 UTC, misandrie commented on Resources/Prototypes/Goobstation/Entities/Objects/Misc/supermatter_sliver.yml
> +      intensity: 3.5
While sure, makes sense - this requires a container to mask both of these components - else you're sentencing a would-be thief to be in a rad suit the moment he picks up the sliver

2024-06-21 15:13 UTC, misandrie commented on Content.Server/Goobstation/Supermatter/Systems/SupermatterSystem.cs
>          }
If you're doing "customSender" - don't make it "Central Command" if true, that's not really *custom*.
make customSender a nullable string and use null-coalescing.

2024-06-21 15:13 UTC, misandrie commented on Content.Server/Goobstation/Supermatter/Systems/SupermatterSystem.cs
> +        }
Delay this, SM/Engi is getting swarmed immediately as this is announced.

2024-06-21 15:13 UTC, misandrie commented on Content.Server/Goobstation/Supermatter/Systems/SupermatterSystem.cs
> +        ///     The supermatter is picky. Help the SM pick it's last song of death.
Ambigious comment

2024-06-21 17:16 UTC, VMSolidus commented
Hey uhh, as this code's maintainer and current codeowner, I'd appreciate it if you brought your changes to the Einstein Engines Upstream where this system is being maintained(and is licensed from). It would be for the betterment of all servers that use our Supermatter Engines if improvements to the code were made more wide reaching. I'm actually completely willing to work with you directly on making these changes directly to the base code, and ensuring that this code is in the best state it can be for its eventual release to the game. Here's the link to where I have the code currently. I think most of your changes are actually great, especially in adding the traitor objective, optional tesla delamination, and improving the delamination logic in general, but I also have even further improvements planned that I'd love to see implemented. For example I want to have hotloaded CVars affecting the delamination logic, so that a server host can optionally override the delamination type to force a specific kind of event to happen, or a boolean that bypasses the checking logic and forces a "Random-Any" delamination regardless of the conditions leading up to it. 

https://github.com/Simple-Station/Einstein-Engines/pull/341

2024-06-21 18:27 UTC, whateverusername0 commented on Content.Server/Goobstation/Supermatter/Systems/SupermatterSystem.cs
> +        }
> Delay this, SM/Engi is getting swarmed immediately as this is announced.

i honestly dunno how

2024-06-21 18:30 UTC, whateverusername0 commented
> Hey uhh, as this code's maintainer and current codeowner, I'd appreciate it if you brought your changes to the Einstein Engines Upstream where this system is being maintained(and is licensed from).

sure. do i just make a PR on your branch?

2024-06-22 12:45 UTC, Aidenkrz requested changes
Mary has already stated most of the issues with this, fix em up and fix the checks, otherwise this looks good.

2024-06-22 13:03 UTC, whateverusername0 commented on Content.Server/Goobstation/Supermatter/Systems/SupermatterSystem.cs
> +        ///     The supermatter is picky. Help the SM pick it's last song of death.
lrp comment now

2024-06-22 13:04 UTC, whateverusername0 commented on Content.Server/Goobstation/Supermatter/Systems/SupermatterSystem.cs
> +        }
upped the difficulty to be on the nuke disk level

2024-06-22 13:04 UTC, whateverusername0 commented on Content.Server/Goobstation/Supermatter/Systems/SupermatterSystem.cs
>          }
done

2024-06-22 13:35 UTC, Aidenkrz approved these changes

2024-06-22 13:35 UTC, merged

2024-06-22 17:31 UTC, CatMagic1 commented
What the fuck when did we start getting real coders

2024-06-22 18:34 UTC, misandrie commented
Don't worry about it