adding ame parts to cargo order cataloge
Goob-Station/Goob-Station pull request #364
Opened 2024-06-25 22:55 UTC by jorgun

## About the PR

adding ame to cargos cataloge

## Why / Balance

some stations have to small ame and changes to ame repairs means ame can become unsuable,
and in response to https://discord.com/channels/1202734573247795300/1254686636994859078
## Technical details

crates for ameparts and ame controller already existed, just added them to cargos order and set a price

## Media

![image](https://github.com/Goob-Station/Goob-Station/assets/2734131/8a91635f-dd43-4a30-a0ce-9d6a77ea674f)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: cargo can order ame parts

2024-06-27 15:04 UTC, Piras314 requested changes
Please make it come as a flatpak instead of a full AME shielding/part please.

2024-06-28 14:42 UTC, jorgun commented
> Please make it come as a flatpak instead of a full AME shielding/part please.

the parts are flatpacked, its the same crate that are on some stations.
the controller is not flatpacked but comes inside a crate.
you want the controller flatpacked?

2024-07-03 10:55 UTC, Piras314 approved these changes

2024-07-08 01:44 UTC, Aidenkrz commented
Don't really like this. I agree with wizden that AME is not meant to be a permanent power source, allowing people to get more parts for it encourages relying on it.

2024-07-08 01:44 UTC, closed without merging