Revert shit changes wizden changes, add a few closed/reverted changes. And minor buffs
Goob-Station/Goob-Station pull request #382
Opened 2024-07-07 15:27 UTC by Hmeister-real

## About the PR
Ion storm Racism
RD hardsuit is fireproof + somewhat laser proof
all Nukie hardsuits are fireproof.
Elite Hardsuit slowdown removed. Back to full speed (god i hate wizden maintainers ideas of """balance""")
Arti portals are 120 seconds again
Bananium is Radioactive again
Disabler SMG buff
caps sword reflect minor buff
Nicotine gives you a little bit of cancer

## Why / Balance
is nice. Discussed with discord and people think its 👍 

## Technical details

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: Hmeister
- tweak: RD hardsuit is fireproof and somewhat laser proof
- tweak: all Nukie hardsuits are fireproof
- tweak: Elite Hardsuit slowdown removed
- tweak: Disabler SMG is buffed
- tweak: caps sword reflect minor buff
- tweak: Added back racial Ion Laws to borgs
- add: Nicotine gives you a little bit of cancer
- add: Artifact portals now last 120 seconds again
- add: Bananium is Radioactive again

2024-07-07 16:42 UTC, misandrie requested changes
Incredible amounts of power creep - author seems to have died to a fire extinguisher meme some time in the past

2024-07-07 16:42 UTC, misandrie commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +      - Energy
why

2024-07-07 16:42 UTC, misandrie commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +    reduction: 0.8
why

2024-07-07 16:42 UTC, misandrie commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +    reduction: 0.8
BHRS has heat reduction of 50%.

2024-07-07 16:42 UTC, misandrie commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +    reduction: 0.8
Ditto

2024-07-07 16:46 UTC, Hmeister-real commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +    reduction: 0.8
that makes it immune to fire, not immune to lasers and such

2024-07-07 16:46 UTC, Hmeister-real commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +    reduction: 0.8
that makes it immune to fire, not immune to lasers and such

2024-07-07 16:46 UTC, Hmeister-real commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +    reduction: 0.8
that makes it immune to fire, not immune to lasers and such

2024-07-07 16:46 UTC, Hmeister-real commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +      - Energy
Old PR i made a while ago that got closed related to the hardsuit size nerf. give a reason why not

2024-07-07 16:51 UTC, misandrie commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +      - Energy
You're giving RD or anyone wearing his suit an innate 55% chance to deflect lasers which is unaffected by movement speed.

2024-07-07 16:51 UTC, misandrie commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +    reduction: 0.8
This allows operatives to plasflood at little to no hard to themselves.

2024-07-07 16:56 UTC, Hmeister-real commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +      - Energy
it's experimental, and it stopped being experimental on upstream when they made it far harder to carry

2024-07-07 16:57 UTC, Hmeister-real commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +    reduction: 0.8
Yes, but science tends to use plasma to do Artis, and this would let the RD survive that. Also the atmos firesuit+hardsuit does the exact same thing except its easier to get and doesnt make you valid if you aren't pretending to be the RD

2024-07-07 17:01 UTC, misandrie commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +      - Energy
This doesnt excuse it being superior to having an esword out just because

2024-07-07 17:03 UTC, misandrie commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +    reduction: 0.8
> Yes, but science tends to use plasma to do Artis, and this would let the RD survive a flood, also the Fire anomaly exists. 

Dying is part of the game, this isn't a reason to allow RD to be careless with artifacts and anomalies. The explosion resistance does not forgive mishandling of dangerous artifacts for example.

> Also the atmos firesuit+hardsuit does the exact same thing except its easier to get

They have major speed penalties and glow innately for no real resistances.

2024-07-07 17:06 UTC, Hmeister-real commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +    reduction: 0.8
without this though, its just a space safe bomb suit

2024-07-07 17:21 UTC, misandrie commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +    reduction: 0.8
as it should? RD shouldn't be superman

2024-07-07 17:49 UTC, misandrie commented
I cant even fight over review resolution without maintainer buttons its so over

2024-07-07 19:43 UTC, Verbalase commented
> Incredible amounts of power creep - author seems to have died to a fire extinguisher meme some time in the past

chat, bro may be onto something

2024-07-07 20:05 UTC, Hmeister-real commented
if you want i can remove the reflection. but this will hurt my ego drastically...

2024-07-07 20:24 UTC, misandrie requested changes
Still no good argument as to why affected hardsuits should be virtually immune to fire

2024-07-07 20:46 UTC, Hmeister-real commented
> Still no good argument as to why affected hardsuit should be virtually immune to fire

Plasma artis, Fire Anomaly, the fact it's experimental and meant to be explosion resistant, It has no real advantage over other hardsuits and no real quirk (it used to have a small carry size, but that got removed), if the CE and Atmosia get it, why not the Head Scientist who works with Atmosia on occasion?

2024-07-07 20:48 UTC, misandrie commented
> > Still no good argument as to why affected hardsuit should be virtually immune to fire
> 
> Plasma artis, Fire Anomaly, the fact it's experimental and meant to be explosion resistant, It has no real advantage over other hardsuits and no real quirk (it used to have a small carry size, but that got removed), if the CE and Atmosia get it, why not the Head Scientist who works with Atmosia on occasion?

The suit shouldn't compensate or outright negate bad handling decisions on behalf of RD. This is without mentioning syndicate hardsuits, which are also virtually immune for no reason or cost increase.

2024-07-07 22:21 UTC, Hmeister-real commented
Got anything ideas to make it special then?

2024-07-07 22:28 UTC, misandrie commented
> > This is without mentioning syndicate hardsuits, which are also virtually immune for no reason or cost increase.
> 
> Got suggested to add it back to the nukie hardsuits so that they dont die to plasma fires anymore, and because it was removed needlessly by upstream. they used to have fireproofing

Crew-caused plasma fires during ops is an administrative issue

2024-07-07 22:46 UTC, Hmeister-real commented
RD hardsuit is currently just, a hardsuit but worse except for with explosions, it's gotta have something. If its such a big problem i can move it to another PR so that this one can be merged, since past the RD suit and Nukie suit changes you're complaining about, this is all fine from what i've been told

2024-07-07 22:49 UTC, misandrie commented
> RD hardsuit is currently just, a hardsuit but worse except for with explosions, it's gotta have something.

It has explosion resistance

> Also it's a Syndicate operative combat hardsuit. Its designed to be resistant to stuff, thats why it has 50% reduction in everything. It makes sense for it to be fireproof

Being in literal fire is not combat last I've checked

2024-07-07 23:18 UTC, whateverusername0 commented
gem, merge now

2024-07-07 23:24 UTC, Hmeister-real commented
> Being in literal fire is not combat

ok, you got me there. In real life, if you are in a fight, you wont usually get set aflame. However, this is FUTURE SPACE TECH STATION 14, where the geneva conventions only a suggestion, and random passengers have more arms and explosives than a  security officer

2024-07-07 23:26 UTC, misandrie commented
> FUTURE SPACE TECH STATION 14

No fully automated luxury gay space communism for this to be accurate.
Being in fire is still not really combat.

> random passengers have more arms and explosives than a security officer

This is an administration issue.

2024-07-07 23:29 UTC, Hmeister-real commented
im going to explode you with my mind

2024-07-07 23:33 UTC, misandrie commented
> im going to explode you with my mind

@Verbalase help admin abuse ban he

2024-07-07 23:36 UTC, misandrie commented
Actually he didn't code that feature in nvm

2024-07-07 23:52 UTC, GreyMario commented
no

2024-07-07 23:53 UTC, misandrie commented
no

2024-07-08 01:41 UTC, Aidenkrz commented
this fucking sucks ass 

> Arti portals are 120 seconds again
> Bananium is Radioactive again

are the only ones I would even thing of allowing.

2024-07-08 01:41 UTC, closed without merging

2024-07-08 01:47 UTC, Verbalase commented
> > im going to explode you with my mind
> 
> @Verbalase help admin abuse ban he

bro thinks im the all knower of coding

2024-07-08 08:23 UTC, Hmeister-real commented
> this fucking sucks ass

Bruh i got suggested this shit by people on the discord. Blame them. I can remove the fluff from this PR just give me a bit

2024-07-08 08:37 UTC, Hmeister-real commented
Il make a new pr soon with just
Ion storm Racism
Elite Hardsuit slowdown removed
Arti portals are 120 seconds again
Bananium is Radioactive again

2024-07-08 09:40 UTC, misandrie commented
> > this fucking sucks ass
> 
> Bruh i got suggested this shit by people on the discord. Blame them. I can remove the fluff from this PR just give me a bit

https://github.com/Goob-Station/Goob-Station/assets/109166122/8447946b-1efb-4576-9cac-96099d9cbef5