fire( )axe/desword reversal
Goob-Station/Goob-Station pull request #383
Opened 2024-07-07 17:06 UTC by Ilya246

## About the PR
- syndicate uplink now has: desword for 100 TC, fire axe for 50 TC, both for syndies and nukies (old pricing)
- *fireaxe* (not fire axe) specifically now pries plating like it used to (credit to https://github.com/space-wizards/space-station-14/pull/28845)
- nukie reinf pricing is back to 80 TC (equivalent to old reinf pricing)

## Why / Balance
fix wizden balance and readd fun

## Media

compiled and tested trust

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: The fire axe and desword are now purchasable in the uplink.
- add: The atmos fireaxe can now pry plating.
- tweak: Nukie reinforcements are back to 80 TC.

2024-07-07 17:07 UTC, misandrie commented
> nukie reinf pricing is back to 80 TC (equivalent to old reinf pricing)

Nukie reinf was re-priced to match tg pricing, but has forgotten that nukie reinf spawns with the hardsuit preequipped. What about giving nukie reinf the hardsuit instead.

2024-07-07 17:09 UTC, Ilya246 commented
> > nukie reinf pricing is back to 80 TC (equivalent to old reinf pricing)
> 
> Nukie reinf was re-priced to match tg pricing, but has forgotten that nukie reinf spawns with the hardsuit preequipped. What about giving nukie reinf the hardsuit instead.

so you mean 24 wiz-TC but comes with hardsuit? i think no-suit 16 TC is better since it encourages more variety in equipment and usage of different hardsuits

2024-07-07 17:11 UTC, misandrie commented
> > > nukie reinf pricing is back to 80 TC (equivalent to old reinf pricing)
> > 
> > 
> > Nukie reinf was re-priced to match tg pricing, but has forgotten that nukie reinf spawns with the hardsuit preequipped. What about giving nukie reinf the hardsuit instead.
> 
> so you mean 24 wiz-TC but comes with hardsuit? i think no-suit 16 TC is better since it encourages more variety in equipment and usage of different hardsuits

Sort of a tradeoff - if you want a pair of extra hands AND an elite/jugg - you'll pay double.
The advantage a (semi-)competent extra player provides is often undervalued, and giving said extra player flexibility in terms of loadout unbalances things imho.

2024-07-07 17:13 UTC, Ilya246 commented
> Sort of a tradeoff - if you want a pair of extra hands AND an elite/jugg - you'll pay double.
The advantage a (semi-)competent extra player provides is often undervalued, and giving said extra player flexibility in terms of loadout unbalances things imho.

will do that if i get another similar opinion

2024-07-07 17:14 UTC, jorgun commented
i agree, nukie reinforsment shud come whit same gear as nuke and a operator name

2024-07-07 17:14 UTC, misandrie commented
![image](https://github.com/Goob-Station/Goob-Station/assets/109166122/c038e5f7-b0a7-4171-b11b-e69f6b6b20c3)
Hivemind

2024-07-07 17:15 UTC, Ilya246 commented
> i agree, nukie reinforsment shud come whit same gear as nuke and a operator name

might be a good idea, will give them operator names

2024-07-07 17:47 UTC, misandrie approved these changes
Millions must buy new jetpacks

2024-07-07 17:48 UTC, Ilya246 commented
updated, description updated to reflect new changes

2024-07-07 22:49 UTC, whateverusername0 commented
pure gem, merge now

2024-07-08 01:38 UTC, Aidenkrz requested changes
all good besides the fact 90% of this should be inside the goobstation folder or have comments

2024-07-08 01:38 UTC, Aidenkrz commented on Resources/Locale/en-US/ghost/roles/ghost-role-component.ftl
> +ghost-role-information-nukie-reinforcement-name = Nuclear Operative
move this into /Goobstation/ghost/ghost-role-component.ftl

2024-07-08 01:38 UTC, Aidenkrz commented on Resources/Locale/en-US/store/uplink-catalog.ftl
> +uplink-operative-radio-name = Nuclear Operative Teleporter
move this into /Goobstation/store/upling-catalog.ftl

2024-07-08 01:38 UTC, Aidenkrz commented on Resources/Locale/en-US/tools/tool-qualities.ftl
> +tool-quality-axing-name = Axing
Same as above....

2024-07-08 01:38 UTC, Aidenkrz commented on Resources/Prototypes/Catalog/uplink_catalog.yml
> +- type: listing
Goobstation folder!!!

2024-07-08 01:38 UTC, Aidenkrz commented on Resources/Prototypes/Catalog/uplink_catalog.yml
> +- type: listing
Goobstation folder!!!

2024-07-08 01:38 UTC, Aidenkrz commented on Resources/Prototypes/Catalog/uplink_catalog.yml
> +  name: uplink-operative-radio-name
add a comment to indicate this was changed for goobstation

2024-07-08 01:38 UTC, Aidenkrz commented on Resources/Prototypes/Entities/Mobs/Player/human.yml
> +    - type: RandomMetadata
add a comment to indicate this was changed for goobstation

2024-07-08 01:38 UTC, Aidenkrz commented on Resources/Prototypes/Entities/Objects/Devices/Syndicate_Gadgets/reinforcement_teleporter.yml
> +  - type: GhostRole
add a comment to indicate this was changed for goobstation

2024-07-08 01:38 UTC, Aidenkrz commented on Resources/Prototypes/Entities/Objects/Weapons/Melee/fireaxe.yml
> +  - type: Tool
add a comment to indicate this was changed for goobstation

2024-07-08 01:38 UTC, Aidenkrz commented on Resources/Prototypes/Roles/Antags/nukeops.yml
>  - type: startingGear
instead of changing this, put this into goobstation folder and leave this default

2024-07-08 01:38 UTC, Aidenkrz commented on Resources/Prototypes/tool_qualities.yml
> +- type: tool
goobstation folder!!!!!!!!!!!!!!!!!!

2024-07-08 01:38 UTC, Aidenkrz commented on Resources/Prototypes/Tiles/plating.yml
> +  deconstructTools: [ Axing ]
# goobstation - allow to be pryable by fire axe
add comment like this to all of these

2024-07-08 08:02 UTC, Ilya246 commented
done, fixed in accordance with review, reviewed the whole diff, and tested, nukeop reinfs now also start with a normal toy carp in their pocket instead of uplink

2024-07-08 09:58 UTC, GitHubUser53123 commented
desword removal was justified, i dont wanna see it return imo

2024-07-08 10:31 UTC, Ilya246 commented
> desword removal was justified, i dont wanna see it return imo

i've done a poll on discord and so far it seems people are in favor of having it returned
besides, if it does end up causing more problems than it's worth, we can just re-remove it

2024-07-09 02:12 UTC, Aidenkrz approved these changes

2024-07-09 02:13 UTC, merged

2024-07-18 15:16 UTC, GitHubUser53123 commented
![image](https://github.com/user-attachments/assets/bd414e06-4215-4b18-8c7e-f0340704a653)
![image](https://github.com/user-attachments/assets/df6c1206-28fb-4dad-a843-3e499e0e37d9)

2024-07-18 17:54 UTC, Piras314 commented
post the vote counts you had 4 options

2024-07-26 04:50 UTC, GitHubUser53123 commented
>post the vote counts you had 4 options
>post vote counts
i didn't screenshot it so it remains a mystery ig. but i'll tell you that it was a distinct difference, not something like 12/11 votes.