Ling gamemode
Goob-Station/Goob-Station pull request #385
Opened 2024-07-08 10:13 UTC by whateverusername0

## About the PR

my sorry ass forgot about it

:cl:
- add: Changeling gamemode

2024-07-08 10:53 UTC, jorgun commented
need a to edit /prototypes/secret_weigth.yml if you want it to be a part of secret
and i sugest you make a "traitor + ling"  game mode

2024-07-08 11:00 UTC, whateverusername0 commented
> need a to edit /prototypes/secret_weigth.yml if you want it to be a part of secret and i sugest you make a "traitor + ling" game mode

sure

2024-07-08 11:43 UTC, whateverusername0 commented
ok great merge now ⚡ !!

2024-07-08 21:49 UTC, Piras314 commented
I get that it's going to be a playtest but those percentages are kind of ridiculous... Maybe remove the percentages and keep the gamerule so it's admin-only, it'll probably be done 50% of rounds anyway lol.

2024-07-09 01:29 UTC, a-person5660 commented
what do you think the percentages should be?

2024-07-09 02:28 UTC, whateverusername0 commented
> I get that it's going to be a playtest but those percentages are kind of ridiculous... Maybe remove the percentages and keep the gamerule so it's admin-only, it'll probably be done 50% of rounds anyway lol.

> what do you think the percentages should be?

what do you think the percentages should be?

2024-07-09 02:29 UTC, a-person5660 commented
still need to fix chem regen :trollface:

2024-07-09 02:29 UTC, a-person5660 commented
> > I get that it's going to be a playtest but those percentages are kind of ridiculous... Maybe remove the percentages and keep the gamerule so it's admin-only, it'll probably be done 50% of rounds anyway lol.
> 
> > what do you think the percentages should be?
> 
> what do you think the percentages should be?

piras said in the discord to make it zero and admins will run the mode until its stable.

2024-07-09 02:44 UTC, whateverusername0 commented
![image](https://github.com/Goob-Station/Goob-Station/assets/113782077/86dc1b9e-072f-498a-a2ad-1fe05f2263b0)
test failed because of some unfathomable reason idk MERGE NOW :zap:

2024-07-09 02:47 UTC, a-person5660 commented
> ![image](https://private-user-images.githubusercontent.com/113782077/346782216-86dc1b9e-072f-498a-a2ad-1fe05f2263b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0OTM1MTIsIm5iZiI6MTcyMDQ5MzIxMiwicGF0aCI6Ii8xMTM3ODIwNzcvMzQ2NzgyMjE2LTg2ZGMxYjllLTA3MmYtNDk4YS1hMmFkLTFmZTA1ZjIyNjNiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQwMjQ2NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NmI4Y2NhYTE3MjM0MTY3YjIyNjRhMWQ4N2Q4YmQ1MjMyYzJlZjAyZjcxMTJhM2Q3NjU0MTY2YTgzNzYwMWI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jboy6alaPpn4Lej4-JSE7CH_q0jytLrbHlGp8z0_HWw) test failed because of some unfathomable reason idk MERGE NOW ⚡

bro still didnt remove lings from secret, smh my head.

2024-07-09 02:48 UTC, whateverusername0 commented
> bro still didnt remove lings from secret, smh my head.

i did remove it from secret weights???

2024-07-09 02:54 UTC, a-person5660 commented
mb, read wrong commit :trollface:

2024-07-09 07:47 UTC, misandrie commented
Shrieks need a greater cooldown and extend to all shrieks.
Fleshmend should work only when stationary.
Fleshmend shouldnt work when dead.
Regenerative stasis should demand you wait 60 seconds at least before reviving.
Amount of lings per X amount of crew should be scaled down. Role is centered around round removal and each ling starts turning 30 pop into 8 pop consistently.

2024-07-09 08:01 UTC, whateverusername0 commented
> Shrieks need a greater cooldown and extend to all shrieks.

upped it to 10 seconds

> Fleshmend should work only when stationary.

can't do that but i've upped it's cooldown to 30 seconds and made it inject some imperdrezene for slowdown (to make up for the effect of flesh mending)

> Fleshmend shouldnt work when dead.

done

> Regenerative stasis should demand you wait 60 seconds at least before reviving.

i'll just up it's entry chemical cost to 75 :trollface: 

> Amount of lings per X amount of crew should be scaled down. Role is centered around round removal and each ling starts turning 30 pop into 8 pop consistently.

sure. made it 15 people to 1 ling, like headrevs, also changed max amount of lings from 8 to 6

2024-07-09 13:57 UTC, whateverusername0 commented
ok now stasis sets your chems to 0 on entry
and exiting stasis now costs 60 chems. you have to wait a full minute to exit it now, and perhaps wait a little extra if you wanna use an ability afterwards

2024-07-09 14:05 UTC, misandrie commented
The issue was that a ling could just get up from a dead state immediately twice at full health, this solves it

2024-07-09 23:41 UTC, Piras314 requested changes

2024-07-09 23:41 UTC, Piras314 commented on Resources/Prototypes/game_presets.yml
> +
Put everything under this line into Resources/Prototypes/Goobstation/game_presets.yml

2024-07-10 00:31 UTC, whateverusername0 commented on Resources/Prototypes/game_presets.yml
> +
done

2024-07-12 19:03 UTC, Piras314 commented on Content.Shared/Goobstation/Changeling/ChangelingComponent.cs
> +    //public static bool operator ==(TransformData one, TransformData two)
It hurts my soul you aren't using multiline comments here lmao.

2024-07-12 19:03 UTC, Piras314 approved these changes

2024-07-13 00:58 UTC, whateverusername0 commented on Content.Shared/Goobstation/Changeling/ChangelingComponent.cs
> +    //public static bool operator ==(TransformData one, TransformData two)
😭 i removed it temporarily

2024-07-13 08:23 UTC, Aidenkrz commented on Resources/Locale/en-US/Goobstation/changeling/abilities/changeling.ftl
> +changeling-sting-fail-simplemob = You can't sting a simplemob with that!
???

2024-07-13 08:24 UTC, whateverusername0 commented on Resources/Locale/en-US/Goobstation/changeling/abilities/changeling.ftl
> +changeling-sting-fail-simplemob = You can't sting a simplemob with that!
simplemob being a mouse
how else can i name it?

2024-07-13 09:00 UTC, misandrie commented on Resources/Locale/en-US/Goobstation/changeling/abilities/changeling.ftl
> +changeling-sting-fail-simplemob = You can't sting a simplemob with that!
lower being

2024-07-13 09:15 UTC, Aidenkrz commented on Resources/Locale/en-US/Goobstation/changeling/abilities/changeling.ftl
> +changeling-sting-fail-simplemob = You can't sting a simplemob with that!
i know what a simplemob is, it just shouldn't say it to the player. change it to say the targets name or lesser/lower being like mary said

2024-07-13 14:12 UTC, CatMagic1 commented
Where is the pixel fix

2024-07-13 16:20 UTC, whateverusername0 commented
![image](https://github.com/user-attachments/assets/22892209-0b9d-417a-9d53-8f4c463f84df)
extra funny

2024-07-13 18:42 UTC, merged

2024-11-24 19:48 UTC, TurboTrackerss14 commented
Your cowardice in adding a blacklist to traitor role selection, meaning traitorling is not possible, has been logged under "cringe". 
(I know I am late I only just noticed the blacklist and am upset at your cowardice)

2024-11-24 22:48 UTC, misandrie commented
Good