More minor, less powerceep changing wizden reverts
Goob-Station/Goob-Station pull request #386
Opened 2024-07-08 12:33 UTC by Hmeister-real

## About the PR
 Smaller version of #382
Ion storm Racism
Elite Hardsuit slowdown removed
Arti portals are 120 seconds again
Bananium is Radioactive again

## Why / Balance
good balance. 
## Technical details
Racism bit is a joke, it just allows for Ion laws to focus on a specific type of crewmember for those who cant read the code.

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: Hmeister
- tweak: Ion storms can now focus on specific species
- tweak: Elite Hardsuit nerf reverted
- tweak: Artifact portals last 120 seconds again
- tweak: Bananium is Radioactive again

2024-07-08 16:29 UTC, Hmeister-real commented
no clue why it failed

2024-07-08 21:42 UTC, Piras314 requested changes
No ion storm racism.

2024-07-09 00:08 UTC, Hmeister-real commented
> No ion storm racism.

But, but, i want borgs to be funny...

2024-07-09 02:22 UTC, Aidenkrz requested changes

2024-07-09 02:22 UTC, Aidenkrz commented on Resources/Prototypes/Datasets/ion_storm.yml
> +  - FURRIES # debating if i should add this, even though its funny
its funny but people will get butthurt

2024-07-09 02:22 UTC, Aidenkrz commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +    sprintModifier: 1.0
still dont think i really agree with this, maybe make it 0.95

2024-07-09 06:16 UTC, lanse12 commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +    sprintModifier: 1.0
![image](https://github.com/Goob-Station/Goob-Station/assets/174656070/1d87d5d1-59b5-496b-bd26-f4ad57a35aa1)

2024-07-09 23:22 UTC, Hmeister-real commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +    sprintModifier: 1.0
they are the second like probably lol

2024-07-09 23:23 UTC, Hmeister-real commented on Resources/Prototypes/Datasets/ion_storm.yml
> +  - FURRIES # debating if i should add this, even though its funny
We shall see, if they do we can remove it

2024-07-09 23:25 UTC, Hmeister-real commented
im actually going to stand for the Ion law race laws because they allow for funny outcomes like "All Harpys are now cool" or something. I want it test merged and if people complain il make a PR removing them

2024-07-09 23:43 UTC, Piras314 commented
People have complained about them, that's why they were removed from wizden, you can read the "Remove racism" PR on wizden to find out more. 

TLDR: It literally gives borgs laws that tell them to violate the rules.

2024-07-09 23:55 UTC, misandrie requested changes
Instead of pressing 4 buttons to revert try replicating tg/para's BHRS which allowed you to toggle between EVA (10% slowdown) and combat (no slowdown, no eva) modes.

Have  fun

2024-07-10 11:26 UTC, Hmeister-real commented
> Instead of pressing 4 buttons to revert try replicating tg/para's BHRS which allowed you to toggle between EVA (10% slowdown) and combat (no slowdown, no eva) modes.
> 
> Have fun

idk how to actually code. I just do very basic stuff

2024-07-11 10:09 UTC, JoeHammad1844 commented
> im actually going to stand for the Ion law race laws because they allow for funny outcomes like "All Harpys are now cool" or something. I want it test merged and if people complain il make a PR removing them

agreed, nothing wrong with a little species based humor

2024-07-12 18:54 UTC, Piras314 commented
This isn't getting merged if you don't remove specism/racism

2024-07-12 18:56 UTC, misandrie commented
> This isn't getting merged if you don't remove specism/racism

Changes generally are cring

2024-07-12 19:01 UTC, misandrie commented
also guy presses "resolve conversation" himself after replying once lol lmao

2024-07-12 21:41 UTC, Verbalase commented
> also guy presses "resolve conversation" himself after replying once and doing nothing lol lmao

which one is it, is it “lol”, or perhaps “lmao”

**anyway murderbone borg law!?!?!?!?!?**

2024-07-13 08:25 UTC, Aidenkrz commented
no intention to make requested changes, closing for now

2024-07-13 08:25 UTC, closed without merging