Syndicate Rebalancing + Gun rebalancing
Goob-Station/Goob-Station pull request #394
Opened 2024-07-13 13:58 UTC by TooSillyFennec

## About the PR
Major price changes on underused items and some general rebalance for synd gear and guns

## Why / Balance

only the gear changes are mentioned here. Price changes can be discussed if there are any changes/reasons wanted.

Cane Blade Reworked - The Cane blade's now 40 TC, but a sidegrade to e-sword. Less than an e-sword DPS at 24 DPS, but 1.5 hit speed and now ignites as a reference to the fact SS13 curators are related to wizards in some ways. Current Cane Blade was well pretty... bad and overpriced.

Synd EVA Reworked - Synd EVA now is closer to the SS13 Syndicate spacesuit- AKA a low defense EVA suit. also made it have 0 slow. Cost changed to 20 TC. - Why? Because you can get the same thing for 0 TC without the valid when it has the same stats as the normal EVA, and having a lighter EVA yet still armored option rounds things out.  25% Combat types means the suit gives 1-2 hits of extra survivability. 50% Rads to add an extra reason to buy one, aka the goose is loose :3

Fake insuls buff - By Buff I mean insta-crit. The effort required to 1: Shock someone w/ them 2: have them be alone or no non-antags are w/ them and 3: Hide the body before they can be found is insane. Also very target dependant and may need thief gloves, so 10/30 TC for a niche situational kill needs to well... actually work! 

China Lake Nerf - 1.0 FR > 0.6 FR. it's a grenade launcher that's an aoe insta death. 0.6 FR makes shots need a lot more thought. The skill weapon needs actual skill not just "Click pixel this far away, girl!!!"

Hristov Changes - Hristovs now deal  deal 60 AP Damage and 90 Structural. They also have 6 Ammo Capacity. Price has been heavily increased from 60 TC to 110 TC. Boxes now have 12 .60 and are 40 TC. FR is actually 0.8 instead of 0.75. This makes them an actual weapon.

Revolver Changes - All normal Revolvers except mateba have recieved a 0.5 FR increase. AKA - inspector 2.0, Deckard/Python 2.5.

.35 Pistol Buff - 10 > 12 Capacity. Pistols have more ammo than you'd think, and this makes them somewhat closer to 13 pistol balance, but not the exact 2 kills for every normal mag the synd makarov if every shot landed on 13.

Shotgun Rebalance - DB's now fire fast as a sawn off to emulate the lack of cycling till someone fixes the near year old den fuck up. Kammerer Cap 4 > 6, makes them have 3 perfect kills a mag on buckshot. other weapons have 4, so making the gun closer makes it less... shit. Closer to the 8 shots 13 has too. Also slugs actually crit in 3 hits now, wowsers.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Clearance Sale! A high amount of items that haven't sold well have been made cheaper by the syndicate. However, Suppliers have increased prices on certain items.
- tweak: The Cane blade has been totally rebalanced, dealing more damage and igniting targets, but has been marked up in price to 40 TC.
- tweak: using better conductive fibers, The sneaky conductive gloves now send someone to crit.
- tweak: The old Syndicate EVA Suit has been replaced by a new lightweight durathread model, with some moderate protection and anti-rad but costs 20 TC. Reviewers have stated that it's insanely comfy, but these have been bought, NT claims.
- tweak: The China Lakes in supply  have started to deprecate and fire slower due to age. 1 FR > 0.6 FR.
- tweak: The Syndicate has realised they were sending .40 Materiel instead of .60 Antimateriel. This has been rectified recently and the hristov improved. The correct ammo is very costly! 40 Damage > 60 Damage AP, Hristov 60 TC > 110 TC.
- tweak: Revolvers across the galaxy have had their firerates magically increased after one girl decided "Hey, maybe we should invest more money into the revolver department!" 1.5 > 2.0 FR for Inspector, 2.0 > 2.5 FR for Deckard and Python.
- tweak: .35 Auto Pistol Capacity 10 > 12
- tweak: The Kammerer has had a bit more space carved out, to contain up to 6 Shells. Slug Shells now deal 45 Damage as well, making them a more desirable option!

2024-07-13 14:16 UTC, CatMagic1 commented
This is all great.

2024-07-13 14:21 UTC, lanse12 commented
how could you do this to me... nerfing my china lake...

2024-07-13 14:34 UTC, Piras314 requested changes

2024-07-13 14:34 UTC, Piras314 commented on Resources/Prototypes/Catalog/uplink_catalog.yml
> +    Telecrystal: 110 # increase price by a lot when the thing has a scope
It has a scope now???????

2024-07-13 14:34 UTC, Piras314 commented on Resources/Prototypes/Catalog/uplink_catalog.yml
> +    Telecrystal: 40 # 2 ammo capacity worth
Why are you nerfing the worst and least used weapon in the game, the sniper

2024-07-13 14:34 UTC, Piras314 commented on Resources/Prototypes/Catalog/uplink_catalog.yml
> +  catergories:
categories, not catergories

2024-07-13 14:34 UTC, Piras314 commented on Resources/Prototypes/Catalog/uplink_catalog.yml
> +    Telecrystal: 8 # Why ever buy a 20 TC fake over a 20 TC real deal?
The carp suit works as a hardsuit that you can eat and drink and everything like that out of, it's actually really good, put this back to 20 or at least 15

2024-07-13 14:34 UTC, Piras314 commented on Resources/Prototypes/Entities/Clothing/Hands/colored.yml
> +    coefficient: 10 # if you pull a shock off and they are alone and can never be found, a kill's deserved. *BZZT!!!* - Goobstation
no

2024-07-13 14:34 UTC, Piras314 commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/antimateriel.yml
> +        Piercing: 60
structural damage doesn't actually work on people other than like, borgs right? if so this is fine, even at the unmodified price

2024-07-13 14:34 UTC, Piras314 commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/shotgun.yml
> +        Piercing: 45 # Goobstation - Don't really have to cycle them here, so a moderate nerf over 13 makes sense... not 28 damage what the actual fuck was that?
40 or 35

2024-07-13 14:34 UTC, Piras314 commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Shotguns/shotguns.yml
> +    fireRate: 4 # until cycling works, this works to simulate the fact a DB doesn't need to pump- and also removes sawn off powergame yayyyy :3 - Goobstation
sawn off SHOULD be faster

2024-07-13 14:34 UTC, Piras314 commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Shotguns/shotguns.yml
> +    capacity: 6 # Goobstation
hell no

2024-07-13 14:35 UTC, Piras314 commented on Resources/Prototypes/Catalog/uplink_catalog.yml
> +    Telecrystal: 40 # 2 ammo capacity worth
this is actually fair

2024-07-13 14:35 UTC, Piras314 commented on Resources/Prototypes/Catalog/uplink_catalog.yml
> +    Telecrystal: 110 # increase price by a lot when the thing has a scope
12 is fine even with the buff

2024-07-13 14:36 UTC, TooSillyFennec commented on Resources/Prototypes/Catalog/uplink_catalog.yml
> +    Telecrystal: 110 # increase price by a lot when the thing has a scope
the ammo does 60 AP now- that was a comment for when the thing has one, not what's in the PR.

2024-07-13 14:36 UTC, TooSillyFennec commented on Resources/Prototypes/Catalog/uplink_catalog.yml
> +    Telecrystal: 40 # 2 ammo capacity worth
The ammo's buffed, and that's 2 capacity worth

2024-07-13 14:36 UTC, TooSillyFennec commented on Resources/Prototypes/Catalog/uplink_catalog.yml
> +  catergories:
yeah, fixed that, me made oopsie

2024-07-13 14:42 UTC, TooSillyFennec commented
fuck damn it accidentally made a review :/

2024-07-13 14:42 UTC, Piras314 commented on Resources/Prototypes/Catalog/uplink_catalog.yml
> +    Telecrystal: 110 # increase price by a lot when the thing has a scope
110 is absolutely insane still, agents start with 100 and should be able to buy it, with its low fire rate and high cost of ammo

2024-07-13 14:43 UTC, Piras314 commented on Resources/Prototypes/Catalog/uplink_catalog.yml
> +    Telecrystal: 110 # increase price by a lot when the thing has a scope
80tc maybe

2024-07-13 15:01 UTC, Piras314 commented on Resources/Prototypes/Catalog/uplink_catalog.yml
> +    Telecrystal: 8 # Why ever buy a 20 TC fake over a 20 TC real deal?
@TooSillyFennec

2024-07-13 15:07 UTC, Piras314 approved these changes

2024-07-13 15:08 UTC, Piras314 commented
No merge for a few days for player / contributor feedback

2024-07-13 15:47 UTC, misandrie commented on Resources/Prototypes/Entities/Objects/Weapons/Melee/cane.yml
> +    fireStacks: 1
Congratulations you have created a portable incinerator

2024-07-13 15:47 UTC, misandrie commented on Resources/Prototypes/Goobstation/Entities/Clothing/OuterClothing/softsuits.yml
> +        Radiation: 0.5
>25% flat resists on brute plus 50% res on rads for zero movement penalty

2024-07-13 16:06 UTC, Piras314 commented on Resources/Prototypes/Goobstation/Entities/Clothing/OuterClothing/softsuits.yml
> +        Radiation: 0.5
ZERO MOVEMENT PENALTY? oh hell no I didn't realise, this should have like 5% resists then, 10 max

2024-07-13 16:45 UTC, lanse12 commented on Resources/Prototypes/Catalog/uplink_catalog.yml
> +    Telecrystal: 8 # Why ever buy a 20 TC fake over a 20 TC real deal?
there's two one is fake one is real

2024-07-13 17:11 UTC, misandrie commented on Resources/Prototypes/Goobstation/Entities/Clothing/OuterClothing/softsuits.yml
> +        Radiation: 0.5
Piras314 approved these changes 2 hours ago

2024-07-13 18:41 UTC, Aidenkrz commented
Genuinely one of the only good balance PRs that's been made here, handle the two reviews above and this looks good.

2024-07-13 18:46 UTC, Piras314 commented on Resources/Prototypes/Entities/Objects/Weapons/Melee/cane.yml
> +    fireStacks: 1
yeah it should be lowered if possible

2024-07-14 04:17 UTC, Verbalase commented
chat there might be a decent pr (no idea)

2024-07-14 08:06 UTC, JoeHammad1844 commented
that penetration mechanic that was denied in wizden would be cool. where the hristov could shoot through walls

2024-07-14 08:14 UTC, TooSillyFennec commented
I fixed a recent den fuck up that made tots have less objectives. old tot objs always overshot to above 5, rarely above 6 diff and they removed that. well that causes 2 objective tots. Best way to emulate the weight overshoot? increase the weight to where it would overshoot, 6.

Why did den not do this? _We all know why._

2024-07-14 08:30 UTC, misandrie commented
Diff 6 usually ended up in objectives which were tantamount to murdering the entire station.

It is been capped for a reason.

2024-07-14 08:37 UTC, TooSillyFennec commented
> Diff 6 usually ended up in objectives which were tantamount to murdering the entire station.
> 
> It is been capped for a reason.

Current Diff is 5, and den fixed the overflow that caused that. overflow actually caused synds to have 6 diff pretty regularly on 5. Basically, keeps the overflow fix but makes objs roll closer to how they used to.

2024-07-14 09:36 UTC, TooSillyFennec commented
![objs](https://github.com/user-attachments/assets/e20d9fbf-41e7-4863-8835-e598275c1444)

There's an example. Also many cases of obj sets that can't be gotten anymore, like 2 steal objectives.

2024-07-14 09:52 UTC, misandrie commented
Steal objectives are more often than not kill objectives with extra steps due to average command staff behavior and how the game functions in general.

2024-07-14 09:57 UTC, TooSillyFennec commented
> Steal objectives are more often than not kill objectives with extra steps due to average command staff behavior and how the game functions in general.

True, but what I'm trying to say is the game generates less than before and the bug that caused problems at 6 has been removed... and also caused less objectives. Can revert if the less objs is wanted, but I presumed otherwise.

2024-07-14 10:10 UTC, misandrie commented
> > Steal objectives are more often than not kill objectives with extra steps due to average command staff behavior and how the game functions in general.
> 
> True, but what I'm trying to say is the game generates less than before and the bug that caused problems at 6 has been removed... and also caused less objectives. Can revert if the less objs is wanted, but I presumed otherwise.

Needs maintainer or third party opinion on this.

2024-07-14 10:26 UTC, packmore commented
> I fixed a recent den fuck up that made tots have less objectives. old tot objs always overshot to above 5, rarely above 6 diff and they removed that. well that causes 2 objective tots. Best way to emulate the weight overshoot? increase the weight to where it would overshoot, 6.
> 
> Why did den not do this? _We all know why._

i think this should be moved to a different PR, personally. especially because this PR has no mention of the change in its description. it almost feels misleading having that be snuck into this PR.

2024-07-14 12:56 UTC, TooSillyFennec commented
> > I fixed a recent den fuck up that made tots have less objectives. old tot objs always overshot to above 5, rarely above 6 diff and they removed that. well that causes 2 objective tots. Best way to emulate the weight overshoot? increase the weight to where it would overshoot, 6.
> > Why did den not do this? _We all know why._
> 
> i think this should be moved to a different PR, personally. especially because this PR has no mention of the change in its description. it almost feels misleading having that be snuck into this PR.

Yeah, honestly discussion is needed and this PR's not the place for that. Also, this was an attempt at reverting the _effect_ of the den change without reverting the bug fix. Personally though player selection might be the way to go, but again not the PR for that

2024-07-14 13:14 UTC, TooSillyFennec commented
Made an issue for that type of thing, otherwise I'm probably not gonna touch that within this PR or the next few really.

2024-07-14 20:33 UTC, Piras314 approved these changes

2024-07-14 20:33 UTC, merged