Dual Antag Gamemodes, Calm Variants of game rules, and changeling delay matches traitor
Goob-Station/Goob-Station pull request #412
Opened 2024-07-17 09:45 UTC by TooSillyFennec

## About the PR
Title :3

## Why / Balance
Changeling Delay - Same reason as agents, and also better for dual antag games for them to match. And changing the delay only for the Calm variants used in dual antag games would blatantly get meta'd.

Calm Variants - 1.5x Player ratio variants that need 30+ Ready. Needed for dual antags to actually be balanced, but also an admin tool. All At once, Calm, no zombies anyone??? - This is sarcasm, all at once sucks :3

Weight Changes - These are very minor, but 2% from traitors and nukies went to Changeling. Remember, Traitorling exists, so 8% out of Changeling became Traitorling. otherwise, the chance for revs in a game with dual antags included stays the same, and survival/zombies still exist at 5%. 1/3 of games with ops now have either lings or traitors with an equal 3% chance each, and 1/5 of rev games now have lings or traitors with an equal 1% chance each. Yeah, it's that small. Rev games kinda benefit from other antags, but currently I think they should be rare with the current state of well... all antags, really.

Also, some key things:

50% of games include Traitors with 30+ Ready

28% of games include Changelings with 30+ Ready.

67% of games with 30+ Ready don't have major antags- AKA Revs, Zombs or ops. 

under 30+ Ready due to how the game works, all dual antag games become traitor whether they had them or not, which really is a good thing at that pop level, as lower pop's better with less major antags, and changeling's honestly less fun with only 1-2 Changelings and actually is more destructive at lower pops as they commonly have a pretty lacking sec/command count.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- add: Added gamemodes to secret with two antags at once, but have less of one type and need 30+ Players ready to start. 
- tweak: Weights have been slightly tweaked. ops are slightly rarer, and only traitor or only changeling games are slightly rarer, but both antags appear in more games due to two antag gamemodes being added.
- tweak: Changeling now rolls with the same delay as traitors.

2024-07-17 09:49 UTC, a-person5660 commented
Coated PR

2024-07-17 10:01 UTC, whateverusername0 commented
the duality of antag

2024-07-17 10:03 UTC, whateverusername0 commented
love these secret weights
now what if we add enother orundstart antag like cult, ratvar cult, heretics and other shit?
how many gamemodes do you wish to add? :trollface: 
srsly we need dynamic

2024-07-17 10:03 UTC, a-person5660 commented
I'm 90% sure the check fail isn't because of this

2024-07-17 10:04 UTC, whateverusername0 commented
mfw air consistency test fails
who farted

2024-07-17 10:04 UTC, a-person5660 commented
> srsly we need dynamic

That's a job for wizden :trollface:

2024-07-17 10:43 UTC, TooSillyFennec commented
> love these secret weights now what if we add enother orundstart antag like cult, ratvar cult, heretics and other shit? how many gamemodes do you wish to add? :trollface: srsly we need dynamic

Pretty correct, but at the current antag level it's not needed **yet.**

By the time wizards are done and piras finishes cult? we really do need dynamic to make antag chances for certain antags not fucking once in a lifetime and allow extra antags to be added after. 0.05 Revs was already personally at least hell, imagine 0.04 wizard and then adding an extra antag.

Yeah, probably good to make a dynamic issue when we have at least one of those.

2024-07-17 13:17 UTC, Piras314 requested changes
the weight numbers hurt my eyes

2024-07-17 13:17 UTC, Piras314 commented on Resources/Prototypes/Goobstation/GameRules/roundstart.yml
> +      max: 2
max should be 1

2024-07-17 13:17 UTC, Piras314 commented on Resources/Prototypes/Goobstation/GameRules/roundstart.yml
> +      max: 6
out of the scope of this PR maybe but this should be 3 or 4

2024-07-17 13:17 UTC, Piras314 commented on Resources/Prototypes/Goobstation/game_presets.yml
> +    - SubGamemodesRule
no subgamemodes (thieves)

2024-07-17 13:17 UTC, Piras314 commented on Resources/Prototypes/Goobstation/game_presets.yml
> +    - SubGamemodesRule
no subgamemodes (thieves)

2024-07-17 13:17 UTC, Piras314 commented on Resources/Prototypes/Goobstation/game_presets.yml
> +    - SubGamemodesRule
no subgamemodes (thieves)

2024-07-17 13:18 UTC, Piras314 commented on Resources/Prototypes/secret_weights.yml
> +    Traitor: 0.38 # Goobstation
rethinking this

2024-07-17 13:22 UTC, Piras314 commented on Resources/Prototypes/secret_weights.yml
> +    Traitor: 0.38 # Goobstation
traitor 40 (total 43)
cling 10 (total 17)
tatorling 5
nukeops 20 (total 22)
nuketraitor 1
nukeling 1
revolutionary 10 (total 13)
revtraitor 2
revling 1
zombie 5
survival 5

2024-07-18 01:58 UTC, a-person5660 commented on Resources/Prototypes/secret_weights.yml
> +    Traitor: 0.38 # Goobstation
Zombie chance is too high imo, it's the worst mode, should be 1%.

2024-07-18 13:16 UTC, Piras314 requested changes

2024-07-18 13:16 UTC, Piras314 commented on Resources/Locale/en-US/Goobstation/game-ticking/game-presets/presets-dualantag.ftl
> +revtraitor-description = A revolution have been provoked by a member of the Syndicate, but not every agent got the hint...
I know this is minor but the main point of my correction was you said "have been provoked" when it should be "has been provoked" @TooSillyFennec other than that this is good I think

2024-07-18 13:26 UTC, TooSillyFennec commented on Resources/Locale/en-US/Goobstation/game-ticking/game-presets/presets-dualantag.ftl
> +revtraitor-description = A revolution have been provoked by a member of the Syndicate, but not every agent got the hint...
can fix that

2024-07-18 13:29 UTC, Piras314 approved these changes

2024-07-18 17:39 UTC, merged