Added Reagent granades
Goob-Station/Goob-Station pull request #421
Opened 2024-07-20 18:18 UTC by jorgun

## About the PR

Adds Lube and Glue granades. Based of Cleanades
a bundle box for a common riff raff, and and disconted for the true hero's of the station the clown and mime 

## Why / Balance

prevent sec from following you. cut of area , slow down pursuers , mute your target and prevent it from escaping.

## Technical details

smaller then the cleanade, about 1/4  so 1 cleanade can clean up 2 reagent granades.

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added fun!

2024-07-20 18:20 UTC, Aidenkrz commented
grenades not granades, also the commit from your assault borg pr is mixed in here.

2024-07-20 18:23 UTC, jorgun commented
> grenades not granades, also the commit from your assault borg pr is mixed in here.
yeah i commited it to the wrong branch , thats why the other branch had an errror

2024-07-21 03:21 UTC, TooSillyFennec commented
Not a maintainer here but, figured I'd mention this stuff anyways- not really enough for me to review here so comment it is! 

Grenades, not Granades.  Also, somewhat, not somwat. A lot of spelling errors.

The grenades aren't really priced well. Clown's Lube grenades are way too cheap compared to the clustersoap, and the box is definitely not worth 40 TC. A freedom implanter costs less by the way, making this "Fuck with the janitor" for the same price tier of an actually useful item.

Also, do remember .ftl and the locale folder exist. Every uplink item uses them, even goob unique items.

To mention the cluster soap- Just buff it instead of adding new items that won't get used. 1 decent item's better than 3 unused items that are straight up useless.

2024-07-22 11:24 UTC, a-person5660 requested changes
There's some spelling issues and you should probably give mimes glue grenades instead of lube grenades too. I think the pricing is fine, though I don't have final say on that.

2024-07-22 11:24 UTC, a-person5660 commented on Resources/Prototypes/Goobstation/Catalog/uplink_catalog.yml
> +  description: Contains 2 Glue granades and 2 Lube Grenades
"Granades" should be "grenades"

2024-07-22 11:24 UTC, a-person5660 commented on Resources/Prototypes/Goobstation/Catalog/uplink_catalog.yml
> +  description: Discounted Granades.30% off  Make the floor somwat Slippery!
"Granades" should be "grenades", specifying that this item is 30% off seems redundant but if you want to keep it there are more spelling errors to fix.

2024-07-22 11:24 UTC, a-person5660 commented on Resources/Prototypes/Goobstation/Catalog/uplink_catalog.yml
> +    - Clown # im sure some Clown mains will spend 100 tc just to buy 14 granades
Another "granades", should be "grenades"

2024-07-22 11:24 UTC, a-person5660 commented on Resources/Prototypes/Goobstation/Entities/Weapons/Guns/ReagentGranades.yml
> +  description: A box full of Lube grenades .
Space between grenades and the period, there shouldn't be any.

2024-07-22 11:24 UTC, a-person5660 commented on Resources/Prototypes/Goobstation/Catalog/uplink_catalog.yml
> +    - Mime
You should give the mime glue grenades instead of lube grenades

2024-07-22 11:26 UTC, a-person5660 commented
And you might wanna throw a buff for cluster soap here or make another PR for that.

2024-07-22 12:43 UTC, Piras314 commented on Resources/Prototypes/Goobstation/Catalog/uplink_catalog.yml
> +    - Mime
I think both having access to both is fine

2024-07-22 12:46 UTC, Piras314 approved these changes

2024-07-22 12:47 UTC, Piras314 requested changes

2024-07-22 12:47 UTC, Piras314 commented on Resources/Prototypes/Goobstation/Entities/Weapons/Guns/ReagentGranades.yml
Change the name of this file to reagent_grenades.yml and then this is approved

2024-07-22 12:48 UTC, Piras314 commented
Prices also need tweaking.

2024-07-22 12:54 UTC, a-person5660 commented
> Prices also need tweaking.

What prices need tweaking and what to?

2024-07-22 17:19 UTC, jorgun commented
lube is now 15, the box is still 40 to prevent over use.  glue can stay at 7 as it is not gonna be as problematic.

2024-07-22 17:47 UTC, Piras314 requested changes
reagent_grenades not Reagent_Grenades

2024-07-23 13:59 UTC, merged