Blueshield Officer and Nanotrasen Representative changes.
Goob-Station/Goob-Station pull request #443
Opened 2024-07-30 06:43 UTC by Verbalase

## About the PR
Removed all access from the Nanotrasen Representative and Blueshield Officer and changed the playtimes to better fit what the Paradise Station wiki says. There's also 

## Why / Balance
According to Paradise Station, neither of the roles even have AA. The jobs do not require the accesses either and are fine with less of them.

The playtimes according to the Paradise Station wiki require 50 hours of command playtime so... Yeah. The Blueshield Officer I don't believe should require just command access playtime since you are also acting as a bodyguard and will have to do more. Do tell if otherwise though.

One last thing was also changing who the Blueshield answers to since it IS said that the Blueshield Officer answers to Central Command and the Nanotrasen Representative.

## Media

- [x ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Changed the Blueshield and NTR's accesses, who the Blueshield answers to, and the playtime requirements for both jobs.

2024-07-30 06:47 UTC, Aidenkrz commented
115 hours is a bit extreme considering the playtime requirements for other command roles.

2024-07-30 06:49 UTC, Verbalase commented
> 115 hours is a bit extreme considering the playtime requirements for other command roles.

What should I change then for it?

2024-07-30 06:59 UTC, Aidenkrz commented
25 sec 25 command? total of 65 hours?

2024-07-30 07:02 UTC, Verbalase commented
> 25 sec 25 command? total of 65 hours?

Done. Anything else?

2024-07-30 12:30 UTC, Piras314 requested changes

2024-07-30 20:14 UTC, Verbalase commented on Resources/Prototypes/Goobstation/Roles/Jobs/Command/blueshield_officer.yml
> +  supervisors: "the Nanotrasen Representative and Central Command"
But that would conflict with what the Nanotrasen Representatie would get. The Blueshield answers to the NTR and CC.

2024-07-30 20:16 UTC, Piras314 commented on Resources/Prototypes/Goobstation/Roles/Jobs/Command/blueshield_officer.yml
> +  supervisors: "the Nanotrasen Representative and Central Command"
make a new localisation job-supervisors-ntr-centcom then

2024-07-30 21:21 UTC, Aidenkrz commented
also stop making fucking branches on the main repo, fork it.

2024-07-30 22:44 UTC, Verbalase commented
> also stop making fucking branches on the main repo, fork it.

Yessir yessir

2024-07-30 23:13 UTC, Verbalase commented on Resources/Prototypes/Goobstation/Roles/Jobs/Command/blueshield_officer.yml
> +  supervisors: "the Nanotrasen Representative and Central Command"
> make a new localisation job-supervisors-ntr-centcom then, mb

am i fine to put this in the job folder in en-us or do i have to put it in the goobstation folder still?

2024-07-30 23:19 UTC, Piras314 requested changes

2024-07-30 23:19 UTC, Piras314 commented on Resources/Locale/en-US/Goobstation/job/department-desc.ftl
why does this exist

2024-07-30 23:19 UTC, Piras314 commented on Resources/Locale/en-US/Goobstation/job/department.ftl
why

2024-07-30 23:19 UTC, Piras314 commented on Resources/Locale/en-US/Goobstation/job/job-description.ftl
why

2024-07-30 23:19 UTC, Piras314 commented on Resources/Locale/en-US/Goobstation/job/job-names.ftl
why

2024-07-30 23:19 UTC, Piras314 commented on Resources/Locale/en-US/Goobstation/job/job-supervisors.ftl
why

2024-07-30 23:19 UTC, Piras314 commented on Resources/Prototypes/Goobstation/Roles/Jobs/Command/blueshield_officer.yml
> +  supervisors: "the Nanotrasen Representative and Central Command"
goobstation folder, but why are you copying all this wizden stuff over into goobstation files/folder.... don't do that.

2024-07-30 23:19 UTC, Verbalase commented on Resources/Locale/en-US/Goobstation/job/department-desc.ftl
was deleting

2024-07-30 23:19 UTC, Verbalase commented on Resources/Locale/en-US/Goobstation/job/department.ftl
was deleting

2024-07-30 23:20 UTC, Verbalase commented on Resources/Locale/en-US/Goobstation/job/job-supervisors.ftl
was deleting

2024-07-30 23:28 UTC, Verbalase commented on Resources/Prototypes/Goobstation/Roles/Jobs/Command/blueshield_officer.yml
> +  supervisors: "the Nanotrasen Representative and Central Command"
so you want this in the goob folder but how specifically..?

2024-07-30 23:30 UTC, Verbalase commented on Resources/Prototypes/Goobstation/Roles/Jobs/Command/blueshield_officer.yml
> +  supervisors: "the Nanotrasen Representative and Central Command"
like do i make a job-supervisors.ftl file in the goob folder then put job-supervisors-ntr-centcom?

2024-07-30 23:38 UTC, Piras314 commented on Resources/Prototypes/Goobstation/Roles/Jobs/Command/blueshield_officer.yml
> +  supervisors: "the Nanotrasen Representative and Central Command"
so make job-supervisors.ftl in a goob folder then put job-supervisors-ntr-centcom = the Nanotrasen Representative and Central Command blablabla and change where it says in this file "the Nanotrasen blablabla" to job-supervisors-ntr-centcom

2024-07-31 00:17 UTC, Piras314 requested changes

2024-07-31 00:17 UTC, Piras314 commented on Resources/Prototypes/Goobstation/Roles/Jobs/Command/blueshield_officer.yml
> +  supervisors: "the Nanotrasen Representative and Central Command"
final step, change this line to supervisors: job-supervisors-ntr-centcom

2024-07-31 00:24 UTC, Verbalase commented on Resources/Prototypes/Goobstation/Roles/Jobs/Command/blueshield_officer.yml
> +  supervisors: "the Nanotrasen Representative and Central Command"
Is this all it and good or did I confuse another thing. Accidentally mistaked ntr and blueshield together at first.

2024-07-31 01:26 UTC, Verbalase commented
Tested and it seems to work just fine.

2024-07-31 01:38 UTC, Piras314 approved these changes

2024-07-31 01:39 UTC, merged

2024-07-31 01:41 UTC, Verbalase commented
im now a master coder

durk does this mean i can self-merge now

2024-07-31 01:42 UTC, Piras314 commented
no.