Added Medical Patches
Goob-Station/Goob-Station pull request #452
Opened 2024-08-01 23:06 UTC by jorgun

## About the PR

This PR adds Medical Patches a way to add chems over time, and in larger quanta then a syringe,
there are 4 flavors. basic rapid large, and makeshift patch.
fill the patches in the chemmaster and stick them to teh patient to transfer the chemicals.
when the patch is empty it will fall off on its own.

the makeshift is a bit different, it can be crafted by hand, can be filled by hand and is destoyed after use.

[ref: patch ](https://www.paradisestation.org/wiki/index.php?title=Medical_Items)

## Why / Balance

There have been a few PR over on wizden where they have been trying to figure out how to make people not abuse the Chemmaster,  by adding this there is anoter reason to not fill the chemmaster, or atlest keep one of them empty.
and gives the cemists/doctors a new tool.

this is atlso a bit more advanced tool for the chemists as mixing the content whitout overdoisng requires **math**

## Technical details

changed stickysystem as you can remove the patch from self whitout trigering the unstick prossess.

the basic holds 40u of chems, 1u of chems transfered evry 1 sec
the rapid holds 40u of chems, 2u of chems transfered evry 1 sec
the large holds 60uof chems,1u of chems transfered evry 1 sec and 15% of chems are transfered on use (10u if full)
makesihft holds 15u and transfer 1u evry 2 sec.
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
Havent made any sprites, just colored the mesh to look like bandaids.

## Breaking changes

**Changelog**

:cl:
- add: Added Medical Patches

2024-08-02 02:16 UTC, whateverusername0 commented
holy based

2024-08-02 02:23 UTC, whateverusername0 requested changes
made a quick review please check

2024-08-02 02:23 UTC, whateverusername0 commented on Content.Server/Goobstation/MedicalPatch/MedicalPatchComponent.cs
> +[AutoGenerateComponentState]
i believe you don't need it if you have default values everywhere

2024-08-02 02:23 UTC, whateverusername0 commented on Content.Server/Goobstation/MedicalPatch/MedicalPatchComponent.cs
> +    public bool SingelUse = false;
minor spelling mistake

2024-08-02 02:23 UTC, whateverusername0 commented on Content.Server/Goobstation/MedicalPatch/MedicalPatchSystem.cs
> +            //_polymorph.PolymorphEntity(uid, "UsedMedicalPatch");
if reagents are empty you can remove the existing entity and add a new one instead of polymorphing into it.
should be much easier and better

2024-08-02 02:23 UTC, whateverusername0 commented on Content.Server/Sticky/Systems/StickySystem.cs
> +        EnsureComp<UnremoveableComponent>(uid); //Goobstation - MedicalPatch
maybe don't? just make it when it gets unattached to stop injecting reagents or to get turned into a wasted one immediately
this shit WILL fuck up plungers. i believe.

2024-08-02 02:23 UTC, whateverusername0 commented on Resources/Prototypes/Goobstation/Entities/Objects/Specific/Medical/medical_patch.yml
> +      - BorgChassis # borgs are alive but dont get band aids.
this can be replaced by a Body component i believe. will make every possible living object except borgs be patchable

2024-08-02 02:23 UTC, whateverusername0 commented on Resources/Prototypes/Goobstation/Entities/Objects/Specific/Medical/medical_patch.yml
> +  description: EEEEWWWWWWW
how silly and awesome EEEEEEWWWWWWWWW 😨

2024-08-02 02:23 UTC, whateverusername0 commented on Resources/Prototypes/Goobstation/Entities/Objects/Specific/Medical/medical_patch.yml
> +  description: does not look hygenic
minor spelling mistake

2024-08-02 02:23 UTC, whateverusername0 commented on Resources/Prototypes/Goobstation/Entities/Objects/Specific/Medical/medical_patch.yml
> +  name: "Makeshift Patch"
you don't have to put them in braces

2024-08-02 02:23 UTC, whateverusername0 commented on Resources/Prototypes/Goobstation/Entities/Objects/Specific/Medical/medical_patch.yml
> +  name: "Medical patch"
you don't have to put them in braces
also no big letters in names

2024-08-02 08:47 UTC, jorgun commented on Content.Server/Sticky/Systems/StickySystem.cs
> +        EnsureComp<UnremoveableComponent>(uid); //Goobstation - MedicalPatch
Plunger dont use the stickysystem, only C4 uses the stickysystem, 
there is a small bug/feature that when you place a c4 on yourself you can just pick it up from the new container created insted of unsticking it.

2024-08-02 09:04 UTC, jorgun commented on Resources/Prototypes/Goobstation/Entities/Objects/Specific/Medical/medical_patch.yml
> +      - BorgChassis # borgs are alive but dont get band aids.
giving medical patches to the pets i think shud be allowed, anything else like borgs guardians or anything else the patch will fall off due to no bloodstream

2024-08-02 10:48 UTC, whateverusername0 commented on Content.Server/Sticky/Systems/StickySystem.cs
> +        EnsureComp<UnremoveableComponent>(uid); //Goobstation - MedicalPatch
> Plunger dont use the stickysystem, only C4 uses the stickysystem, there is a small bug/feature that when you place a c4 on yourself you can just pick it up from the new container created insted of unsticking it.

oh ok, doesn't matter then, i'm sure nothing will break whatsoever :trollface:

2024-08-02 10:49 UTC, whateverusername0 commented on Resources/Prototypes/Goobstation/Entities/Objects/Specific/Medical/medical_patch.yml
> +      - BorgChassis # borgs are alive but dont get band aids.
speaking of bloodstream, you can check for that component instead of using whatever you have now :godo:

2024-08-02 17:16 UTC, Aidenkrz commented on Resources/Prototypes/Goobstation/Entities/Objects/Specific/Medical/medical_patch.yml
> +  description: EEEEWWWWWWW
meical patch

2024-08-03 05:42 UTC, whateverusername0 commented on Content.Server/Goobstation/MedicalPatch/MedicalPatchSystem.cs
> +            //_polymorph.PolymorphEntity(uid, "UsedMedicalPatch");
@jorgun you can spawn it simply by doing `Spawn("UsedMedicalPatch", Transform(uid).Coordinated);`
pls do sth 🥺

2024-08-04 13:11 UTC, jorgun commented on Content.Server/Goobstation/MedicalPatch/MedicalPatchSystem.cs
> +            //_polymorph.PolymorphEntity(uid, "UsedMedicalPatch");
diddnt quite do the trick but by copinyg how snacks gets turned into trash i got it working

2024-08-04 13:11 UTC, jorgun commented on Resources/Prototypes/Goobstation/Entities/Objects/Specific/Medical/medical_patch.yml
> +  description: EEEEWWWWWWW
yes. spelling

2024-08-05 02:51 UTC, whateverusername0 approved these changes
ok looks good enough to me :+1:

2024-08-05 07:11 UTC, jorgun commented
> ok looks good enough to me 👍

i think so to, now we just need to do anoter round of balancing

2024-08-05 16:50 UTC, whateverusername0 commented
> i think so to, now we just need to do anoter round of balancing

also i suggest you find sprites more resembling a medical patch not just a bangade :trollface:

2024-08-05 17:06 UTC, jorgun commented
> > i think so to, now we just need to do anoter round of balancing
> 
> also i suggest you find sprites more resembling a medical patch not just a bangade :trollface:

TODO!

2024-08-05 20:15 UTC, Piras314 requested changes
Make a BaseMedicalPatch that MedicalPatchBasic and MedicalPatchPrefilledBase are children of, and change the popup messages to "Started placing patch" "Patch placed" "Started removing patch" "Patch removed" (which conveniently you will only have to do once in BaseMedicalPatch now!

2024-08-05 22:06 UTC, jorgun commented
changed base, 
added new sprite , added a solution indicator bar that colors after the soulution
added a border layer that can be used to tell the patches apart.

2024-08-05 22:09 UTC, jorgun commented
> don't see the push / commit rn

i forgot to push

2024-08-05 22:11 UTC, Piras314 approved these changes

2024-08-06 14:21 UTC, jorgun commented
![image](https://github.com/user-attachments/assets/574ccffc-de27-4c0f-b461-ed9286ea37b5)
working on new sprite

2024-08-07 08:26 UTC, whateverusername0 commented
> working on new sprite

yeah no making it stick onto you like a c4 is a bad idea
what if no sprite at all? or some kind of bandage like in visual traits (that will not be seen through hardsuits ofc)

2024-08-07 08:28 UTC, JoeHammad1844 commented
bandaid sprite is super blurry

2024-08-07 14:13 UTC, jorgun commented
> > working on new sprite
> 
> yeah no making it stick onto you like a c4 is a bad idea what if no sprite at all? or some kind of bandage like in visual traits (that will not be seen through hardsuits ofc)

Can make em not "visible" by not using sticky visuliser component. They will be behind the character On dreawdepth 3. There is a bug when you use a patch on your self, it don't trigger sticky visualiser. But as that is a self attached I don't mind the patch being hidden. 
I think they shud be visible to indicate a transfer of chemicals.  
I feel the sticky system works excellent the way it is now.

2024-08-07 14:24 UTC, jorgun commented
> bandaid sprite is super blurry

Bandaid is currently only used for Makeshift and as Trash item. Il respite it when I get a better idea for how a Makeshift shud look like.

2024-08-10 21:38 UTC, merged