Duke Nukies & stamcrit resistance
Goob-Station/Goob-Station pull request #466
Opened 2024-08-05 16:41 UTC by whateverusername0

## About the PR

CL :trollface:
also added stamina damage resistance which can be enabled by simply adding a StaminaDamageResistance component with the coefficient to an entity. very cool
now all hardsuits have 25% stamdmg resistance, bloodred has 50%, elite - 75%, jugger - 65%

## Why / Balance

i always wanted to balance nukies and i think i did a good job at it
GOD I LOVE TEH DUKE NUKEI

## Media
hardsuit stamcrit resistance check
![image](https://github.com/user-attachments/assets/8b3df54a-2a51-4a92-8d31-ef1be2b83d9d)
![image](https://github.com/user-attachments/assets/038a6ce1-66e1-4565-84c7-3f27df7c97e1)

roundstart nukie changes
![image](https://github.com/user-attachments/assets/86e3a11b-962f-47e5-9e17-7878e6407b8f)

cool new sprites
![image](https://github.com/user-attachments/assets/f169d180-c472-47bc-be24-e129fde0b496)

reinforcement changes
![image](https://github.com/user-attachments/assets/df131c1a-2cfd-483a-9444-85986487f944)
![image](https://github.com/user-attachments/assets/cf6b2789-bdef-4a1d-91a9-57702cd8053c)

:cl:
- add: Now all hardsuits have different stamina damage resistance.
- add: Nuclear operatives now spawn without hardsuits but with 50 more TC.
- add: Nuclear operative reinforcements now spawn with a bonus uplink with 50 TC.
- tweak: Changed nuclear operative hardsuit sprites.
- tweak: Decreased raid suit price to 30 TC
- tweak: Increased syndicate elite suit price to 70 TC
- tweak: Increased juggernaut suit price to 100 TC
- tweak: Increased the chinalake price to 150 TC
- tweak: Decreased nukie reinforcement agent price to 125 TC

2024-08-05 17:29 UTC, misandrie requested changes
Hysterically overtuned balance tied to a resprite for no real reason - by killing stuns entirely you remove any counter to juggernaut players, even if jugg walks in solo into 3 secoffs with stunbatons at point blank range, which should be an instant over for the player due to severe skill issue.

The real killer are tranq and rubber bullets, which do absurd amounts of stamina damage at range and thus - at little risk.

Discussion on stamres was held here in march (wizden server):
https://discord.com/channels/310555209753690112/1217867633588830239/1217867633588830239

Taking away hardsuits but giving 50 more telecrystals effectively gives them 50 tc for free if they decide to take anything but the default hardsuit - the redundancy is a balance and noobtrap issue of some bright individuals forgetting to buy a hardsuit in the first place and getting forced into an EVA suit off the shuttle instead.

Movement speed increases are not mentioned anywhere.

2024-08-05 17:53 UTC, a-person5660 commented
i think that stun resist is way too high, 0% for civ suits, 25% base for sec and nukie suits, then maybe 50% for elite and jug. also make the elite suit have 0 speed penalty.

2024-08-05 20:18 UTC, Piras314 commented on Resources/Locale/en-US/ghost/roles/ghost-role-component.ftl
> +ghost-role-information-nukeop-reinforcement-name = Nuclear Assailant
assailant doesn't make any sense here, put it back to op and if you really hate op I'd rather reinforcement than assailant

2024-08-05 20:19 UTC, Piras314 commented on Resources/Prototypes/Entities/Clothing/OuterClothing/base_clothingouter.yml
> +    coefficient: 0.75
remove this entirely

2024-08-05 20:20 UTC, Piras314 commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +    coefficient: 0.5 # 50% resistance
0.8

2024-08-05 20:21 UTC, Piras314 commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +    coefficient: 0.25 # 75% stamdamage resistance
0.8

2024-08-05 20:22 UTC, Piras314 commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +    coefficient: 0.35 # 65% stamdmg resist
0.65 and put the speed back up

2024-08-05 20:24 UTC, Piras314 requested changes
Revert all the TC and reinforcement changes.

Also see above for balance suggestions

2024-08-05 20:31 UTC, misandrie commented
> OP doesn't explain a single bit about balancing
> Maintainer jr. doesn't explain anything about his requested balance changes in response

2024-08-05 20:33 UTC, a-person5660 commented
also, you should probably make the resprite a seperate PR from this.

2024-08-05 20:34 UTC, Piras314 commented
just initial nerfs to get it in some kind of reasonable ballpark, will calculate the required number of stuns etc in a bit

2024-08-05 20:39 UTC, misandrie commented
> just initial nerfs to get it in some kind of reasonable ballpark, will calculate the required number of stuns etc in a bit

There's not a single effective nerf in this PR.

![image](https://github.com/user-attachments/assets/819ab580-0ead-4695-811d-a329e5f0efab)

2024-08-05 20:45 UTC, Piras314 commented
being immune to stuns with stimulants is fine

2024-08-05 20:46 UTC, misandrie commented
> being immune to stuns with stimulants is fine

You're expected to elaborate

2024-08-05 20:47 UTC, Piras314 commented
stims making you stun immune is fine, they're not easy to get en masse and you have to constantly inject yourself

2024-08-05 20:54 UTC, misandrie commented
> stims making you stun immune is fine, they're not easy to get en masse and you have to constantly inject yourself

I don't believe you've seen HM2 Tony RP with a guy full of stimkits and northstars getting full combo on the entire station before. Stimulants do more than just double your total stamina atm - they also massively increase your speed and heal you when you're at 70 damage or above but not crit.

There are already questionable combos balance-wise with the stimulants (the fucking desword) as-is, and this is a direct buff to hardsuits over a web vest (where 20% pierce for 50%/75% stam is the best tradeoff in the game atm).

2024-08-05 20:58 UTC, misandrie commented
This is not to mention that you'll be playing with abstract numbers and balance ping-pong because you'll have to now account for the stam resist modifiers and the total amount of stamina you have.

2024-08-06 01:44 UTC, whateverusername0 commented
ok addressing changes now

> tied to a resprite for no real reason

my bad og, it was supposed to be a modsuit PR but i got a bit carried away

> Taking away hardsuits but giving 50 more telecrystals effectively gives them 50 tc for free if they decide to take anything but the default hardsuit

ok, so what? why not eco and buy something like raid suits? this leaves more TC for nukies to spend on gimmicks

> bright individuals forgetting to buy a hardsuit in the first place and getting forced into an EVA suit off the shuttle instead

if someone doesn't buy armor that's his problem, why do we need to tune the mechanics towards the new playerbase? they won't be able to learn from mistakes if we remove mistakes from the game :trollface:

2024-08-06 01:47 UTC, whateverusername0 commented on Resources/Prototypes/Entities/Clothing/OuterClothing/base_clothingouter.yml
> +    coefficient: 0.75
don't see an issue here, taking one more hit from a batong to go stamcrit while wearing a hardsuit should be nice

2024-08-06 01:50 UTC, whateverusername0 commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +    coefficient: 0.25 # 75% stamdamage resistance
please give elite some love hot damn
it's less resistant to brute therefore should at least have more stamresist

2024-08-06 02:00 UTC, whateverusername0 commented
ok here's my stam resistance changes:
all nukie hardsuits - 50%
engi, security - 25%
warden, CE - 35%
hos, captain, wizard, ERT - 50%
death squad - 90%

2024-08-06 09:58 UTC, misandrie commented
> if someone doesn't buy armor that's his problem, why do we need to tune the mechanics towards the new playerbase? they won't be able to learn from mistakes if we remove mistakes from the game :trollface:

Mistakes of one guy reflect on the whole team. If this skill issue wouldn’t have affected anyone else you’d have some ground to stand on. People are already at each other’s throats for minor mistakes when playing ops.

2024-08-06 14:30 UTC, jorgun commented
> ok here's my stam resistance changes: all nukie hardsuits - 50% engi, security - 25% warden, CE - 35% hos, captain, wizard, ERT - 50% death squad - 90%

this sounds more resonabe, we shud to a trila weekend to see how this works

2024-08-07 15:27 UTC, closed without merging

2024-08-07 15:28 UTC, whateverusername0 commented
i renamed the branch. well shit