multi page action bar
Goob-Station/Goob-Station pull request #469
Opened 2024-08-07 11:26 UTC by yglop

## About the PR
Action bar now can hold up to 100 items. 10 actions per page.

## Why / Balance
10 slots for action bar is just not enough. This issue become worse with the addition of changeling.

## Technical details
It's just revert of https://github.com/space-wizards/space-station-14/commit/4e84961ef8ca0591a90ca5f30f5c69b557a76318

## Media
![Screenshot from 2024-08-07 16-11-59](https://github.com/user-attachments/assets/db94725a-bcd8-4309-9428-d878ad138c3a)
![Screenshot from 2024-08-07 16-12-05](https://github.com/user-attachments/assets/c773cf77-c9d9-4ae4-83d2-7bd3fda96cba)
![Screenshot from 2024-08-07 16-12-39](https://github.com/user-attachments/assets/653c554a-9a07-42e1-ae7f-cef29d27f8b9)

## Requirements

- [ ] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

2024-08-07 11:38 UTC, misandrie commented
check if this works on separated ui

2024-08-07 12:37 UTC, yglop commented
> check if this works on separated ui
![Screenshot from 2024-08-07 17-36-06](https://github.com/user-attachments/assets/7c5053d9-f71e-47ff-9db3-8fec6a87e55e)
![Screenshot from 2024-08-07 17-36-12](https://github.com/user-attachments/assets/0fbbdae0-0e85-4a30-a768-4aad24135845)

2024-08-07 12:59 UTC, whateverusername0 requested changes
i'm wiznerding you right here right now

2024-08-07 12:59 UTC, whateverusername0 commented on Content.Client/UserInterface/Systems/Actions/ActionUIController.cs
> +    private const int DefaultPageIndex = 0; // goobstation
you should prolly add a comment at the start of the class that it's been heavily modified and should not be tampered with (//goobstation)

2024-08-07 15:57 UTC, misandrie commented
> > check if this works on separated ui
> > ![Screenshot from 2024-08-07 17-36-06](https://private-user-images.githubusercontent.com/95057024/355818196-7c5053d9-f71e-47ff-9db3-8fec6a87e55e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNDY1MTcsIm5iZiI6MTcyMzA0NjIxNywicGF0aCI6Ii85NTA1NzAyNC8zNTU4MTgxOTYtN2M1MDUzZDktZjcxZS00N2ZmLTlkYjMtOGZlYzZhODdlNTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDE1NTY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMGE1NGYyZWQ3YTMxMDQ0NTA1N2MwOWEyYzNlM2E0MDQ3OGNjMTg0NzYxNDZjY2ZkMWFmMjBkNWJmNTIwMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W9ayZ-KFuMTFWM49MU0NOJbKZDvmgv6LZRi-m6yDels)
> > ![Screenshot from 2024-08-07 17-36-12](https://private-user-images.githubusercontent.com/95057024/355818210-0fbbdae0-0e85-4a30-a768-4aad24135845.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNDY1MTcsIm5iZiI6MTcyMzA0NjIxNywicGF0aCI6Ii85NTA1NzAyNC8zNTU4MTgyMTAtMGZiYmRhZTAtMGU4NS00YTMwLWE3NjgtNGFhZDI0MTM1ODQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDE1NTY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNjVkZTdiMzZhMTdmYTlmYzJmZDYyOGZjNDkyZDljNGFjNTI0MWUzZDRjM2VhMmUwODhhMjIzY2NmYmZmZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cllsjtALS0wjUcth0uV5fgtXXkto5v6dSB8qLSIfvK8)

horrifying

2024-08-08 10:21 UTC, yglop commented on Content.Shared/Input/ContentKeyFunctions.cs
> +        // goobstation
whole file is written that way

2024-08-09 18:01 UTC, whateverusername0 commented on Content.Shared/Input/ContentKeyFunctions.cs
> +        // goobstation
this is so sad, ok resovled

2024-08-10 21:37 UTC, merged

2024-08-11 04:00 UTC, JoeHammad1844 commented
HOLY SHIT YOU FINALLY FIXED THAT SUPER ANNOYING GLITCH WHERE THE PDA LIGHT ACTION WOULD JUMP POSITIONS WHEN YOU HOLD IT IN YOUR HAND
I WILL NO LONGER WANT TO KILL MYSELF WHEN PLAYING MEDICAL