traitor item Energy crossbow
Goob-Station/Goob-Station pull request #490
Opened 2024-08-12 06:07 UTC by yglop

## About the PR
Adds energy crossbow to uplink for 50 tc.

## Why / Balance
This will add more variety and I hope that less players will take storage implant + emag and do nothing the whole shift.

## Technical details
Original commit by Ratyyy:
https://github.com/Workbench-Team/space-station-14/commit/e2414c73e0dc72167a68a7e2846b15de80f7b24e

**Changelog**
:cl:
- add: Syndicate weapons supply department can now provide new Energy Crossbow for just 49.99!

2024-08-12 06:26 UTC, whateverusername0 requested changes

2024-08-12 06:26 UTC, whateverusername0 commented on Resources/Prototypes/Goobstation/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
> +        Poison: 10
please change that to heat

2024-08-12 06:26 UTC, whateverusername0 commented
unrelated sawmill test, merg now :trollface:

2024-08-12 06:59 UTC, yglop commented on Resources/Prototypes/Goobstation/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
> +        Poison: 10
but tg wiki said 
![image](https://github.com/user-attachments/assets/9861af3e-0e9e-42e9-88a5-b30a16e3f444)
:cry:

2024-08-12 09:02 UTC, whateverusername0 commented on Resources/Prototypes/Goobstation/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
> +        Poison: 10
> but tg wiki said

your crossbow doesn't knock the eveny down for 1 seconds so it's ooseless
also why tf does *energy* crossbow deal *toxin* damage? this i call bad design choices

2024-08-12 09:26 UTC, JoeHammad1844 commented on Resources/Prototypes/Goobstation/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
> +        Poison: 10
budget AP :trollface:

2024-08-12 09:46 UTC, yglop commented on Resources/Prototypes/Goobstation/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
> +        Poison: 10
done

2024-08-12 13:26 UTC, whateverusername0 approved these changes
i approve of this PR (even though i'm not a maintainer :trollface:)

2024-08-12 20:10 UTC, Aidenkrz commented
Can we get some media on this?

2024-08-13 20:22 UTC, Aidenkrz commented
https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html?highlight=changelog#changelog

2024-08-13 20:51 UTC, merged