Duke nukies & Stamcrit resistance part 2
Goob-Station/Goob-Station pull request #491
Opened 2024-08-12 06:17 UTC by whateverusername0

## About the PR
yeah. #466 #471 
![image](https://github.com/user-attachments/assets/57bd9bf8-8ebb-49d9-b2ac-8a327e1487d0)

:cl:
- add: Now (almost) all hardsuits have different stamina damage resistance.
- add: Nuclear operatives now spawn without hardsuits but with 50 more TC.
- add: Nuclear operative reinforcements now spawn with a bonus uplink with 50 TC.
- tweak: Decreased raid suit price to 30 TC
- tweak: Increased syndicate elite suit price to 70 TC
- tweak: Increased juggernaut suit price to 100 TC
- tweak: Increased the chinalake price to 150 TC
- tweak: Decreased nukie reinforcement agent price to 125 TC

2024-08-12 06:19 UTC, Verbalase commented
mald-

2024-08-12 06:19 UTC, whateverusername0 commented
> mald-

does he know? :trollface:

2024-08-12 06:34 UTC, whateverusername0 commented
absolutely unrelated test fail

2024-08-12 09:25 UTC, JoeHammad1844 commented
hairline regrowing hopeful PR

2024-08-12 20:07 UTC, Aidenkrz requested changes

2024-08-12 20:07 UTC, Aidenkrz commented on Content.Shared/Goobstation/Stunnable/StaminaDamageResistanceSystem.cs
> +    private void OnExamine(Entity<StaminaDamageResistanceComponent> ent, ref ExaminedEvent args)
mf why this in default examine instead of the actual resist examine

2024-08-12 20:07 UTC, Aidenkrz commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +    sprintModifier: 1.0
you aint slick with this, change it back

2024-08-12 20:07 UTC, Aidenkrz commented on Resources/Prototypes/Entities/Objects/Specific/syndicate.yml
> +#this uplink MUST be used for nukeops, as it has the tag for filtering the listing.
This can be moved to /Goobstation/

2024-08-12 20:07 UTC, Aidenkrz commented on Resources/Prototypes/Roles/Antags/nukeops.yml
> +- type: startingGear
This should be moved to /Goobstation/ as well

2024-08-15 03:31 UTC, whateverusername0 commented on Content.Shared/Goobstation/Stunnable/StaminaDamageResistanceSystem.cs
> +    private void OnExamine(Entity<StaminaDamageResistanceComponent> ent, ref ExaminedEvent args)
because armor system won't let me

2024-08-18 22:55 UTC, Aidenkrz commented on Content.Shared/Goobstation/Stunnable/StaminaDamageResistanceSystem.cs
> +    private void OnExamine(Entity<StaminaDamageResistanceComponent> ent, ref ExaminedEvent args)
There is no such thing as "I can't"

2024-08-21 09:06 UTC, whateverusername0 commented on Content.Shared/Goobstation/Stunnable/StaminaDamageResistanceSystem.cs
> +    private void OnExamine(Entity<StaminaDamageResistanceComponent> ent, ref ExaminedEvent args)
you're right

2024-08-21 09:07 UTC, whateverusername0 commented
@Aidenkrz rerequesting rereview

2024-08-23 00:09 UTC, whateverusername0 commented
@Aidenkrz 
![](https://media.discordapp.net/attachments/776578963694551071/1269205805421559858/cooltext463243197532673.gif?ex=66c8ecc4&is=66c79b44&hm=89d64d87411eca501f5c675d9439e27e8a0e0ec57c30db598ae67a23aa82218b&=)

2024-08-24 02:31 UTC, Aidenkrz commented
ask staff about this because when i merge this they are inevitably going to bitch and complain that they didnt know it was getting added

2024-08-24 04:31 UTC, whateverusername0 commented
> ask staff about this because when i merge this they are inevitably going to bitch and complain that they didnt know it was getting added

you're staff :trollface:

2024-08-25 20:25 UTC, whateverusername0 commented
@Piras314 ![](https://media.discordapp.net/attachments/776578963694551071/1269205805421559858/cooltext463243197532673.gif?ex=66c8ecc4&is=66c79b44&hm=89d64d87411eca501f5c675d9439e27e8a0e0ec57c30db598ae67a23aa82218b&=)

2024-08-28 08:07 UTC, whateverusername0 commented
gonna draft it for now (don't close it)

2024-08-29 09:05 UTC, whateverusername0 commented
@Piras314 need review
also the map is slightly different from what i showed on discord
not willing to retest it for the 12th time tho :trollface:

2024-08-29 11:27 UTC, JoeHammad1844 commented
does the ship's suit storage units have free bloodreds like ss13 or are they EVA suits?

2024-08-29 12:20 UTC, Piras314 approved these changes

2024-08-29 21:05 UTC, packmore commented
> does the ship's suit storage units have free bloodreds like ss13 or are they EVA suits?

unless that was literally changed for this PR, nukie ships should have syndicate EVAs in their suit storages.

2024-08-29 21:44 UTC, whateverusername0 commented
it has evas

2024-08-30 01:32 UTC, merged

2024-08-30 10:25 UTC, JoeHammad1844 commented
wait so none of the hardsuits even have stamdam resistance?

2024-08-31 12:17 UTC, JoeHammad1844 commented
by the way you forgot to add the nuke code folder, the one that fixes nukies only getting their nuke code

2024-09-01 12:04 UTC, Piras314 commented
pretty sure that was fixed upstream

2024-09-04 07:44 UTC, JoeHammad1844 commented
> pretty sure that was fixed upstream

i think it was fixed upstream with the folder

2024-09-04 07:46 UTC, JoeHammad1844 commented
not 100% sure on how it worked, but i think the station was always loaded first so the code would always be the station nuke. and it was fixed by, when the folder was used, the code would generate at that moment with both the nukes codes able to be generated and it picked one fairly