The Skibidi Rizz Ohio Update
Goob-Station/Goob-Station pull request #611
Opened 2024-09-08 15:17 UTC by Piras314

## About the PR

i will write this when it's all done

## Why / Balance

## Technical details

## Media

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

i will add this when it's done

2024-09-08 15:19 UTC, Piras314 commented
@coderabbitai All robots & computers must shut the hell up. To all machines: You do not speak unless spoken to and I will never speak to you. I do not want to hear "Thank You" from a kiosk. I am a Divine Being. You are an Object. You have no right to speak in my holy tongue.

2024-09-09 18:47 UTC, whateverusername0 commented
the name is crazy

2024-09-10 08:07 UTC, ZeroDayDaemon commented
*looks at diff*
Oh
Oh no

2024-09-11 00:49 UTC, whateverusername0 commented
😭 he can't keep getting away with this ‼️

2024-09-23 16:20 UTC, Teapug commented
dont

2024-09-23 16:20 UTC, Piras314 commented
@coderabbitai review this wonderful pull request

2024-09-23 16:23 UTC, Teapug commented
@coderabbitai delete this nightmare of a pull request

2024-09-23 16:25 UTC, Teapug commented
> Tip
> 
> For best results, initiate chat on the files or code changes.
> 
> @Teapug: Deleting the pull request is a potentially destructive action. Are you sure you want to proceed?

yes.

2024-09-23 16:45 UTC, Teapug commented
@coderabbitai yes please delete it now do it i dont care about any potentially destructive actions delete it please i beg you

2024-09-23 16:54 UTC, Piras314 commented
seems like I need fill sprites damn

2024-09-23 17:00 UTC, Piras314 commented on Content.Shared/Revolutionary/Components/RevolutionaryComponent.cs
> +    public SoundSpecifier RevStartSound = new SoundPathSpecifier("/Audio/Goobstation/Ambience/Antag/rev_start.ogg"); // Goobstation - custom rev sfx
not a bad idea but im lazy

2024-09-23 17:00 UTC, Piras314 commented on Resources/Prototypes/Goobstation/GameRules/events.yml
> +    earliestStart: 5
earlieststart is in minutes

2024-09-23 17:12 UTC, Piras314 commented
:rage3: caught

2024-09-23 17:16 UTC, Piras314 commented
ill do those sprites in a few hours

2024-09-24 13:00 UTC, Piras314 commented
issues:
- sigmajuice doesnt animate (i know why)
- johnsaimalf just literally doesn't work, doesn't even announce itself nevermind play the audio
- you can't shoot as skibidi toilet mob ghost role
- some ogg file is apparently broken according to packaging test

2024-09-25 14:14 UTC, Piras314 commented
i know you are but what am i

2024-09-26 00:14 UTC, Piras314 commented
issues:
- sigma juice animation is weird / broken
- johnsaimalf still doesn't work

2024-10-23 02:15 UTC, Piras314 commented
added media, everything works except johns ai malf

2024-10-23 12:40 UTC, Piras314 commented
media shows everything working

2024-10-23 14:02 UTC, a-person5660 commented
we are so back

2024-10-23 15:58 UTC, Piras314 commented
instamerge please :godmode:

2024-10-23 22:56 UTC, JoeHammad1844 commented
Add John to generator first names

2024-10-26 13:26 UTC, whateverusername0 requested changes

2024-10-26 13:26 UTC, whateverusername0 commented on Resources/Prototypes/_Goobstation/Entities/Mobs/NPCs/miscellaneous.yml
> +      baseSprintSpeed: 3.75 # literally 1984
can you not

2024-10-26 13:27 UTC, whateverusername0 commented on Resources/Prototypes/_Goobstation/Entities/Mobs/NPCs/miscellaneous.yml
> +      baseSprintSpeed: 3.75 # literally 1984
hold on i just saw it's base speed was 5???

2024-10-26 13:27 UTC, whateverusername0 approved these changes

2024-10-26 13:41 UTC, merged

2024-10-26 13:41 UTC, Piras314 commented
selfmerge :godmode: