Added Nigthvision
Goob-Station/Goob-Station pull request #673
Opened 2024-09-21 10:19 UTC by jorgun

## About the PR

copied nigthvision from https://github.com/Rxup/space-station-14
changed some of it. 

## Why / Balance

## Technical details

added nigthvision to:
ninja visors
all comands hardsuit helmets
nukie hardsuits that is not basic. 
some animals that shud have good nigthvision.
dragon and carps

## Media

nightvision disabled
![image](https://github.com/user-attachments/assets/04145180-4358-4192-80cf-a89e92d225b5)
nightvision enabled
![image](https://github.com/user-attachments/assets/33836619-6ff7-4efe-92c1-a8d6de930c34)
nightvision disabled on animal
![image](https://github.com/user-attachments/assets/a6a76dd5-9cf4-4658-90c8-720d4ee64432)

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Added Nigthvision

2024-09-21 10:23 UTC, BombasterDS commented
Finally someone port nightvision, thanks!
But i think you should remove nightvision from command hardsuits because command players will always walk in hardsuits just to see better in the dark. Also add nightvision to nukies visor instead of hardsuits.

2024-09-21 11:47 UTC, whateverusername0 requested changes
looks good but

rename PNV to NVG
also remove NVG from heads/cap hardsuits
move it to the syndicate gasmask, ninja visor and mesons (engi goggles)

2024-09-21 13:53 UTC, Piras314 commented
I feel like it really needs some shader or at least noise texture over it.

2024-09-21 14:38 UTC, JoeHammad1844 commented
I think the night vision should be moved from the syndicate gas mask to the visor

2024-09-21 15:11 UTC, whateverusername0 requested changes

2024-09-21 15:11 UTC, whateverusername0 commented on Content.Client/Backmen/Eye/NightVision/NightVisionSystem.cs
> +namespace Content.Client.GG.Eye.NightVision;
no GG namespace x2

2024-09-21 15:11 UTC, whateverusername0 commented on Content.Shared/Backmen/Eye/NightVision/Components/PNVComponent.cs
> +public sealed partial class PNVComponent : Component
rename PNV to NVD or NVG

2024-09-21 15:15 UTC, Piras314 commented
Visually two changes would be great:
1. Some kind of noise or otherwise some kind of shader
2. The ability to set different colours for the visor, for example the syndicate gas mask being red would be very interesting. Green and red would probably be the only colours though.

2024-09-21 15:34 UTC, a-person5660 commented
i would love to see some white phosphorus NVGs. 

also give changelings this when they use that enhanced eyesight ability thingy

2024-09-21 15:38 UTC, whateverusername0 commented
> also give changelings this when they use that enhanced eyesight ability thingy

they gain thermals too :godo:

2024-09-21 16:31 UTC, jorgun commented
im redoing some of the code. 
and whit all the rewrite im gonna move it into the /goobstation/ structure. 

there is problem whit having it add the comp and removing it to the mob. gonn look into making it more contained to the item.
i dont know how to add static overlay, but i like the idea. will work on that when. other stuff is stable.
i gonna need feedback from admin on what items and animals to add this to.

2024-09-25 10:39 UTC, a-person5660 commented
👍

2024-09-25 10:43 UTC, JoeHammad1844 commented
> they gain thermals too :godo:

speaking of thermals, the bulldog bundle gets a pair in their bag, when they're implemented

2024-09-25 13:07 UTC, ElPidor commented
it would be cool being red vision for syndicate gasmask since they have red visor 
For colour blind people theyll see it gray so its good 
Imho could this pr rule to future RP thermal vision update?

2024-09-25 14:01 UTC, Piras314 commented
remember it's _Goobstation now

2024-10-06 07:13 UTC, a-person5660 commented
is this still being worked on?

2024-10-13 03:09 UTC, closed without merging

2024-10-13 04:30 UTC, JoeHammad1844 commented
it's over..

2024-10-13 19:57 UTC, jorgun commented
i git a bit to abisus whit this one, i managed to make it work as a raseial ability for dragon cats, but for NVG goggels i diddnt manage to get it working.