Unique items teleporters
Goob-Station/Goob-Station pull request #690
Opened 2024-09-25 01:11 UTC by BombasterDS

## About the PR
Adds two teleporters for BSO and NTR that allows them teleport their lockers if station don't have them.

## Why / Balance
Since we can't map them on every map

## Technical details
Lockers create unique item marker to prevent abuse with locker breaking.
UniqueEntityChecker search for all markers and delete teleporter entity if found with proper marker name.

## Media
https://discord.com/channels/1202734573247795300/1236697829171527841/1288306630307483648

:cl:
- add: BSO and NTR now can teleport their lockers if they not mapped!

2024-09-25 02:27 UTC, JoeHammad1844 commented
could this also be done for nukies to spawn in syndicate bombs? that's the way it's done in ss13

2024-09-25 07:17 UTC, BombasterDS commented on Resources/Prototypes/_Goobstation/Entities/Objects/Devices/unique_teleporters.yml
> +
items field is required field, so i can left it empty

2024-09-25 08:41 UTC, BombasterDS commented on Resources/Prototypes/_Goobstation/Entities/Objects/Devices/unique_teleporters.yml
> +
I lied! It worked because it's abstract class :trollface:

2024-09-25 08:43 UTC, BombasterDS commented
github not allows me to push commit (dead russia servers :()

![image](https://github.com/user-attachments/assets/d30bfa76-7469-4b51-84c4-02d63df981a7)

2024-09-25 14:03 UTC, Piras314 requested changes
namespace is _Goobstation, other than that looks good though

2024-09-25 15:04 UTC, BombasterDS commented
> namespace is _Goobstation, other than that looks good though

Fixed

2024-09-25 15:17 UTC, Piras314 approved these changes

2024-09-26 09:37 UTC, whateverusername0 approved these changes

2024-09-26 13:41 UTC, merged

2024-09-27 15:36 UTC, Aidenkrz commented on Resources/Prototypes/_Goobstation/Entities/Objects/Devices/unique_teleporters.yml
> +
yes remove that learning