Pizdec development take 1
Goob-Station/Goob-Station pull request #785
Opened 2024-10-18 16:04 UTC by ElPidor

The holy syndicate soldier 

## Breaking changes
I made DisarmBonus
You add bonus to thing and if you shove you get bonus to shove mainly gloves
but this shit for some reason doesnt work on gloves but if you add this to Urist and shove itll work 
the more it goes to 0 the more % of succes will be 
I also made disarming event so game should understand if disarmer has bonus or not  and then apply it in the end but....
I made new glasses (god help) You can toggle them but i dont know how to make that when you toggle lights sick .ogg will play but not standart flashlight.ogg
I made new suit
I made new belt 
I made new gloves (god help me)
I made new helmet 
I made new silenced boots
I made 3 new sound for this set
**Changelog**
I hope itll be good

2024-10-18 16:05 UTC, ElPidor commented
WHAIT WHAIT WHAIT 
NO NO NO NO NO
WRONG repo???

2024-10-18 16:30 UTC, ElPidor commented
Okey, i did allright time to clean all stuff above

2024-10-18 18:04 UTC, Piras314 requested changes
didn't review everything but apply what I said everywhere else and where I said and I'll review it again after

2024-10-18 18:04 UTC, Piras314 commented on Resources/Audio/Effects/Footsteps/silencedbootsstep.ogg
Should be in _Goobstation folder

2024-10-18 18:04 UTC, Piras314 commented on Resources/Audio/Items/visor_off.ogg
Should be in _Goobstation folder

2024-10-18 18:04 UTC, Piras314 commented on Resources/Audio/Items/visor_on.ogg
Should be in _Goobstation folder, also credit isn't added for any of these audios it doesn't look like

2024-10-18 18:04 UTC, Piras314 commented on Resources/Prototypes/Entities/Clothing/Belt/belts.yml
All the changes here should be in the corresponding file in a _Goobstation folder (create one if there isn't one already)

2024-10-18 18:04 UTC, Piras314 commented on Resources/Prototypes/Entities/Clothing/Belt/belts.yml
> +  description: A brand new chest rig for an operation. Gorlex LLC provides it as an addition to compact armorsuit.
change to "A branch new chest rig provided by Gorlex LLC in addition to the compact armor suit"

2024-10-18 18:04 UTC, Piras314 commented on Resources/Prototypes/Entities/Clothing/Belt/belts.yml
> +  id: ClothingBeltSyndieWest
Vest, not West

2024-10-18 18:04 UTC, Piras314 commented
Also check the checkfails.

2024-10-18 21:49 UTC, JoeHammad1844 commented
1. im not a fan of the sprites, they are all too dark
2. also, make the bundle come in the syndicate backpack so you dont need the extra purchase for full move speed
3. please dont resprite the syndicate recruit jumpsuit, that one is for ship vs ship and i'd prefer it stays that way, make a whole new jumpsuit prototype instead

2024-10-19 10:52 UTC, ElPidor commented
> 1. im not a fan of the sprites, they are all too dark
> 2. also, make the bundle come in the syndicate backpack so you dont need the extra purchase for full move speed
> 3. please dont resprite the syndicate recruit jumpsuit, that one is for ship vs ship and i'd prefer it stays that way, make a whole new jumpsuit prototype instead
1 Yeah i agree, i made it a little more colourfull
![image](https://github.com/user-attachments/assets/0b477d08-2f98-426e-b555-431c53d9eeae)
.  you can dm or just write in generall Im bloodyspy on discord. 
2 Yeah i guess, but ill try to check is if it possible to put all bundle into vest, because its all "compact" styled
3 I didnt resprite it, like i did but then i made syndidrip.rsi 
![image](https://github.com/user-attachments/assets/915b1d7f-70b9-4208-9b43-0d93f0b1e1ba)
Itll come with a bundle or ill ad it as pointless item\emmagged clothesmate item 
![image](https://github.com/user-attachments/assets/f0bd689c-e112-4dad-bf44-21c20bb16238)
![image](https://github.com/user-attachments/assets/717db3a9-8b69-4502-974f-fb8114fa64e2)

2024-10-19 14:13 UTC, InfinityPandaRed commented
> > 1. im not a fan of the sprites, they are all too dark
> > 2. also, make the bundle come in the syndicate backpack so you dont need the extra purchase for full move speed
> > 3. please dont resprite the syndicate recruit jumpsuit, that one is for ship vs ship and i'd prefer it stays that way, make a whole new jumpsuit prototype instead
> >    1 Yeah i agree, i made it a little more colourfull
> >    ![image](https://private-user-images.githubusercontent.com/49343726/378072502-0b477d08-2f98-426e-b555-431c53d9eeae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNDc0MzYsIm5iZiI6MTcyOTM0NzEzNiwicGF0aCI6Ii80OTM0MzcyNi8zNzgwNzI1MDItMGI0NzdkMDgtMmY5OC00MjZlLWI1NTUtNDMxYzUzZDllZWFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDE0MTIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyZTBhZDU3MTY1MmMxOTRlYWQ0ZjYxYjg2MGQ5ODZjMDEwMzE5MmI3YjczMDJmZjQ4NDUxMTVhMjY0YTE2Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._kgN1z-4evclRmCV9V-fVn8KtC3M4s7KLLeq-MAomAY)
> >    .  you can dm or just write in generall Im bloodyspy on discord.
> >    2 Yeah i guess, but ill try to check is if it possible to put all bundle into vest, because its all "compact" styled
> >    3 I didnt resprite it, like i did but then i made syndidrip.rsi
> >    ![image](https://private-user-images.githubusercontent.com/49343726/378072566-915b1d7f-70b9-4208-9b43-0d93f0b1e1ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNDc0MzYsIm5iZiI6MTcyOTM0NzEzNiwicGF0aCI6Ii80OTM0MzcyNi8zNzgwNzI1NjYtOTE1YjFkN2YtNzBiOS00MjA4LTliNDMtMGQ5M2YwYjFlMWJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDE0MTIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyMGFiYjM3YzZkNzNjZjY0OTg0MTcwZWUzZDJhZjhhMjhjMTQyMmNjNDZhNWJiMGE0MmJjNDI0NmY2MmRmMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4svulli1RG9lgn7mCphtVzO6lCuGVUdNAK1jbJHShks)
> >    Itll come with a bundle or ill ad it as pointless item\emmagged clothesmate item
> >    ![image](https://private-user-images.githubusercontent.com/49343726/378072821-f0bd689c-e112-4dad-bf44-21c20bb16238.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNDc0MzYsIm5iZiI6MTcyOTM0NzEzNiwicGF0aCI6Ii80OTM0MzcyNi8zNzgwNzI4MjEtZjBiZDY4OWMtZTExMi00ZGFkLWJmNDQtMjFjMjBiYjE2MjM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDE0MTIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5OWM4MTYzMWEyZTgzYTk2ZjFjODkyZDFhOGNjNWRkZjlmNzgzMGQyYTI1MzllMThiYjY1OGJmZWQ1Y2YxNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SiTuF69TEIPmYsYXsTJcc7Gso8exYPFt4oOi0ysJeus)
> >    ![image](https://private-user-images.githubusercontent.com/49343726/378072860-717db3a9-8b69-4502-974f-fb8114fa64e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNDc0MzYsIm5iZiI6MTcyOTM0NzEzNiwicGF0aCI6Ii80OTM0MzcyNi8zNzgwNzI4NjAtNzE3ZGIzYTktOGI2OS00NTAyLTk3NGYtZmI4MTE0ZmE2NGUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDE0MTIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiMjZiMjQ5YmYyYzBlZDQ2ZjQxZmU5NjUzMjlhMjA5OWZiYzAyMDhkZjNkMDAyODg1ZjA3NDc3ZDk3ZDk3MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1krxq0Ncrv7W8HLMwC4MiimYxWCE7nf7_dLspm4ywtU)

yeah that looks way better

2024-10-29 07:07 UTC, ElPidor commented
Since new stamina meta got merged that is pretty good for my PR 
The bad side is that i wont be able physically continue any of my ideas for a year. 
The concet is yours, dear ananymouses, i hope you wont be lazy and will make my dream PR real. BTW, i made odd sounds so dont be afraid about license. Wait me for next year and ill make _syndicate look grate again_
     - With honor, BloodySpy

2024-10-29 07:07 UTC, closed without merging