Heretics update part 4
Goob-Station/Goob-Station pull request #795
Opened 2024-10-23 11:48 UTC by whateverusername0

## About the PR

Added codex cicatrix, contraband checking, made a big cleanup refactor boogie and fixed some bugs.

:cl:
- add: Items with magical properties are now illegal on Nanotrasen territory.
- add: Some heretic items now have better tooltips.
- fix: Fixed void pull being extremely OP
- fix: Heretics are now unable to transmute items using their own organs.
- add: Added codex cicatrix for Heretics as an early progression tool.
- tweak: Mansus grasp and codex cicatrix now glow in the dark.

2024-10-23 12:50 UTC, Piras314 requested changes

2024-10-23 12:50 UTC, Piras314 commented on Content.Server/_Goobstation/Heretic/Abilities/HereticAbilitySystem.Void.cs
>          foreach (var pookie in topPriority)
pookie is crazy

2024-10-23 12:50 UTC, Piras314 commented on Content.Server/_Goobstation/Heretic/EntitySystems/EldritchInfluenceSystem.cs
> +        RaiseLocalEvent(user, ev);
I think this is right?

2024-10-23 12:50 UTC, Piras314 commented on Resources/Locale/en-US/_Goobstation/Heretic/abilities/heretic.ftl
> +heretic-blade-void-examine = [color=cyan]While there is at least a single marked heathen in a large proximity, teleport behind it's back without breaking the blade.[/color]
rabbit is right

2024-10-23 12:50 UTC, Piras314 commented on Resources/Locale/en-US/_Goobstation/Heretic/store/heretic/heretic-catalog-side.ftl
> +    However, you will fall unconscious a short time after casting this spell.
rabbit is right

2024-10-23 12:50 UTC, Piras314 commented on Resources/Locale/en-US/_Goobstation/Heretic/store/heretic/heretic-catalog-side.ftl
> +    However, you will fall unconscious a short time after casting this spell.
rabbit is right

2024-10-23 12:50 UTC, Piras314 commented on Resources/Textures/_Goobstation/Heretic/book.rsi/meta.json
> +    "copyright": "Taken from TGStation, inhands made by @blooodyspy",
tgstation at commit :godmode:

2024-10-23 12:50 UTC, Piras314 commented on Resources/Textures/_Goobstation/Heretic/items.rsi/meta.json
> +    "copyright": "Taken from TGStation",
tgstation at commit :godmode:

2024-10-24 01:02 UTC, whateverusername0 commented on Content.Server/_Goobstation/Heretic/Abilities/HereticAbilitySystem.Void.cs
>          foreach (var pookie in topPriority)
:godmode:

2024-10-24 01:03 UTC, whateverusername0 commented on Content.Server/_Goobstation/Heretic/EntitySystems/EldritchInfluenceSystem.cs
> +        RaiseLocalEvent(user, ev);
it passed all checks wdym
you don't have to specify entityuid on entity<component> because it passes it automatically

2024-10-30 23:18 UTC, Aidenkrz commented
merge conflict

2024-11-01 15:55 UTC, whateverusername0 commented
hell

2024-11-03 06:57 UTC, whateverusername0 commented
@Aidenkrz merge conflicted

2024-11-03 17:08 UTC, merged