Security buffs
Goob-Station/Goob-Station pull request #953
Opened 2024-11-24 13:16 UTC by Aviu00

## About the PR

Added knockdown alert to distinguish it from stun.

Flashbangs now knock down for 10 seconds and stun for 2 seconds, these numbers scale with distance to the epicenter. This can be mitigated with over-ear headsets and combat hardsuit helmets, which reduce stun/knockdown range from 7 to 2 so no exploding flashbangs in your hands. Flashbangs now printable on secfab.

All sec and command now has over-ear headsets.

Tear gas is now stronger, also wearing sec/syndie/ert/deathsquad gas mask blocks smoke inhalation (even if internals are off).

Disabler bolts now pierce through glass (they are energy projectiles) and deal no heat damage (they are non-lethal projectiles).

Added energy bola which is smaller than regular one and is destroyed on removal. Printable on secfab. Regular bola stamina damage reduced to 25. I'll make bolas knockdown after [this](https://github.com/Goob-Station/Goob-Station/pull/912) gets merged

Added epinephrine autoinjector for sec and bso. It regenerates epinephrine VERY slowly. This would increase survivability since epi negates damage slowdown completely and also heals in crit. I made it also to increase move speed by 10%.

Jackboots now don't reduce damage slowdown (epinephrine does that). Instead, they reduce all stun and knockdown times by 40%.

Sec belt and webbing are now explosion resistant, no more grenades exploding.

Fixed a bug when you get paralyzed no matter what after soft stun.

Removed `StamcritResist` from reagents. It used "Adrenaline" key for some reason which was also used for `IgnoreSlowOnDamage`. And `StaminaModifier` does the same thing as `StamcritResist` I believe.

More changes in the changelog.

## Why / Balance

To encourage people to play security more.

## Technical details

On soft stun you get knocked down. After a while stamina starts regenerating, calling `TakeStaminaDamage` method with negative values and `immediate = true`. This caused a player to enter hard stamina crit.

## Media

Flashbang showcase

https://github.com/user-attachments/assets/183910d7-9b7e-4145-8244-f8790f4ce999

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl: Aviu
- add: Flashbangs now stun and knockdown people. Wear over-ear headset or combat hardsuit helmet to reduce flashbang effective range.
- add: All sec and command members received over-ear headsets.
- add: Energy bola was added for security.
- add: Flashbangs and e-bolas now printable on secfab.
- add: Epinephrine autoinjector was added for security.
- tweak: Epinephrine now speeds up by 10%.
- remove: Jackboots no longer reduce damage slowdown.
- add: Jackboots now reduce all stun and knockdown times.
- add: Combat hardsuit helmets now protect from flashes.
- tweak: Tear gas is now stronger.
- add: Wearing security, ert, syndie or deathsquad gas mask blocks smoke inhalation even if internals are off.
- tweak: Disabler bolts now pierce through glass but deal no heat damage.
- tweak: Stamcrit stun time is once again 6 seconds.
- tweak: Security hardsuits now have heat resistance.
- tweak: Sec belt and webbing now have 50% explosion resistance.
- fix: Now you won't get stunned no matter what after baton knockdown.

2024-11-24 13:30 UTC, BombasterDS approved these changes

2024-11-24 14:37 UTC, a-person5660 commented
give stun reduction to combat boots too (idk why they didnt get the jackboot buff in the first place)

2024-11-24 20:40 UTC, Golinth commented
> Tear gas is now stronger, also wearing sec/syndie/ert/deathsquad gas mask blocks smoke inhalation (even if internals are off).

But not the literal gas mask? it’s literally what they are designed for 

> Added epinephrine autoinjector for sec and bso. It regenerates epinephrine VERY slowly. This would increase survivability since epi negates damage slowdown completely and also heals in crit. I made it also to increase move speed by 10%.
>
> Jackboots now don't reduce damage slowdown (epinephrine does that). Instead, they reduce all stun and knockdown times by 40%.

Both of these are absurdly strong, even more so in the hands of a competent antag player. An antag with a rechargeable speed boost, no damage slowdown, and boots that make it nearly impossible to stun cuff would be a nightmare to catch

The rest of this is fine and are needed buffs, but specifically the jackboots are absurdly strong, and will make it nearly impossible to non-lethally apprehend an antag. Pretty sure this will have the opposite effect of what you want, where people who play sec will just be seen as loot piñatas for antags

2024-11-24 23:25 UTC, Piras314 requested changes

2024-11-24 23:25 UTC, Piras314 commented on Content.Shared/Ensnaring/Components/EnsnaringComponent.cs
> +    public bool DestroyOnRemove;
Set this to false by default

2024-11-25 04:47 UTC, JoeHammad1844 commented
this is mostly epic but the jackboot thing is over tuned, 20-25% is better I think.

Also, I wish that flashbangs would explode in sec belts while tear gas doesnt

2024-11-25 07:57 UTC, Aviu00 commented on Content.Shared/Ensnaring/Components/EnsnaringComponent.cs
> +    public bool DestroyOnRemove;
Bool fields are false by default in c#

2024-11-25 07:58 UTC, Aviu00 commented
I increased stamcrit stun time by one second, so I think jackboots buff is fine. You are still able to cuff a person wearing jackboots.

2024-11-25 08:00 UTC, Aviu00 commented
> give stun reduction to combat boots too (idk why they didnt get the jackboot buff in the first place)

Should I? That would buff the nukies. But on the other side, nukies who don't buy noslips can be slipped and disarmed easily.

2024-11-25 08:04 UTC, Aviu00 commented
> But not the literal gas mask? it’s literally what they are designed for

It is supposed to work only for combat gas masks. I might add description that they have filters for smoke. 

> Both of these are absurdly strong, even more so in the hands of a competent antag player. An antag with a rechargeable speed boost, no damage slowdown, and boots that make it nearly impossible to stun cuff would be a nightmare to catch

True, maybe I shouldn't make autoinjector rechargeable. Instead, I can make it use cartridges printable on secfab.

2024-11-25 09:22 UTC, JoeHammad1844 commented
> Both of these are absurdly strong, even more so in the hands of a competent antag player. An antag with a rechargeable speed boost, no damage slowdown, and boots that make it nearly impossible to stun cuff would be a nightmare to catch
> 
> True, maybe I shouldn't make autoinjector rechargeable. Instead, I can make it use cartridges printable on secfab.

better yet, the medipen refiller that was closed on wizden

2024-11-26 00:46 UTC, ARMOKS commented
Sydnies are going to kill a single cadet then have enough overpowered gear to end the entire station if this gets merged

2024-11-26 07:21 UTC, Aviu00 commented
> Sydnies are going to kill a single cadet then have enough overpowered gear to end the entire station if this gets merged

Yeah, but syndies will only get jackboots which are useless to them anyway because they probably have noslips. I'll make epi autoinjector cartridges so it's not rechargeable and not abuseable by antags.

2024-11-26 11:20 UTC, Aviu00 commented
Added descriptions for gas mask blocking smoke and headsets/hardsuit helmets blocking flashbang sounds.
Now epi autoinjector doesn't refill automatically. Instead, it uses cartridges printable on secfab.
Mercenary and combat boots now reduce stun time just like jackboots.

2024-11-26 11:30 UTC, Aviu00 commented
Uhh, I also might add a time limit to autoinjector so people don't just print a ton of cartridges and run around on epi.

2024-11-26 13:57 UTC, Piras314 requested changes

2024-11-26 13:57 UTC, Piras314 commented on Resources/Prototypes/Entities/Clothing/Shoes/boots.yml
> +    modifier: 0.6
A 40% stun time decrease just from a pair of shoes is crazy. Tiders are going to steal these all the time... they already steal sec's shoes constantly. Also why would you remove the ClothingSlowOnDamageModifier?

2024-11-26 14:01 UTC, Aviu00 commented on Resources/Prototypes/Entities/Clothing/Shoes/boots.yml
> +    modifier: 0.6
> A 40% stun time decrease just from a pair of shoes is crazy. Tiders are going to steal these all the time... they already steal sec's shoes constantly.

What should the numbers be then?

> Also why would you remove the ClothingSlowOnDamageModifier?

Because I added epinephrine autoinjectors for sec that completely cancel damage slowdown, so I don't think boots should also modify it. Should I add it back?

2024-11-26 14:06 UTC, Piras314 commented on Resources/Prototypes/Entities/Clothing/Shoes/boots.yml
> +    modifier: 0.6
I think you might as well keep it. I think a 20% reduction from the shoes is reasonable, you just have to remember tiders/antags are always going to get their hands on these.

2024-11-26 14:30 UTC, Piras314 approved these changes

2024-11-26 14:30 UTC, merged

2024-11-27 01:54 UTC, whateverusername0 commented
sec buff :godmode: