Blob. not ready yet, like a week away
Goob-Station/Goob-Station pull request #975
Opened 2024-11-26 12:59 UTC by jorgun

## About the PR

ports blob from  https://github.com/Rxup/space-station-14

credit to VigersRay for original code and
Roudenn for maintaining

## Why / Balance

## Technical details

## Media

## Requirements

- [ ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Blob added

2024-11-27 06:31 UTC, JustSome1Nearby commented
Did you actually yoink Blob from a russian server? Like translating it, fixing bugs and adding to Goob? This sure is nice, maybe would be also possible to do the same with Shadowlings and Vampires, think i saw them coded there

2024-11-27 09:27 UTC, JustSome1Nearby commented
Also what are you working on rn?

2024-11-28 04:15 UTC, Roudenn commented
Uuhhh it hurts to say but I was developing the blob update for quality-of-life and balance changes. It will take me so time to finish

Also a big mention here: blob IS NOT balanced for wizden weapons at all. Lasers on Backmen are 3-4 times stronger, so the blob is made to resist them.

2024-11-28 04:17 UTC, Roudenn commented
> Did you actually yoink Blob from a russian server? Like translating it, fixing bugs and adding to Goob? This sure is nice, maybe would be also possible to do the same with Shadowlings and Vampires, think i saw them coded there

idk who's shadowlings but vampires are shitcoded asf

2024-11-28 04:25 UTC, Roudenn commented
Please add Rxup in credits. He was helping me so much while developing

2024-11-28 16:13 UTC, jorgun commented
> Uuhhh it hurts to say but I was developing the blob update for quality-of-life and balance changes that still aren't in the main Backmen repo. It will take me some time to finish and add to the build, so get ready to port another blob PR again
> 
> Also a big mention here: blob IS NOT balanced for wizden weapons at all. Lasers on Backmen are 3-4 times stronger, so the blob is made to resist them.

ops. there was a QOL already that added downgrade. i was not aware you wherr doing more. 
And that explains why the core is so tanky.

2024-11-29 10:12 UTC, whateverusername0 requested changes
add blob to dynamic :godmode:

2024-11-29 10:22 UTC, whateverusername0 requested changes

2024-11-29 10:22 UTC, whateverusername0 commented on Content.Server/_Goobstation/GameTicking/Rules/Components/BlobRuleComponent.cs
> +    public SoundSpecifier? AlertAudio = new SoundPathSpecifier("/Audio/Announcements/attention.ogg");
change attention to our zombie breakout announcement
`Audio/Announcements/outbreak7.ogg` or `outbreak5.ogg` which you added

2024-11-29 10:22 UTC, whateverusername0 commented on Content.Server/_Goobstation/GameTicking/Rules/BlobRuleSystem.cs
> +                _alertLevelSystem.SetLevel(stationUid, StationSigma, true, true, true, true);
sigma alert :goberserk: 

change this to violet

2024-11-29 16:37 UTC, jorgun commented on Content.Server/_Goobstation/GameTicking/Rules/BlobRuleSystem.cs
> +                _alertLevelSystem.SetLevel(stationUid, StationSigma, true, true, true, true);
violet dont seem rigth either

2024-11-30 06:45 UTC, whateverusername0 commented on Content.Server/_Goobstation/GameTicking/Rules/BlobRuleSystem.cs
> +                _alertLevelSystem.SetLevel(stationUid, StationSigma, true, true, true, true);
but sigma does???

2024-11-30 06:47 UTC, whateverusername0 commented on Content.Server/_Goobstation/GameTicking/Rules/BlobRuleSystem.cs
> +                _alertLevelSystem.SetLevel(stationUid, StationSigma, true, true, true, true);
ok @jorgun just make it do only gamma code and that's it, like when blob reaches certain numbers of cells

2024-11-30 06:47 UTC, whateverusername0 commented on Content.Server/_Goobstation/GameTicking/Rules/BlobRuleSystem.cs
> +                _alertLevelSystem.SetLevel(stationUid, StationSigma, true, true, true, true);
or do delta because blob really is a delta type sit

2024-11-30 08:26 UTC, JustSome1Nearby commented
Wait are you not merging Blob just because people cant decide on the announcement?

2024-11-30 08:28 UTC, whateverusername0 commented
> [JustSome1Nearby](/JustSome1Nearby)

idk just waiting for piras or durk for it i'm not really a merge guy :trollface:

2024-11-30 08:31 UTC, JustSome1Nearby commented
Like it cant be merged or reviewed for merging untill the requested change is done? I think

2024-11-30 09:34 UTC, JustSome1Nearby commented
Also why didnt anyone do the same "porting" before? There are indeed abductors, vampires, shadowlings on other servers... Why not yoink it?

2024-11-30 11:18 UTC, whateverusername0 commented
> Also why didnt anyone do the same "porting" before? There are indeed abductors, vampires, shadowlings on other servers... Why not yoink it?

WYCI bro

2024-12-01 13:13 UTC, jorgun commented on Content.Server/_Goobstation/GameTicking/Rules/BlobRuleSystem.cs
> +                _alertLevelSystem.SetLevel(stationUid, StationSigma, true, true, true, true);
I set it to red on detect and delta on critical

2024-12-01 13:14 UTC, jorgun commented
> add blob to dynamic :godmode:

added to dynamic. as midround antag

2024-12-01 19:36 UTC, Piras314 commented
When I `forcepreset Blob` after doing `golobby` no blob spawns (on dev map if that matters), and when I spawn in the ghost role version of blob and take the role, it errors out saying it can't.

2024-12-01 20:21 UTC, Piras314 commented
still the same issue after that commit

2024-12-01 20:52 UTC, jorgun commented
> When I `forcepreset Blob` after doing `golobby` no blob spawns (on dev map if that matters), and when I spawn in the ghost role version of blob and take the role, it errors out saying it can't.

did you try spawning the blob mouse?

2024-12-01 21:08 UTC, Piras314 commented
well this definitely is not ready for merge if it doesn't work at all lmao

2024-12-01 23:34 UTC, jorgun commented
tested now whit gammode blob. host became a carrier, have 10 minutes to find a spot or get forced into blob

2024-12-02 00:06 UTC, jorgun commented
ghostrole mouse works. that spawns on the event. 
there is still a bug whit ghostrole blob. this only affects when splitting the blob
I belive this but ony happens on debug mode. will look into it more.

2024-12-02 00:52 UTC, Aidenkrz requested changes
I'll do a proper review later, didnt have a lot of time so just glanced through some of this.

2024-12-02 00:52 UTC, Aidenkrz commented on Content.Client/_Goobstation/Blob/BlobCarrierSystem.cs
> +        // do nothing
Why does this file exist if it does nothing

2024-12-02 00:52 UTC, Aidenkrz commented on Content.Client/_Goobstation/Blob/BlobMobSystem.cs
> +public sealed class BlobMobSystem : SharedBlobMobSystem
Same with this file

2024-12-02 00:52 UTC, Aidenkrz commented on Content.Client/_Goobstation/Blob/BlobPodSystem.cs
> +        // do nothing
here as well... why does this file exist

2024-12-02 00:52 UTC, Aidenkrz commented on Content.Client/_Goobstation/Blob/BlobbernautSystem.cs
> +
For why

2024-12-02 00:52 UTC, Aidenkrz commented on Content.Client/_Goobstation/Blob/ZombieBlobSystem.cs
> +public sealed class ZombieBlobSystem : SharedZombieBlobSystem;
Once again why

2024-12-02 00:52 UTC, Aidenkrz commented on Content.Client/_Goobstation/Nigthvision/NightVisionOverlay.cs
> +namespace Content.Client.NightVision
Wrong namespace

2024-12-02 00:52 UTC, Aidenkrz commented on Content.Client/_Goobstation/Nigthvision/NightVisionOverlay.cs
> +using Content.Shared.NightVision.Components; //creater - vladospupuos
huh? what does this comment mean

2024-12-02 00:52 UTC, Aidenkrz commented on Content.Client/_Goobstation/Nigthvision/NightVisionSystem.cs
> +namespace Content.Client.NightVision;
Also incorrect namespace

2024-12-02 00:52 UTC, Aidenkrz commented on Content.Server/Body/Components/RespiratorComponent.cs
> +        public bool HasImmunity = false;    //Goobstation - Blob
This literally just reflects if they have a component, why? its not even used anywhere.

2024-12-02 00:52 UTC, Aidenkrz commented on Content.Server/_Goobstation/Blob/BlobCarrierSystem.cs
> +namespace Content.Server.Blob;
Wrong namespace

2024-12-02 00:52 UTC, Aidenkrz commented on Content.Server/_Goobstation/Blob/BlobCarrierSystem.cs
> +    //[ValidatePrototypeId<LanguagePrototype>]
Instead of commenting this shit out, just delete it.

2024-12-02 00:52 UTC, Aidenkrz commented on Content.Server/_Goobstation/Blob/BlobChangeLevelEvent.cs
> +namespace Content.Server.Blob;
wrong namespace

2024-12-02 00:52 UTC, Aidenkrz commented on Content.Server/_Goobstation/Blob/BlobCoreActionSystem.cs
> +namespace Content.Server.Blob;
wrong namespace

2024-12-02 00:52 UTC, Aidenkrz commented on Content.Server/_Goobstation/Blob/BlobCoreSystem.cs
> +namespace Content.Server.Blob;
wrong namespace

2024-12-02 00:52 UTC, Aidenkrz commented on Content.Server/_Goobstation/Blob/BlobFactorySystem.cs
> +namespace Content.Server.Blob;
wrong namespace

2024-12-02 00:52 UTC, Aidenkrz commented on Content.Server/_Goobstation/Blob/BlobMobSystem.cs
> +namespace Content.Server.Blob;
wrong namespace

2024-12-02 00:52 UTC, Aidenkrz commented on Content.Server/_Goobstation/Body/RespiratorImmunityComponent.cs
> +public sealed partial class RespiratorImmunityComponent : Component
Why does this exist? especially on top of the previously mentioned bool

2024-12-02 00:52 UTC, Aidenkrz commented on Content.Server/_Goobstation/Body/RespiratorImmunityComponent.cs
> +namespace Content.Server.Body.Components;
wrong namespace

2024-12-02 00:52 UTC, Aidenkrz commented on Content.Server/_Goobstation/Blob/BlobNodeSystem.cs
> +namespace Content.Server.Blob;
wrong namespace

2024-12-02 00:52 UTC, Aidenkrz commented on Content.Server/_Goobstation/Blob/BlobObserverMover.cs
> +namespace Content.Server.Blob;
wrong namespace

2024-12-02 00:52 UTC, Aidenkrz commented on Content.Server/_Goobstation/Blob/BlobObserverSystem.cs
> +namespace Content.Server.Blob;
wrong namespace

2024-12-02 00:52 UTC, Aidenkrz commented on Content.Server/_Goobstation/Blob/BlobPodZombifyOperator.cs
> +namespace Content.Server.NPC.HTN.PrimitiveTasks.Operators.Specific;
wrong namespace

2024-12-02 00:52 UTC, Aidenkrz commented on Content.Server/_Goobstation/Blob/BlobResourceSystem.cs
> +namespace Content.Server.Blob;
wrong namespace

2024-12-02 00:52 UTC, Aidenkrz commented on Content.Server/_Goobstation/Blob/BlobTileSystem.cs
> +namespace Content.Server.Blob;
wrong namespace

2024-12-02 00:52 UTC, Aidenkrz commented on Content.Server/_Goobstation/Blob/BlobbernautSystem.cs
> +namespace Content.Server.Blob;
wrong namespace

2024-12-02 00:52 UTC, Aidenkrz commented on Content.Server/_Goobstation/Blob/Components/BlobFactoryComponent.cs
> +namespace Content.Server.Blob.Components;
wrong namespace

2024-12-02 00:52 UTC, Aidenkrz commented on Content.Server/_Goobstation/Blob/Components/BlobResourceComponent.cs
> +namespace Content.Server.Blob.Components;
wrong namespace

2024-12-02 01:16 UTC, jorgun commented on Content.Server/_Goobstation/Blob/NPC/BlobPod/BlobPodSystem.cs
> +namespace Content.Server.Blob.NPC.BlobPod;
yeah, understood

2024-12-02 01:18 UTC, jorgun commented on Resources/Prototypes/GameRules/events.yml
> +   # - id: BlobSpawn #Goobstation - Blob  (not added wile undergoing playtesting)
admins can force the event. so that if it is broken/ OP then game wont have to be hotfixed in order to sort it out

2024-12-02 01:58 UTC, jorgun commented on Content.Server/_Goobstation/Body/RespiratorImmunityComponent.cs
> +public sealed partial class RespiratorImmunityComponent : Component
this is a component. it checks the variable in tte respirator. doing so the zombie blobs do not need air.

2024-12-02 02:01 UTC, jorgun commented on Content.Server/Body/Components/RespiratorComponent.cs
> +        public bool HasImmunity = false;    //Goobstation - Blob
its is used in server._goobstation.Blob.ZombieBlobSystem.cs
its to make the zombies not need air, there might be a better way to do it. this code is old afterall

2024-12-02 02:02 UTC, jorgun commented on Content.Client/_Goobstation/Nigthvision/NightVisionOverlay.cs
> +using Content.Shared.NightVision.Components; //creater - vladospupuos
probably the creator of the nightvison part, i forgot to credit.

2024-12-02 02:04 UTC, jorgun commented on Content.Server/_Goobstation/Blob/BlobCarrierSystem.cs
> +    //[ValidatePrototypeId<LanguagePrototype>]
there is a lot of that. 
you want me to remove all comented out code?
there are soem what whud be good if we put this on the MRP server.

2024-12-02 05:34 UTC, whateverusername0 commented on Content.Server/Body/Components/RespiratorComponent.cs
> +        public bool HasImmunity = false;    //Goobstation - Blob
if you're not planning on turning them back to normal people you can remove barotrauma component from them

2024-12-02 06:03 UTC, whateverusername0 reviewed
fix whatever is causing this
![image](https://github.com/user-attachments/assets/2b21e9f3-7dd4-4419-b1b4-f75c53fd45c6)

also the comments

2024-12-02 06:03 UTC, whateverusername0 commented on Resources/Prototypes/secret_weights.yml
> +    #Blob: 0.00 # Blob not added to secret while undergoing playtesting
ig make blob midround only?

2024-12-02 06:35 UTC, jorgun commented
> fix whatever is causing this ![image](https://private-user-images.githubusercontent.com/113782077/391427950-2b21e9f3-7dd4-4419-b1b4-f75c53fd45c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMjE1NjIsIm5iZiI6MTczMzEyMTI2MiwicGF0aCI6Ii8xMTM3ODIwNzcvMzkxNDI3OTUwLTJiMjFlOWYzLTdkZDQtNDQxOS1iMWI0LWY3NWM1M2ZkNDVjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMlQwNjM0MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZTdjMjZiNzAwNWI1ZGU1OWQ0MzExNTQxM2I4NzU1ZTAzYjAxYWUzZjk3YzFlZWFlNWRlZGFhYjhhZGE3ZjdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kuPGKoYYxATiURfmEDb3y-LmRcsxWPL_GPJrl8sfrKM)
> 
> also the comments

This is caused by placing a blob and trying ti take it over via ghost role.
Use force antag verb blob

2024-12-02 15:23 UTC, jorgun commented on Content.Server/_Goobstation/Blob/BlobMobSystem.cs
> +   /* private void OnIntrinsicReceive(Entity<BlobSpeakComponent> ent, ref RadioReceiveEvent args)
becuse blobspeak is a part of giving blob its own blob language, we dont have a language system

2024-12-02 19:06 UTC, Roudenn commented on Content.Server/_Goobstation/Blob/BlobCoreActionSystem.cs
> +        /*if (targetTileEmpty)
It should merge two grids together if blob is trying to grow from one nearby grid to another. But grid merge is the shttiest thing ever and literally isn't implemented anywhere else, so it was scrapped until someone with enough skill comes and fixes it

2024-12-02 19:07 UTC, Roudenn commented on Content.Server/_Goobstation/Blob/BlobCoreSystem.cs
> +                _damageable.SetDamageModifierSetId(uid, "BaseBlob");
Backmen already has the PR that will fix that, but it isn't merged right now

2024-12-02 19:08 UTC, Roudenn commented on Content.Server/_Goobstation/Blob/BlobTileSystem.cs
> +    // private void OnStartup(EntityUid uid, BlobCellComponent component, ComponentStartup args)
Delete this safely, it's the oldest code that survived as a comment

2024-12-02 19:09 UTC, Roudenn commented on Content.Server/_Goobstation/Blob/Components/StationBlobConfigComponent.cs
> +    public int StageBegin { get; set; } = DefaultStageBegin;
I think Rxup did it for more performance, because calling for constants is faster? Idk but maybe the default value solution would be better

2024-12-02 19:10 UTC, Roudenn commented on Resources/Prototypes/_Goobstation/Blob/blob_tiles.yml
> +  description: The most important part of you. This is the brain and heart of the Blob. You cannot have more than one core (if you have a second one, it is not controlled by you), so you must protect
Descriptions should be rewritten, it was already done on Backmen, but only on russian.

2024-12-02 19:11 UTC, Roudenn commented on Resources/Prototypes/secret_weights.yml
> +    #Blob: 0.00 # Blob not added to secret while undergoing playtesting
Blob can work fine as a round-start antag, if balanced just right

2024-12-02 19:11 UTC, Roudenn commented on Resources/Prototypes/_Goobstation/Roles/Antags/blob.yml
> +    time: 54000 # 15h # Corvax-RoleTime
corvax comment detected

2024-12-02 21:20 UTC, jorgun commented on Resources/Prototypes/_Goobstation/Roles/Antags/blob.yml
> +    time: 54000 # 15h # Corvax-RoleTime
fixed

2024-12-02 21:20 UTC, jorgun commented on Resources/Prototypes/_Goobstation/Blob/blob_tiles.yml
> +  description: The most important part of you. This is the brain and heart of the Blob. You cannot have more than one core (if you have a second one, it is not controlled by you), so you must protect
shotened

2024-12-02 21:21 UTC, jorgun commented on Content.Server/_Goobstation/Blob/Components/StationBlobConfigComponent.cs
> +    public int StageBegin { get; set; } = DefaultStageBegin;
changed these, not sure if it mattered

2024-12-02 21:21 UTC, jorgun commented on Content.Shared/Physics/CollisionGroup.cs
> +    MobMask = Impassable | HighImpassable | MidImpassable | LowImpassable | BlobImpassable,
fixed

2024-12-02 21:21 UTC, jorgun commented on Content.Shared/_Goobstation/Blob/BlobChemTypedStorage.cs
> +    // Индексатор для доступа к полям через перечисление BlobChemType
fixed

2024-12-02 21:22 UTC, jorgun commented on Content.Shared/_Goobstation/Blob/BlobTypedStorage.cs
> +                case BlobTileType.Core:
not sure what you mean here

2024-12-02 21:22 UTC, jorgun commented on Resources/Locale/en-US/_Goobstation/blob/blob.ftl
> +ent-MobBlobBlobbernaut = Blobburnout
spelling error fixed

2024-12-03 13:15 UTC, whateverusername0 commented on Content.Server/_Goobstation/Blob/BlobCoreActionSystem.cs
> +        /*if (targetTileEmpty)
ight

2024-12-03 13:18 UTC, whateverusername0 commented on Content.Shared/_Goobstation/Blob/BlobTypedStorage.cs
> +                case BlobTileType.Core:
i mean what does it do? why is it here? does it have to look this eye gouging?

2024-12-03 13:19 UTC, whateverusername0 commented
> This is caused by placing a blob and trying ti take it over via ghost role. Use force antag verb blob

ngl it should be able to become a ghostrole

2024-12-03 19:57 UTC, Roudenn commented on Content.Shared/_Goobstation/Blob/BlobTypedStorage.cs
> +                case BlobTileType.Core:
> i mean what does it do? why is it here? does it have to look this eye gouging?

It was coded by Rxup, to replace the system with a lot of dictionaries with more optimized typed storage. Don't know if it works faster, but yeah it looks hilariously hardcoded

2024-12-03 20:08 UTC, jorgun commented
> > This is caused by placing a blob and trying ti take it over via ghost role. Use force antag verb blob
> 
> ngl it should be able to become a ghostrole

yes im working on it, it does work its just a debug error, it works on server.

2024-12-13 10:53 UTC, a-person5660 commented
is this still being worked on?

2024-12-13 11:31 UTC, JustSome1Nearby commented
It was supposed to be "next week"... Its the third "next week"

2024-12-13 16:14 UTC, Piras314 commented
@jorgun is this abandoned?

2024-12-13 16:20 UTC, whateverusername0 commented
@jorgun FIX MERGE CONFLICT

2024-12-14 14:12 UTC, AgentePanela commented
@jorgun FIX IT 💔

2024-12-14 14:56 UTC, JustSome1Nearby commented
We are begging at this point i guess

2024-12-14 16:12 UTC, jorgun commented
> @jorgun is this abandoned?

no, its just that anyting iu try to get rid of the debug error , and it is still there

2024-12-14 17:18 UTC, JustSome1Nearby commented
@jorgun can you not just, idk, leave it like that? Opening Heretic's book CRASHED the debug server for a LONG TIME... if it doesnt affect the game itself... why not? We dont want IDEAL code, we just want game mechanics! The fact that Ling has ALL abilities via actions is HORRIBLE, but no one cares!

2024-12-14 20:45 UTC, jorgun commented
well, yeah, the code works just fine, there is a debug error that comes up becuse it moves the mind from the core to the blob eye. then tries to attacth the ghost mind to the core, but the mind is allready attatched. this is a debug error. but i cant seem to find a way to get rid of it.

2024-12-14 22:22 UTC, AgentePanela commented
> well, yeah, the code works just fine, there is a debug error that comes up becuse it moves the mind from the core to the blob eye. then tries to attacth the ghost mind to the core, but the mind is allready attatched. this is a debug error. but i cant seem to find a way to get rid of it.

Leaving the debug error, how much of the blob is done?

2024-12-14 23:04 UTC, jorgun commented
> > well, yeah, the code works just fine, there is a debug error that comes up becuse it moves the mind from the core to the blob eye. then tries to attacth the ghost mind to the core, but the mind is allready attatched. this is a debug error. but i cant seem to find a way to get rid of it.
> 
> Leaving the debug error, how much of the blob is done?

its is a port, its all "done" 
5 chemical types:  brute, brute+fire,  emp, explosive, toxin.  
blob pod that turn corpses into blob zombies, blobbernaut ghostroles.
automatic spreading, 
upgradable tiles to strong and then to reflective
transfer of core
spliting core to make a blob ghostrole.

2024-12-14 23:06 UTC, JustSome1Nearby commented
Please for the love of Narsie push it then... Rimworld is gonna consume me, i need tge spessgame

2024-12-17 10:58 UTC, SolsticeOfTheWinter commented
its coming next week trust me bro

2024-12-17 11:31 UTC, JustSome1Nearby commented
> its coming next week trust me bro

All i want for Christmas is [to see Blob merged]

2024-12-18 02:00 UTC, merged

2024-12-18 05:38 UTC, JustSome1Nearby commented
This is a Christmas miracle