Add Stamps and Sprites
Goob-Station/Goob-Station pull request #985
Opened 2024-11-27 15:11 UTC by Lyacs

## About the PR

This PR is aimed to add more lore friendly stamps to the game. 

In this PR I also introduce a new faction inspired by an old one. UWU, the united workers utopia. Throught it I wish a bit more diversity to the usual antagonists, and provide I explaination on how revolutionaries get their flash technology. (see the comment on the first file in "files changed" for more infos) 

(Don't trust my github name, it's Weide not Lyacs normally)
## Why / Balance

Adding these stamps encourga further lore-friendly (tg-lore mostly) shenanigans, gimmics, maps buildings, admemes, etc. Eventually I hope it will encourage better coders to develop a bit the content related to these factions

While it will more likely be used in MRP (hopefully), I hope to see them, and the lore around them, also in LRP

## Technical details

Added sprites, stamps entity, and stamps components based on [#668](https://github.com/Goob-Station/Goob-Station/pull/668)
## Media

cybersun stamp example
![stamp-cybersun](https://github.com/user-attachments/assets/c15822c9-9981-40bf-a23c-1417e7431f87)
![paper_stamp-cybersun](https://github.com/user-attachments/assets/c5d81c73-47f3-4ca3-8209-4f2866159686)

ssc stamp example 
![stamp-ssc](https://github.com/user-attachments/assets/a9b7efc8-154d-4d7c-8734-f1b44b601a5b)
![paper_stamp-ssc](https://github.com/user-attachments/assets/c24cd34e-7f99-4438-b2e8-cacebc8dc302)

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Added a lot of stamps from NT corporates enemies as well as other lore related entities

2024-11-27 15:43 UTC, Lyacs commented
I managed to finally setup the test environment. This PR still has two small issues.

One fixed and one I need to work on.

2024-11-27 17:45 UTC, Lyacs commented
Nothing left to change on my end. I might add a few remaining stamps 'Gorlex', 'Tiger', 'Clown school', etc.  in the future, but not in this PR.

2024-11-29 16:56 UTC, Piras314 approved these changes

2024-11-29 16:57 UTC, Piras314 approved these changes
just to be sure, do these come from tgstation like the others? If they don't, you have to add their credits in the copyright section of the meta.json files

2024-11-29 17:08 UTC, Lyacs commented
I created the sprites myself (colouring), using the base of the other stamps in the files. For the sprite that is shown on the paper it's 100% from my own creations. 

So should I add myself in the credits ?

2024-11-29 21:15 UTC, Aidenkrz commented
> So should I add myself in the credits ?

Yes.
Also remove the UWU shit

2024-11-29 21:15 UTC, Aidenkrz requested changes
> So should I add myself in the credits ?

Yes
Also remove the UWU shit, we don't want that

2024-12-01 19:39 UTC, Piras314 commented
@Aidenkrz

2024-12-02 01:22 UTC, Aidenkrz requested changes
Mostly fine with this now, but none of these really spawn in anywhere, NTR should spawn with their stamp, and you should figure out ways for the rest of these to be obtainable, as admins can just make their own stamps, adding admin only ones is kind of useless and just bloat.

2024-12-02 01:22 UTC, Aidenkrz commented on Resources/Textures/Objects/Misc/bureaucracy.rsi/meta.json
> +      {
All of this is indented incorrectly, and there's 3 empty lines at the bottom for now reason.

2024-12-02 23:22 UTC, Lyacs commented
Closing it and making a brand new to save some

2024-12-02 23:22 UTC, closed without merging