Add some new posters
Goob-Station/Goob-Station pull request #997
Opened 2024-11-28 18:04 UTC by BeeRobynn

## About the PR
Adds some new posters

**Changelog**
:cl:
- add: Added some new posters

2024-11-28 19:01 UTC, LevitatingTree commented
no way you made this while i'm trying to figure out how to add my _own_ posters here as my first PR lmao, nice sprites

2024-11-28 19:18 UTC, Piras314 commented on Resources/Prototypes/Entities/Structures/Wallmounts/Signs/posters.yml
> +  - type: Sprite
We don't indent after components: in this codebase. Please remember this @coderabbitai

2024-11-28 19:18 UTC, Piras314 commented on Resources/Prototypes/Entities/Structures/Wallmounts/Signs/posters.yml
> +  name: "Danges of Fuel Tanks"
@BeeRobynn

2024-11-28 19:29 UTC, Lyacs commented
That reminds me I should update the copyright on my own PR

2024-11-28 19:43 UTC, Piras314 requested changes
🤓 👇

2024-11-28 19:43 UTC, Piras314 commented on Resources/Prototypes/Entities/Markers/Spawners/Random/posters.yml
> +      - PosterContrabandYakub
ermmm... you need a `# Goobstation` comment

2024-11-28 19:43 UTC, Piras314 commented on Resources/Prototypes/Entities/Structures/Wallmounts/Signs/posters.yml
> +# Goob posters
Erm.... these should go in `Resources/Prototypes/_Goobstation/Entities/Structures/Wallmounts/Signs/posters.yml 🤓 ☝️

2024-11-28 19:43 UTC, Piras314 commented on Resources/Textures/Structures/Wallmounts/posters.rsi/poster53_legit.png
eeeeeeeeeeeeeeeeeeeeerrrrrrrrrrmmmmmmmmmmm.... these should go in `Resources/Textures/_Goobstation/Structures/Wallmounts/posters/posters.rsi

2024-11-28 20:34 UTC, BeeRobynn commented on Resources/Prototypes/Entities/Structures/Wallmounts/Signs/posters.yml
> +# Goob posters
Putting them in goob messes with file paths and I dont know the workaround for giving the markers two paths for sprites

2024-11-28 20:50 UTC, Piras314 commented on Resources/Prototypes/Entities/Structures/Wallmounts/Signs/posters.yml
> +# Goob posters
you just specifically set the sprite within the sprite component to the goob rsi path

2024-11-29 16:33 UTC, Piras314 requested changes

2024-11-29 16:33 UTC, Piras314 commented on Resources/Prototypes/Entities/Structures/Wallmounts/Signs/posters.yml
> +# Goob posters
You forgot to delete these

2024-11-29 16:33 UTC, Piras314 commented on Resources/Textures/Structures/Wallmounts/posters.rsi/meta.json
> +    "copyright": "Taken from  at commit https://github.com/tgstation/tgstation/commit/f01de25493e2bd2706ef9b0303cb0d7b5e3e471b.     poster52_contraband, poster53_contraband and poster54_contraband ta
revert your changes to this file

2024-12-09 21:25 UTC, closed without merging